import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/main.c',
    '../../Source/pub_key.c',
    '../../../../../module/micro-ecc/uECC.c',
]
inc = [
    '../../Include/.',
    '../../.',
    '../../../../../module/micro-ecc/',
]
env.app_build('fota',src,inc)
