#include "ls_msp_otpv2.h"
#include "reg_cpu0_sys.h"
#include "field_manipulate.h"

void HAL_LSOTPV2_MSP_Init()
{
   REG_FIELD_WR(CPU0_SYS_CFG -> CPU0_SYS_CFG_REG1, CPU0_SYS_OTP_AHB_CLK_CLK_CG0_19, 0x1);
   REG_FIELD_WR(CPU0_SYS_CFG -> CPU0_SYS_CFG_REG5, CPU0_SYS_OTP_CYP_APB_CLK_CLK_CG0_6, 0x1);
}

void HAL_LSOTPV2_MSP_DeInit()
{
   REG_FIELD_WR(CPU0_SYS_CFG -> CPU0_SYS_CFG_REG1, CPU0_SYS_OTP_AHB_CLK_CLK_CG0_19, 0x0);
   REG_FIELD_WR(CPU0_SYS_CFG -> CPU0_SYS_CFG_REG5, CPU0_SYS_OTP_CYP_APB_CLK_CLK_CG0_6, 0x0);
}