import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    'fota_svc_server.c',
]
inc = [
    '.'
]
env.app_build('ble_fota_server',src,inc)
