import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/main.c',
    '../../Source/sig_mesh_ctl.c',
    '../../Source/sig_light_cfg.c',
    '../../Source/sig_mesh_vendor_event.c',
]
inc = [
    '../../Include/.',
    '../../.',
]
env.app_build('sig_mesh_provee',src,inc,mesh = True)
