import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    'pub_key.c',
    '../../../module/micro-ecc/uECC.c'
]
inc = [
    '.',
    '../../../module/micro-ecc/'
]
env['LINKSCRIPT'] = File(env.subst('compiler/$COMPILER/single_bank_fota_link.txt'))
env.app_build('fota',src,inc)
