stages:
  - build
  - test
  - deploy

.release_rule:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/v*/

include: 
  - 'tools/le501x/ci.yml'
  - 'tools/lm3050/ci.yml'
  - 'tools/leo/ci.yml'

doxygen:
  stage: build
  script:
    - mkdir _build
    - doxygen tools/Doxyfile