import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/uart_process.c',
    '../../Source/upgrade_process.c',
    '../../Source/main.c',
    '../../Source/iap_sha256.c',
]
inc = [
    '../../Include/.',
    '../../.',
]
env.app_build('iap_bootloader',src,inc,ble = False)
