import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/main.c',
]
inc = [
    '../../Include/.',
    '../../.',
]
env.app_build('ll_uart_polling',src,inc,ble = False)
