#include "ls_msp_emmc.h"
#include "field_manipulate.h"
#include "exception_isr.h"
#include "core_rv32.h"
#include "sys_stat.h"
#include "qsh.h"
#include "reg_sysc_app_cpu.h"
#include "reg_sysc_app_awo.h"
#include <stdint.h>

void lsqsh_emmc_txck_rxck_config()
{
    CLEAR_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_TX_RST_N_MASK);   //emmc1 tx soft reset
    CLEAR_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_RX_RST_N_MASK);   //emmc1 rx soft reset
    CLEAR_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_CORE_RST_N_MASK); //emmc1 base core soft reset
    CLEAR_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_TIM_RST_N_MASK);  //emmc1 timer soft reset

    SET_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_TX_RST_N_MASK);
    SET_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_RX_RST_N_MASK);
    SET_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_CORE_RST_N_MASK);
    SET_BIT(SYSC_APP_AWO->ETH_EMMC_RST, SYSC_APP_AWO_EMMC1_CLK_TIM_RST_N_MASK);

    CLEAR_BIT(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_TX_CG_MASK);
    SET_BIT(SYSC_APP_AWO->EMMC1_TX_RX_CLK, 0x40);  //25M 的64分频 390K
    REG_FIELD_WR(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_TX_SEL, 0x1); //his 25M
    SET_BIT(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_TX_CG_MASK);

    CLEAR_BIT(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_RX_CG_MASK);
    REG_FIELD_WR(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_RX_SEL, 0x4); //tx_clk_pad
    SET_BIT(SYSC_APP_AWO->EMMC1_TX_RX_CLK, SYSC_APP_AWO_EMMC1_CLK_RX_CG_MASK);

    CLEAR_BIT(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_CORE_CG_MASK);
    REG_FIELD_WR(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_CORE_DIV, 0); //不分频
    REG_FIELD_WR(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_CORE_SEL, 0x1); /* his 25M */
    SET_BIT(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_CORE_CG_MASK);

    CLEAR_BIT(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_TIM_CG_MASK);
    SET_BIT(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_TIM_DIV_MASK);
    REG_FIELD_WR(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_TIM_SEL, 0x1); /* hsi 25M */
    SET_BIT(SYSC_APP_AWO->EMMC1_CORE_TIM_CLK, SYSC_APP_AWO_EMMC1_CLK_TIM_CG_MASK);
}

void HAL_LSEMMC_MSP_Init(uint32_t mapbase)
{
    lsqsh_emmc_txck_rxck_config();
    switch (mapbase)
    {
        case LSEMMC1:
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_EMMC1_MASK;
            SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_CLR_EMMC1_MASK;
            SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_SET_EMMC1_MASK;
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_SET_EMMC1_MASK;
        break;
        case LSEMMC2:
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_EMMC2_MASK;
            SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_CLR_EMMC2_MASK;
            SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_SET_EMMC2_MASK;
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_SET_EMMC2_MASK;
        break;
        default:
        break;
    }
}

void HAL_LSEMMC_MSP_DeInit(uint32_t mapbase)
{
    switch (mapbase)
    {
        case LSEMMC1:
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_EMMC1_MASK;
        break;
        case LSEMMC2:
            SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_EMMC2_MASK;
        break;
        default:
        break;
    }
}