#include "ls_msp_ltpi.h"
#include "reg_sysc_app_cpu.h"
#include "core_rv32.h"
#include "platform.h"
#include "qsh.h"

void HAL_MSP_LTPI_PHY_Init()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_PHY_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_CLR_LTPI_PHY_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_SET_LTPI_PHY_MASK;
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_SET_LTPI_PHY_MASK;
}

void HAL_MSP_LTPI_PHY_DeInit()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_PHY_MASK;
}

void HAL_MSP_LTPI_HPM_Init()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_HPM_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_CLR_LTPI_HPM_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_SET_LTPI_HPM_MASK;
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_SET_LTPI_HPM_MASK;
}

void HAL_MSP_LTPI_HPM_DeInit()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_HPM_MASK;
}

void HAL_MSP_LTPI_SCM_Init()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_SCM_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_CLR_LTPI_SCM_MASK;
    SYSC_APP_CPU->PD_CPU_SRST1 = SYSC_APP_CPU_SRST_SET_LTPI_SCM_MASK;
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_SET_LTPI_SCM_MASK;
}
void HAL_MSP_LTPI_SCM_DeInit()
{
    SYSC_APP_CPU->PD_CPU_CLKG1 = SYSC_APP_CPU_CLKG_CLR_LTPI_SCM_MASK;
}