#include "ls_msp_otp_ctrl.h"
#include "reg_sysc_sec_cpu.h"


void HAL_MSP_OTP_CTRL_Init()
{
    SYSC_SEC_CPU->PD_CPU_CLKG[1] = SYSC_SEC_CPU_CLKG_CLR_OTP_CTRL_MASK;
    SYSC_SEC_CPU->PD_CPU_SRST[1] = SYSC_SEC_CPU_SRST_CLR_OTP_CTRL_MASK;
    SYSC_SEC_CPU->PD_CPU_SRST[1] = SYSC_SEC_CPU_SRST_SET_OTP_CTRL_MASK;
    SYSC_SEC_CPU->PD_CPU_CLKG[1] = SYSC_SEC_CPU_CLKG_SET_OTP_CTRL_MASK;
}

void HAL_MSP_OTP_CTRL_DeInit()
{
    SYSC_SEC_CPU->PD_CPU_CLKG[1] = SYSC_SEC_CPU_CLKG_CLR_OTP_CTRL_MASK;
}

