#ifndef PER_FUNC_MUX_H_
#define PER_FUNC_MUX_H_

#ifdef __cplusplus
extern "C" {
#endif

#define FIOA_ADTIM1_CH1      1
#define FIOA_ADTIM1_CH1N     2
#define FIOA_ADTIM1_CH2      3
#define FIOA_ADTIM1_CH2N     4
#define FIOA_ADTIM1_CH3      5
#define FIOA_ADTIM1_CH3N     6
#define FIOA_ADTIM1_CH4      7
#define FIOA_ADTIM1_ETR      8
#define FIOA_ADTIM1_BK       9
#define FIOA_I2C1_SCL        10
#define FIOA_I2C1_SDA        11
#define FIOA_I2C1_SMBA       12
#define FIOA_UART1_TXD       13
#define FIOA_UART1_RXD       14
#define FIOA_UART1_CTSN      15
#define FIOA_UART1_RTSN      16
#define FIOA_UART1_CK        17
#define FIOA_SPI1_SCK        18
#define FIOA_SPI1_NSS        19
#define FIOA_SPI1_MOSI       20
#define FIOA_SPI1_MISO       21
#define FIOA_SPI1_I2S        22
#define FIOA_FDCAN_TXD       23
#define FIOA_FDCAN_RXD       24
#define FIOA_PS2IF1_CLK      25
#define FIOA_PS2IF1_DAT      26
#define FIOA_PWM1            27
#define FIOA_CAP1            28
#define FIOA_OWM             29
#define FIOA_CEC             30
#define FIOA_PIS_CH1         31

#define FIOB_ADTIM2_CH1      1
#define FIOB_ADTIM2_CH1N     2
#define FIOB_ADTIM2_CH2      3
#define FIOB_ADTIM2_CH2N     4
#define FIOB_ADTIM2_CH3      5
#define FIOB_ADTIM2_CH3N     6
#define FIOB_ADTIM2_CH4      7
#define FIOB_ADTIM2_ETR      8
#define FIOB_ADTIM2_BK       9
#define FIOB_I2C2_SCL        10
#define FIOB_I2C2_SDA        11
#define FIOB_I2C2_SMBA       12
#define FIOB_UART2_TXD       13
#define FIOB_UART2_RXD       14
#define FIOB_UART2_CTSN      15
#define FIOB_UART2_RTSN      16
#define FIOB_UART2_CK        17
#define FIOB_SPI2_SCK        18
#define FIOB_SPI2_NSS        19
#define FIOB_SPI2_MOSI       20
#define FIOB_SPI2_MISO       21
#define FIOB_SPI2_I2S        22
#define FIOB_USB1_DP         23
#define FIOB_USB2_DM         24
#define FIOB_USB2_CID        25
#define FIOB_PS2IF2_CLK      26
#define FIOB_PS2IF2_DAT      27
#define FIOB_PWM2            28
#define FIOB_CAP2            29
#define FIOB_OWM             30
#define FIOB_CEC             31

#define FIOC_GPTIMA1_CH1     1
#define FIOC_GPTIMA1_CH2     2
#define FIOC_GPTIMA1_CH3     3
#define FIOC_GPTIMA1_CH4     4
#define FIOC_GPTIMA1_ETR     5
#define FIOC_I2C3_SCL        6
#define FIOC_I2C3_SDA        7
#define FIOC_I2C3_SMBA       8
#define FIOC_UART3_TXD       9
#define FIOC_UART3_RXD       10
#define FIOC_UART3_CTSN      11
#define FIOC_UART3_DSRN      12
#define FIOC_UART3_DCDN      13
#define FIOC_UART3_RIN       14
#define FIOC_UART3_RTSN      15
#define FIOC_UART3_DTRN      16
#define FIOC_UART3_DE        17
#define FIOC_UART3_RE        18
#define FIOC_SPI3_SCK        19
#define FIOC_SPI3_DATA0      20
#define FIOC_SPI3_DATA1      21
#define FIOC_SPI3_DATA2      22
#define FIOC_SPI3_DATA3      23
#define FIOC_USB2_DP         24
#define FIOC_USB2_DM         25
#define FIOC_USB2_CID        26
#define FIOC_PWM3            27
#define FIOC_PWM4            28
#define FIOC_CAP3            29
#define FIOC_CAP4            30
#define FIOC_PIS_CH2         31


#define FIOD_GPTIMA2_CH1     1
#define FIOD_GPTIMA2_CH2     2
#define FIOD_GPTIMA2_CH3     3
#define FIOD_GPTIMA2_CH4     4
#define FIOD_GPTIMA2_ETR     5
#define FIOD_I2C4_SCL        6
#define FIOD_I2C4_SDA        7
#define FIOD_I2C4_SMBA       8
#define FIOD_UART4_TXD       9
#define FIOD_UART4_RXD       10
#define FIOD_UART4_CTSN      11
#define FIOD_UART4_DSRN      12
#define FIOD_UART4_DCDN      13
#define FIOD_UART4_RIN       14
#define FIOD_UART4_RTSN      15
#define FIOD_UART4_DTRN      16
#define FIOD_UART4_DE        17
#define FIOD_UART4_RE        18
#define FIOD_SPI4_SCK        19
#define FIOD_SPI4_DATA0      20
#define FIOD_SPI4_DATA1      21
#define FIOD_SPI4_DATA2      22
#define FIOD_SPI4_DATA3      23
#define FIOD_MJTAG1_TRST     24
#define FIOD_MJTAG1_TDI      25
#define FIOD_MJTAG1_TCK      26
#define FIOD_MJTAG1_TMS      27
#define FIOD_MJTAG1_TDO      28
#define FIOD_DBG1_SCL        29
#define FIOD_DBG1_SDA        30
#define FIOD_PIS_CH3         31

#define FIOE_GPTIMB1_CH1     1
#define FIOE_GPTIMB1_CH2     2
#define FIOE_GPTIMB1_CH3     3
#define FIOE_GPTIMB1_CH4     4
#define FIOE_GPTIMB1_ETR     5
#define FIOE_I2C5_SCL        6
#define FIOE_I2C5_SDA        7
#define FIOE_I2C5_SMBA       8
#define FIOE_UART5_TXD       9
#define FIOE_UART5_RXD       10
#define FIOE_UART5_CTSN      11
#define FIOE_UART5_DSRN      12
#define FIOE_UART5_DCDN      13
#define FIOE_UART5_RIN       14
#define FIOE_UART5_RTSN      15
#define FIOE_UART5_DTRN      16
#define FIOE_UART5_DE        17
#define FIOE_UART5_RE        18
#define FIOE_SPI3_NSS1       19
#define FIOE_SPI4_NSS1       20
#define FIOE_PDM_DATA0       21
#define FIOE_PDM_DATA1       22
#define FIOE_PDM_CLK         23
#define FIOE_MJTAG2_TRST     24
#define FIOE_MJTAG2_TDI      25
#define FIOE_MJTAG2_TCK      26
#define FIOE_MJTAG2_TMS      27
#define FIOE_MJTAG2_TDO      28
#define FIOE_DBG2_SCL        29
#define FIOE_DBG2_SDA        30
#define FIOE_PIS_CH4         31


#define FIOF_GPTIMC1_CH1     1
#define FIOF_GPTIMC1_CH1N    2
#define FIOF_GPTIMC1_CH2     3
#define FIOF_GPTIMC1_BK      4
#define FIOF_I2C6_SCL        5
#define FIOF_I2C6_SDA        6
#define FIOF_I2C6_SMBA       7
#define FIOF_UART6_TXD       8
#define FIOF_UART6_RXD       9
#define FIOF_UART6_CTSN      10
#define FIOF_UART6_DSRN      11
#define FIOF_UART6_DCDN      12
#define FIOF_UART6_RIN       13
#define FIOF_UART6_RTSN      14
#define FIOF_UART6_DTRN      15
#define FIOF_UART6_DE        16
#define FIOF_UART6_RE        17
#define FIOF_SPI3_NSS2       18
#define FIOF_SPI4_NSS2       19
#define FIOF_PDM_DATA0       20
#define FIOF_PDM_DATA1       21
#define FIOF_PDM_CLK         22
#define FIOF_MJTAG3_TRST     23
#define FIOF_MJTAG3_TDI      24
#define FIOF_MJTAG3_TCK      25
#define FIOF_MJTAG3_TMS      26
#define FIOF_MJTAG3_TDO      27
#define FIOF_PWM5            28
#define FIOF_PWM6            29
#define FIOF_CAP5            30
#define FIOF_CAP6            31

#define FIOG_ADTIM1_CH1      1
#define FIOG_ADTIM1_CH1N     2
#define FIOG_ADTIM1_CH2      3
#define FIOG_ADTIM1_CH2N     4
#define FIOG_ADTIM1_CH3      5
#define FIOG_ADTIM1_CH3N     6
#define FIOG_ADTIM1_CH4      7
#define FIOG_ADTIM1_ETR      8
#define FIOG_ADTIM1_BK       9
#define FIOG_I2C7_SCL        10
#define FIOG_I2C7_SDA        11
#define FIOG_I2C7_SMBA       12
#define FIOG_UART1_TXD       13
#define FIOG_UART1_RXD       14
#define FIOG_UART1_CTSN      15
#define FIOG_UART1_RTSN      16
#define FIOG_UART1_CK        17
#define FIOG_SPI4_SCK        18
#define FIOG_SPI4_DATA0      19
#define FIOG_SPI4_DATA1      20
#define FIOG_SPI4_DATA2      21
#define FIOG_SPI4_DATA3      22
#define FIOG_FDCAN_TXD       23
#define FIOG_FDCAN_RXD       24
#define FIOG_PS2IF1_CLK      25
#define FIOG_PS2IF1_DAT      26
#define FIOG_PWM7            27
#define FIOG_CAP7            28
#define FIOG_OWM             29
#define FIOG_CEC             30
#define FIOG_PIS_CH5         31

#define FIOH_ADTIM2_CH1      1
#define FIOH_ADTIM2_CH1N     2
#define FIOH_ADTIM2_CH2      3
#define FIOH_ADTIM2_CH2N     4
#define FIOH_ADTIM2_CH3      5
#define FIOH_ADTIM2_CH3N     6
#define FIOH_ADTIM2_CH4      7
#define FIOH_ADTIM2_ETR      8
#define FIOH_ADTIM2_BK       9
#define FIOH_I2C8_SCL        10
#define FIOH_I2C8_SDA        11
#define FIOH_I2C8_SMBA       12
#define FIOH_UART2_TXD       13
#define FIOH_UART2_RXD       14
#define FIOH_UART2_CTSN      15
#define FIOH_UART2_RTSN      16
#define FIOH_UART2_CK        17
#define FIOH_DBG_HBUS_CLK    18
#define FIOH_DBG_CACHE1_MISS 19
#define FIOH_DBG_CACHE1_HIT  20
#define FIOH_SPI4_NSS1       21
#define FIOH_SPI4_NSS2       22
#define FIOH_USB2_DP         23
#define FIOH_USB2_DM         24
#define FIOH_USB2_CID        25
#define FIOH_PS2IF2_CLK      26
#define FIOH_PS2IF2_DAT      27
#define FIOH_PWM8            28
#define FIOH_CAP8            29
#define FIOH_CACHE2_MISS     30
#define FIOH_CACHE2_HIT      31

#define FIOI_GPTIMA1_CH1     1
#define FIOI_GPTIMA1_CH2     2
#define FIOI_GPTIMA1_CH3     3
#define FIOI_GPTIMA1_CH4     4
#define FIOI_GPTIMA1_ETR     5
#define FIOI_I2C9_SDA        6
#define FIOI_I2C9_SCL        7
#define FIOI_I2C9_SMBA       8
#define FIOI_UART3_TXD       9
#define FIOI_UART3_RXD       10
#define FIOI_UART3_CTSN      11
#define FIOI_UART3_DSRN      12
#define FIOI_UART3_DCDN      13
#define FIOI_UART3_RIN       14
#define FIOI_UART3_RTSN      15
#define FIOI_UART3_DTRN      16
#define FIOI_UART3_DE        17
#define FIOI_UART3_RE        18
#define FIOI_SPI3_SCK        19
#define FIOI_SPI3_DATA0      20
#define FIOI_SPI3_DATA1      21
#define FIOI_SPI3_DATA2      22
#define FIOI_SPI3_DATA3      23
#define FIOI_USB2_DP         24
#define FIOI_USB2_DM         25
#define FIOI_USB2_CID        26
#define FIOI_PWM9            27
#define FIOI_PWM10           28
#define FIOI_CAP9            29
#define FIOI_CAP10           30
#define FIOI_PIS_CH6         31

#define FIOJ_GPTIMA2_CH1     1
#define FIOJ_GPTIMA2_CH2     2
#define FIOJ_GPTIMA2_CH3     3
#define FIOJ_GPTIMA2_CH4     4
#define FIOJ_GPTIMA2_ETR     5
#define FIOJ_I2C10_SCL       6
#define FIOJ_I2C10_SDA       7
#define FIOJ_I2C10_SMBA      8
#define FIOJ_UART4_TXD       9
#define FIOJ_UART4_RXD       10
#define FIOJ_UART4_CTSN      11
#define FIOJ_UART4_DSRN      12
#define FIOJ_UART4_DCDN      13
#define FIOJ_UART4_RIN       14
#define FIOJ_UART4_RTSN      15
#define FIOJ_UART4_DTRN      16
#define FIOJ_UART4_DE        17
#define FIOJ_UART4_RE        18
#define FIOJ_SPI2_SCK        19
#define FIOJ_SPI2_NSS        20
#define FIOJ_SPI2_MOSI       21
#define FIOJ_SPI2_MISO       22
#define FIOJ_SPI2_I2S        23
#define FIOJ_MJTAG1_TRST     24
#define FIOJ_MJTAG1_TDI      25
#define FIOJ_MJTAG1_TCK      26
#define FIOJ_MJTAG1_TMS      27
#define FIOJ_MJTAG1_TDO      28
#define FIOJ_DBG1_SCL        29
#define FIOJ_DBG1_SDA        30
#define FIOJ_PIS_CH7         31

#define FIOK_GPTIMB1_CH1     1
#define FIOK_GPTIMB1_CH2     2
#define FIOK_GPTIMB1_CH3     3
#define FIOK_GPTIMB1_CH4     4
#define FIOK_GPTIMB1_ETR     5
#define FIOK_I2C7_SCL        6
#define FIOK_I2C7_SDA        7
#define FIOK_I2C7_SMBA       8
#define FIOK_I2C8_SCL        9
#define FIOK_I2C8_SDA        10
#define FIOK_I2C8_SMBA       11
#define FIOK_UART5_TXD       12
#define FIOK_UART5_RXD       13
#define FIOK_UART5_CTSN      14
#define FIOK_UART5_DSRN      15
#define FIOK_UART5_DE        16
#define FIOK_UART5_RE        17
#define FIOK_SPI2_SCK        18
#define FIOK_SPI2_NSS        19
#define FIOK_SPI2_MOSI       20
#define FIOK_SPI2_MISO       21
#define FIOK_MJTAG2_TRST     22
#define FIOK_MJTAG2_TDI      23
#define FIOK_MJTAG2_TCK      24
#define FIOK_MJTAG2_TMS      25
#define FIOK_MJTAG2_TDO      26
#define FIOK_DBG2_SCL        27
#define FIOK_DBG2_SDA        28
#define FIOK_PWM7            29
#define FIOK_CAP7            30
#define FIOK_PIS_CH8         31

#define FIOM_GPTIMC1_CH1     1
#define FIOM_GPTIMC1_CH1N    2
#define FIOM_GPTIMC1_CH2     3
#define FIOM_GPTIMC1_BK      4
#define FIOM_I2C9_SCL        5
#define FIOM_I2C9_SDA        6
#define FIOM_I2C9_SMBA       7
#define FIOM_I2C10_SCL       8
#define FIOM_I2C10_SDA       9
#define FIOM_I2C10_SMBA      10
#define FIOM_UART6_TXD       11
#define FIOM_UART6_RXD       12
#define FIOM_UART6_CTSN      13
#define FIOM_UART6_RTSN      14
#define FIOM_UART6_DE        15
#define FIOM_UART6_RE        16
#define FIOM_SPI2_SCK        17
#define FIOM_SPI2_NSS        18
#define FIOM_SPI2_MOSI       19
#define FIOM_SPI2_MISO       20
#define FIOM_MJTAG3_TRST     21
#define FIOM_MJTAG3_TDI      22
#define FIOM_MJTAG3_TCK      23
#define FIOM_MJTAG3_TMS      24
#define FIOM_MJTAG3_TDO      25
#define FIOM_PWM8            26
#define FIOM_PWM9            27
#define FIOM_PWM10           28
#define FIOM_CAP8            29
#define FIOM_CAP9            30
#define FIOM_CAP10           31

#define FION_ADTIM1_CH1      1
#define FION_ADTIM1_CH1N     2
#define FION_ADTIM1_CH2      3
#define FION_ADTIM1_CH2N     4
#define FION_ADTIM1_CH3      5
#define FION_ADTIM1_CH3N     6
#define FION_ADTIM1_CH4      7
#define FION_ADTIM1_ETR      8
#define FION_ADTIM1_BK       9
#define FION_I2C11_SCL       10
#define FION_I2C11_SDA       11
#define FION_I2C11_SMBA      12
#define FION_I2C12_SCL       13
#define FION_I2C12_SDA       14
#define FION_I2C12_SMBA      15
#define FION_UART1_TXD       16
#define FION_UART1_RXD       17
#define FION_UART1_CTSN      18
#define FION_UART1_RTSN      19
#define FION_FDCAN_TXD       20
#define FION_FDCAN_RXD       21
#define FION_PS2IF1_CLK      22
#define FION_PS2IF1_DAT      23
#define FION_PWM11           24
#define FION_PWM12           25
#define FION_PWM13           26
#define FION_CAP11           27
#define FION_CAP12           28
#define FION_CAP13           29
#define FION_PIS_CH5         30
#define FION_PIS_CH6         31

#define FIOQ_ADTIM2_CH1      1
#define FIOQ_ADTIM2_CH1N     2
#define FIOQ_ADTIM2_CH2      3
#define FIOQ_ADTIM2_CH2N     4
#define FIOQ_ADTIM2_CH3      5
#define FIOQ_ADTIM2_CH3N     6
#define FIOQ_ADTIM2_CH4      7
#define FIOQ_ADTIM2_ETR      8
#define FIOQ_ADTIM2_BK       9
#define FIOQ_I2C13_SCL       10
#define FIOQ_I2C13_SDA       11
#define FIOQ_I2C13_SMBA      12
#define FIOQ_I2C14_SCL       13
#define FIOQ_I2C14_SDA       14
#define FIOQ_I2C14_SMBA      15
#define FIOQ_UART2_TXD       16
#define FIOQ_UART2_RXD       17
#define FIOQ_UART2_CTSN      18
#define FIOQ_UART2_RTSN      19
#define FIOQ_DBG1_SCL        20
#define FIOQ_DBG1_SDA        21
#define FIOQ_PS2IF2_CLK      22
#define FIOQ_PS2IF2_DAT      23
#define FIOQ_PWM14           24
#define FIOQ_PWM15           25
#define FIOQ_PWM16           26
#define FIOQ_CAP14           27
#define FIOQ_CAP15           28
#define FIOQ_CAP16           29
#define FIOQ_PIS_CH7         30
#define FIOQ_PIS_CH8         31



#ifdef __cplusplus
}
#endif




#endif
