#ifndef REG_SYSC_AWO_TYPE_H_
#define REG_SYSC_AWO_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#define SYSC_AWO ((reg_sysc_awo_t *)QSH_SYSC_AWO_ADDR)

typedef struct
{
    volatile uint32_t EFUSE_CTRL; //0x0
    volatile uint32_t SLP_HLD_CTRL; //0x4
    volatile uint32_t CRYPT_WORD; //0x8
    volatile uint32_t AWO_CTRL; //0xc
    volatile uint32_t RESERVED0[5];
    volatile uint32_t DBG_RST_CTRL; //0x24
    volatile uint32_t PD_AWO_CLKG_SRST; //0x28
    volatile uint32_t PD_AWO_CLK_CTRL; //0x2c
    volatile uint32_t RESERVED1[1];
    volatile uint32_t PD_AWO_ANA0; //0x34
    volatile uint32_t PD_AWO_ANA1; //0x38
    volatile uint32_t CLK_OUT_SEL; //0x3c
    volatile uint32_t TX_DLL_CTRL; //0x40
    volatile uint32_t RX_DLL_CTRL; //0x44
    volatile uint32_t CLK_ETH_REG; //0x48
    volatile uint32_t ETH_CRG_CFG; //0x4c
    volatile uint32_t RESERVED2[12];
    struct IO_FUNC_
    {
        volatile uint32_t IO[8];
    } DIGITAL_FUNC_EN[4];
    // volatile uint32_t IO1_FUNC1_EN; //0x80
    // volatile uint32_t IO2_FUNC1_EN; //0x84
    // volatile uint32_t IO3_FUNC1_EN; //0x88
    // volatile uint32_t IO4_FUNC1_EN; //0x8c
    // volatile uint32_t IO5_FUNC1_EN; //0x90
    // volatile uint32_t IO6_FUNC1_EN; //0x94
    // volatile uint32_t IO7_FUNC1_EN; //0x98
    // volatile uint32_t RESERVED3[1];
    // volatile uint32_t IO1_FUNC2_EN; //0xa0
    // volatile uint32_t IO2_FUNC2_EN; //0xa4
    // volatile uint32_t IO3_FUNC2_EN; //0xa8
    // volatile uint32_t IO4_FUNC2_EN; //0xac
    // volatile uint32_t IO5_FUNC2_EN; //0xb0
    // volatile uint32_t IO6_FUNC2_EN; //0xb4
    // volatile uint32_t IO7_FUNC2_EN; //0xb8
    // volatile uint32_t RESERVED4[1];
    // volatile uint32_t IO1_FUNC3_EN; //0xc0
    // volatile uint32_t IO2_FUNC3_EN; //0xc4
    // volatile uint32_t IO3_FUNC3_EN; //0xc8
    // volatile uint32_t IO4_FUNC3_EN; //0xcc
    // volatile uint32_t IO5_FUNC3_EN; //0xd0
    // volatile uint32_t IO6_FUNC3_EN; //0xd4
    // volatile uint32_t IO7_FUNC3_EN; //0xd8
    // volatile uint32_t RESERVED5[1];
    // volatile uint32_t IO1_FUNC4_EN; //0xe0
    // volatile uint32_t IO2_FUNC4_EN; //0xe4
    // volatile uint32_t IO3_FUNC4_EN; //0xe8
    // volatile uint32_t IO4_FUNC4_EN; //0xec
    // volatile uint32_t IO5_FUNC4_EN; //0xf0
    // volatile uint32_t IO6_FUNC4_EN; //0xf4
    // volatile uint32_t IO7_FUNC4_EN; //0xf8
}reg_sysc_awo_t;

enum SYSC_AWO_REG_SLP_HLD_CTRL_FIELD
{
    SYSC_AWO_SLP_HLD_DLY_MASK = (int)0x3f,
    SYSC_AWO_SLP_HLD_DLY_POS = 0,
};

enum SYSC_AWO_REG_AWO_CTRL_FIELD
{
    SYSC_AWO_DBG_REQ_VLD_MASK = (int)0x1,
    SYSC_AWO_DBG_REQ_VLD_POS = 0,
    SYSC_AWO_CRYPT_EN_MASK = (int)0x80000000,
    SYSC_AWO_CRYPT_EN_POS = 31,
};

enum SYSC_AWO_REG_DBG_RST_CTRL_FIELD
{
    SYSC_AWO_DBG_RST_STP_DLY_MASK = (int)0xf0,
    SYSC_AWO_DBG_RST_STP_DLY_POS = 4,
};

enum SYSC_AWO_REG_PD_AWO_CLKG_SRST_FIELD
{
    SYSC_AWO_CLKG_SET_DIV_HBUS_MASK = (int)0x1,
    SYSC_AWO_CLKG_SET_DIV_HBUS_POS = 0,
    SYSC_AWO_CLKG_CLR_DIV_HBUS_MASK = (int)0x2,
    SYSC_AWO_CLKG_CLR_DIV_HBUS_POS = 1,
};

enum SYSC_AWO_REG_PD_AWO_CLK_CTRL_FIELD
{
    SYSC_AWO_CLK_DIV_PARA_HBUS_M1_MASK = (int)0xf,
    SYSC_AWO_CLK_DIV_PARA_HBUS_M1_POS = 0,
    SYSC_AWO_CLK_SEL_HBUS_MASK = (int)0xf0,
    SYSC_AWO_CLK_SEL_HBUS_POS = 4,
    SYSC_AWO_CLK_SEL_HBUS_FLT_MASK = (int)0x300,
    SYSC_AWO_CLK_SEL_HBUS_FLT_POS = 8,
    SYSC_AWO_CLK_SEL_QSPI_FLT_MASK = (int)0xc00,
    SYSC_AWO_CLK_SEL_QSPI_FLT_POS = 10,
    SYSC_AWO_HBUS_FLT_CTRL_MASK = (int)0xf000,
    SYSC_AWO_HBUS_FLT_CTRL_POS = 12,
    SYSC_AWO_QSPI_FLT_CTRL_MASK = (int)0xf0000,
    SYSC_AWO_QSPI_FLT_CTRL_POS = 16,
    SYSC_AWO_HSE_DCT_EN_MASK = (int)0x100000,
    SYSC_AWO_HSE_DCT_EN_POS = 20,
    SYSC_AWO_CLK_SEL_PBUS2_MASK = (int)0x600000,
    SYSC_AWO_CLK_SEL_PBUS2_POS = 21,
    SYSC_AWO_CLK_PBUS1_DIV4_MASK = (int)0x800000,
    SYSC_AWO_CLK_PBUS1_DIV4_POS = 23,
    SYSC_AWO_CLK_SEL_QSPI_MASK = (int)0x7000000,
    SYSC_AWO_CLK_SEL_QSPI_POS = 24,
    SYSC_AWO_CLK_SEL_PBUS3_MASK = (int)0x30000000,
    SYSC_AWO_CLK_SEL_PBUS3_POS = 28,
    SYSC_AWO_CLK_SEL_PBUS4_MASK = (int)0xc0000000,
    SYSC_AWO_CLK_SEL_PBUS4_POS = 30,
};

enum SYSC_AWO_REG_PD_AWO_ANA0_FIELD
{
    SYSC_AWO_AWO_DPLL_CTRL_MASK = (int)0x3fff,
    SYSC_AWO_AWO_DPLL_CTRL_POS = 0,
};

enum SYSC_AWO_REG_PD_AWO_ANA1_FIELD
{
    SYSC_AWO_AWO_CFG_HSICAL_MASK = (int)0x7fff,
    SYSC_AWO_AWO_CFG_HSICAL_POS = 0,
    SYSC_AWO_HSI_TC_TRIM_MASK = (int)0x70000,
    SYSC_AWO_HSI_TC_TRIM_POS = 16,
};

enum SYSC_AWO_REG_CLK_OUT_SEL_FIELD
{
    SYSC_AWO_CLK_OUT_SEL_MASK = (int)0x30000000,
    SYSC_AWO_CLK_OUT_SEL_POS = 28,
};

enum SYSC_AWO_REG_TX_DLL_CTRL_FIELD
{
    SYSC_AWO_TX_DLL_CTRL_MASK = (int)0x3ffff,
    SYSC_AWO_TX_DLL_CTRL_POS = 0,
};

enum SYSC_AWO_REG_RX_DLL_CTRL_FIELD
{
    SYSC_AWO_RX_DLL_CTRL_MASK = (int)0x3ffff,
    SYSC_AWO_RX_DLL_CTRL_POS = 0,
};

enum SYSC_AWO_REG_CLK_ETH_REG_FIELD
{
    SYSC_AWO_CLK_ETH_TX_REG_MASK = (int)0xfff,
    SYSC_AWO_CLK_ETH_TX_REG_POS = 0,
    SYSC_AWO_CLK_ETH_RX_REG_MASK = (int)0x7000,
    SYSC_AWO_CLK_ETH_RX_REG_POS = 12,
    SYSC_AWO_CLK_ETH_RMII_REG_MASK = (int)0x1ff0000,
    SYSC_AWO_CLK_ETH_RMII_REG_POS = 16,
    SYSC_AWO_TX_CLK_SEL_MASK = (int)0x10000000,
    SYSC_AWO_TX_CLK_SEL_POS = 28,
    SYSC_AWO_RX_CLK_SEL_MASK = (int)0x20000000,
    SYSC_AWO_RX_CLK_SEL_POS = 29,
};

enum SYSC_AWO_REG_ETH_CRG_CFG_FIELD
{
    SYSC_AWO_ETH_CRG_CFG_MASK = (int)0x3ffff,
    SYSC_AWO_ETH_CRG_CFG_POS = 0,
};

enum SYSC_AWO_REG_IO1_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOA_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOA_EN_POS = 0,
    SYSC_AWO_FUNC1_IOB_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOB_EN_POS = 16,
};

enum SYSC_AWO_REG_IO2_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOC_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOC_EN_POS = 0,
    SYSC_AWO_FUNC1_IOD_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOD_EN_POS = 16,
};

enum SYSC_AWO_REG_IO3_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOE_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOE_EN_POS = 0,
    SYSC_AWO_FUNC1_IOF_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOF_EN_POS = 16,
};

enum SYSC_AWO_REG_IO4_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOG_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOG_EN_POS = 0,
    SYSC_AWO_FUNC1_IOH_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOH_EN_POS = 16,
};

enum SYSC_AWO_REG_IO5_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOI_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOI_EN_POS = 0,
    SYSC_AWO_FUNC1_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOJ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO6_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_IOK_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_IOK_EN_POS = 0,
    SYSC_AWO_FUNC1_IOM_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOM_EN_POS = 16,
};

enum SYSC_AWO_REG_IO7_FUNC1_EN_FIELD
{
    SYSC_AWO_FUNC1_ION_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC1_ION_EN_POS = 0,
    SYSC_AWO_FUNC1_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC1_IOQ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO1_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOA_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOA_EN_POS = 0,
    SYSC_AWO_FUNC2_IOB_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOB_EN_POS = 16,
};

enum SYSC_AWO_REG_IO2_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOC_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOC_EN_POS = 0,
    SYSC_AWO_FUNC2_IOD_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOD_EN_POS = 16,
};

enum SYSC_AWO_REG_IO3_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOE_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOE_EN_POS = 0,
    SYSC_AWO_FUNC2_IOF_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOF_EN_POS = 16,
};

enum SYSC_AWO_REG_IO4_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOG_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOG_EN_POS = 0,
    SYSC_AWO_FUNC2_IOH_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOH_EN_POS = 16,
};

enum SYSC_AWO_REG_IO5_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOI_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOI_EN_POS = 0,
    SYSC_AWO_FUNC2_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOJ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO6_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOK_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOK_EN_POS = 0,
    SYSC_AWO_FUNC2_IOM_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOM_EN_POS = 16,
};

enum SYSC_AWO_REG_IO7_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_ION_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_ION_EN_POS = 0,
    SYSC_AWO_FUNC2_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC2_IOQ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO8_FUNC2_EN_FIELD
{
    SYSC_AWO_FUNC2_IOT_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC2_IOT_EN_POS = 0,
};

enum SYSC_AWO_REG_IO1_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOA_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOA_EN_POS = 0,
    SYSC_AWO_FUNC3_IOB_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOB_EN_POS = 16,
};

enum SYSC_AWO_REG_IO2_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOC_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOC_EN_POS = 0,
    SYSC_AWO_FUNC3_IOD_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOD_EN_POS = 16,
};

enum SYSC_AWO_REG_IO3_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOE_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOE_EN_POS = 0,
    SYSC_AWO_FUNC3_IOF_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOF_EN_POS = 16,
};

enum SYSC_AWO_REG_IO4_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOG_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOG_EN_POS = 0,
    SYSC_AWO_FUNC3_IOH_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOH_EN_POS = 16,
};

enum SYSC_AWO_REG_IO5_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOI_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOI_EN_POS = 0,
    SYSC_AWO_FUNC3_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOJ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO6_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_IOK_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_IOK_EN_POS = 0,
    SYSC_AWO_FUNC3_IOM_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOM_EN_POS = 16,
};

enum SYSC_AWO_REG_IO7_FUNC3_EN_FIELD
{
    SYSC_AWO_FUNC3_ION_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC3_ION_EN_POS = 0,
    SYSC_AWO_FUNC3_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC3_IOQ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO1_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOA_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOA_EN_POS = 0,
    SYSC_AWO_FUNC4_IOB_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOB_EN_POS = 16,
};

enum SYSC_AWO_REG_IO2_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOC_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOC_EN_POS = 0,
    SYSC_AWO_FUNC4_IOD_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOD_EN_POS = 16,
};

enum SYSC_AWO_REG_IO3_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOE_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOE_EN_POS = 0,
    SYSC_AWO_FUNC4_IOF_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOF_EN_POS = 16,
};

enum SYSC_AWO_REG_IO4_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOG_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOG_EN_POS = 0,
    SYSC_AWO_FUNC4_IOH_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOH_EN_POS = 16,
};

enum SYSC_AWO_REG_IO5_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOI_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOI_EN_POS = 0,
    SYSC_AWO_FUNC4_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOJ_EN_POS = 16,
};

enum SYSC_AWO_REG_IO6_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_IOK_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_IOK_EN_POS = 0,
    SYSC_AWO_FUNC4_IOM_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOM_EN_POS = 16,
};

enum SYSC_AWO_REG_IO7_FUNC4_EN_FIELD
{
    SYSC_AWO_FUNC4_ION_EN_MASK = (int)0xffff,
    SYSC_AWO_FUNC4_ION_EN_POS = 0,
    SYSC_AWO_FUNC4_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_AWO_FUNC4_IOQ_EN_POS = 16,
};

#endif

