#ifndef REG_SYSC_APP_CPU_TYPE_H_
#define REG_SYSC_APP_CPU_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#define SYSC_APP_CPU ((reg_sysc_app_cpu_t *)APP_SYSC_CPU_APP_ADDR)

typedef struct
{
    volatile uint32_t APP_CPU_SYSC; //0x0
    volatile uint32_t SYS_CLK; //0x4
    volatile uint32_t RESERVED0[2];
    volatile uint32_t PD_CPU_CLKG0; //0x10
    volatile uint32_t PD_CPU_CLKG1; //0x14
    volatile uint32_t PD_CPU_SRST; //0x18
    volatile uint32_t PD_CPU_SRST1; //0x1c
    volatile uint32_t APP_CPU_INTR; //0x20
    volatile uint32_t APP_CPU_IMSK; //0x24
    volatile uint32_t RESERVED1[2];
    volatile uint32_t FDCAN_TIMESTAMP_H; //0x30
    volatile uint32_t FDCAN_TIMESTAMP_L; //0x34
    volatile uint32_t FDCAN_TIM_CTRL; //0x38
    volatile uint32_t RESERVED2[1];
    volatile uint32_t DMAC1_CH01_SEL; //0x40
    volatile uint32_t DMAC1_CH23_SEL; //0x44
    volatile uint32_t DMAC1_CH45_SEL; //0x48
    volatile uint32_t DMAC1_CH67_SEL; //0x4c
    volatile uint32_t DMAC2_CH01_SEL; //0x50
    volatile uint32_t DMAC2_CH23_SEL; //0x54
    volatile uint32_t DMAC2_CH45_SEL; //0x58
    volatile uint32_t DMAC2_CH67_SEL; //0x5c
    volatile uint32_t ETH1_PHY_CTRL; //0x60
    volatile uint32_t RESERVED3[1];
    volatile uint32_t ETH2_PHY_CTRL; //0x68
    volatile uint32_t RESERVED4[1];
    volatile uint32_t EMMC1_DLL_CTRL; //0x70
    volatile uint32_t EMMC1_CTRL; //0x74
    volatile uint32_t EMMC2_DLL_CTRL; //0x78
    volatile uint32_t EMMC2_CTRL; //0x7c
    volatile uint32_t PSRAM_CTRL; //0x80
} reg_sysc_app_cpu_t;

enum SYSC_APP_CPU_REG_APP_CPU_SYSC_FIELD {
    SYSC_APP_CPU_CACHE2_MEMTST_MASK = (int)0x20,
    SYSC_APP_CPU_CACHE2_MEMTST_POS = 5,
    SYSC_APP_CPU_IWDT_DBG2_MASK = (int)0x100,
    SYSC_APP_CPU_IWDT_DBG2_POS = 8,
    SYSC_APP_CPU_WWDT_DBG2_MASK = (int)0x1000,
    SYSC_APP_CPU_WWDT_DBG2_POS = 12,
};

enum SYSC_APP_CPU_REG_SYS_CLK_FIELD {
    SYSC_APP_CPU_USB1_RX_DIFF_SEL_MASK = (int)0x10,
    SYSC_APP_CPU_USB1_RX_DIFF_SEL_POS = 4,
};

enum SYSC_APP_CPU_REG_PD_CPU_CLKG0_FIELD {
    SYSC_APP_CPU_CLKG_SET_CACHE2_MASK = (int)0x10,
    SYSC_APP_CPU_CLKG_SET_CACHE2_POS = 4,
    SYSC_APP_CPU_CLKG_CLR_CACHE2_MASK = (int)0x20,
    SYSC_APP_CPU_CLKG_CLR_CACHE2_POS = 5,
    SYSC_APP_CPU_CLKG_SET_QSPI2_MASK = (int)0x100,
    SYSC_APP_CPU_CLKG_SET_QSPI2_POS = 8,
    SYSC_APP_CPU_CLKG_CLR_QSPI2_MASK = (int)0x200,
    SYSC_APP_CPU_CLKG_CLR_QSPI2_POS = 9,
    SYSC_APP_CPU_CLKG_SET_USB1_MASK = (int)0x400,
    SYSC_APP_CPU_CLKG_SET_USB1_POS = 10,
    SYSC_APP_CPU_CLKG_CLR_USB1_MASK = (int)0x800,
    SYSC_APP_CPU_CLKG_CLR_USB1_POS = 11,
    SYSC_APP_CPU_CLKG_SET_USB2_MASK = (int)0x1000,
    SYSC_APP_CPU_CLKG_SET_USB2_POS = 12,
    SYSC_APP_CPU_CLKG_CLR_USB2_MASK = (int)0x2000,
    SYSC_APP_CPU_CLKG_CLR_USB2_POS = 13,
    SYSC_APP_CPU_CLKG_SET_DMAC1_MASK = (int)0x4000,
    SYSC_APP_CPU_CLKG_SET_DMAC1_POS = 14,
    SYSC_APP_CPU_CLKG_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_APP_CPU_CLKG_CLR_DMAC1_POS = 15,
    SYSC_APP_CPU_CLKG_SET_DMAC2_MASK = (int)0x10000,
    SYSC_APP_CPU_CLKG_SET_DMAC2_POS = 16,
    SYSC_APP_CPU_CLKG_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_APP_CPU_CLKG_CLR_DMAC2_POS = 17,
    SYSC_APP_CPU_CLKG_SET_ESPI1_MASK = (int)0x40000,
    SYSC_APP_CPU_CLKG_SET_ESPI1_POS = 18,
    SYSC_APP_CPU_CLKG_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_APP_CPU_CLKG_CLR_ESPI1_POS = 19,
    SYSC_APP_CPU_CLKG_SET_ESPI2_MASK = (int)0x100000,
    SYSC_APP_CPU_CLKG_SET_ESPI2_POS = 20,
    SYSC_APP_CPU_CLKG_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_APP_CPU_CLKG_CLR_ESPI2_POS = 21,
    SYSC_APP_CPU_CLKG_SET_LPC1_MASK = (int)0x400000,
    SYSC_APP_CPU_CLKG_SET_LPC1_POS = 22,
    SYSC_APP_CPU_CLKG_CLR_LPC1_MASK = (int)0x800000,
    SYSC_APP_CPU_CLKG_CLR_LPC1_POS = 23,
    SYSC_APP_CPU_CLKG_SET_LPC2_MASK = (int)0x1000000,
    SYSC_APP_CPU_CLKG_SET_LPC2_POS = 24,
    SYSC_APP_CPU_CLKG_CLR_LPC2_MASK = (int)0x2000000,
    SYSC_APP_CPU_CLKG_CLR_LPC2_POS = 25,
    SYSC_APP_CPU_CLKG_SET_FDCAN_MASK = (int)0x4000000,
    SYSC_APP_CPU_CLKG_SET_FDCAN_POS = 26,
    SYSC_APP_CPU_CLKG_CLR_FDCAN_MASK = (int)0x8000000,
    SYSC_APP_CPU_CLKG_CLR_FDCAN_POS = 27,
    SYSC_APP_CPU_CLKG_SET_PSRAM_MASK = (int)0x10000000,
    SYSC_APP_CPU_CLKG_SET_PSRAM_POS = 28,
    SYSC_APP_CPU_CLKG_CLR_PSRAM_MASK = (int)0x20000000,
    SYSC_APP_CPU_CLKG_CLR_PSRAM_POS = 29,
    SYSC_APP_CPU_CLKG_SET_USB2_CTL_MASK = (int)0x40000000,
    SYSC_APP_CPU_CLKG_SET_USB2_CTL_POS = 30,
    SYSC_APP_CPU_CLKG_CLR_USB2_CTL_MASK = (int)0x80000000,
    SYSC_APP_CPU_CLKG_CLR_USB2_CTL_POS = 31,
};

enum SYSC_APP_CPU_REG_PD_CPU_CLKG1_FIELD {
    SYSC_APP_CPU_CLKG_SET_SPI3_MASK = (int)0x1,
    SYSC_APP_CPU_CLKG_SET_SPI3_POS = 0,
    SYSC_APP_CPU_CLKG_CLR_SPI3_MASK = (int)0x2,
    SYSC_APP_CPU_CLKG_CLR_SPI3_POS = 1,
    SYSC_APP_CPU_CLKG_SET_SPI4_MASK = (int)0x4,
    SYSC_APP_CPU_CLKG_SET_SPI4_POS = 2,
    SYSC_APP_CPU_CLKG_CLR_SPI4_MASK = (int)0x8,
    SYSC_APP_CPU_CLKG_CLR_SPI4_POS = 3,
    SYSC_APP_CPU_CLKG_SET_SPIS1_MASK = (int)0x10,
    SYSC_APP_CPU_CLKG_SET_SPIS1_POS = 4,
    SYSC_APP_CPU_CLKG_CLR_SPIS1_MASK = (int)0x20,
    SYSC_APP_CPU_CLKG_CLR_SPIS1_POS = 5,
    SYSC_APP_CPU_CLKG_SET_SPIS2_MASK = (int)0x40,
    SYSC_APP_CPU_CLKG_SET_SPIS2_POS = 6,
    SYSC_APP_CPU_CLKG_CLR_SPIS2_MASK = (int)0x80,
    SYSC_APP_CPU_CLKG_CLR_SPIS2_POS = 7,
    SYSC_APP_CPU_CLKG_SET_SPI1_FLT_MASK = (int)0x100,
    SYSC_APP_CPU_CLKG_SET_SPI1_FLT_POS = 8,
    SYSC_APP_CPU_CLKG_CLR_SPI1_FLT_MASK = (int)0x200,
    SYSC_APP_CPU_CLKG_CLR_SPI1_FLT_POS = 9,
    SYSC_APP_CPU_CLKG_SET_SPI2_FLT_MASK = (int)0x400,
    SYSC_APP_CPU_CLKG_SET_SPI2_FLT_POS = 10,
    SYSC_APP_CPU_CLKG_CLR_SPI2_FLT_MASK = (int)0x800,
    SYSC_APP_CPU_CLKG_CLR_SPI2_FLT_POS = 11,
    SYSC_APP_CPU_CLKG_SET_SPI3_FLT_MASK = (int)0x1000,
    SYSC_APP_CPU_CLKG_SET_SPI3_FLT_POS = 12,
    SYSC_APP_CPU_CLKG_CLR_SPI3_FLT_MASK = (int)0x2000,
    SYSC_APP_CPU_CLKG_CLR_SPI3_FLT_POS = 13,
    SYSC_APP_CPU_CLKG_SET_SPI4_FLT_MASK = (int)0x4000,
    SYSC_APP_CPU_CLKG_SET_SPI4_FLT_POS = 14,
    SYSC_APP_CPU_CLKG_CLR_SPI4_FLT_MASK = (int)0x8000,
    SYSC_APP_CPU_CLKG_CLR_SPI4_FLT_POS = 15,
    SYSC_APP_CPU_CLKG_SET_ETH1_MASK = (int)0x10000,
    SYSC_APP_CPU_CLKG_SET_ETH1_POS = 16,
    SYSC_APP_CPU_CLKG_CLR_ETH1_MASK = (int)0x20000,
    SYSC_APP_CPU_CLKG_CLR_ETH1_POS = 17,
    SYSC_APP_CPU_CLKG_SET_ETH2_MASK = (int)0x40000,
    SYSC_APP_CPU_CLKG_SET_ETH2_POS = 18,
    SYSC_APP_CPU_CLKG_CLR_ETH2_MASK = (int)0x80000,
    SYSC_APP_CPU_CLKG_CLR_ETH2_POS = 19,
    SYSC_APP_CPU_CLKG_SET_EMMC1_MASK = (int)0x100000,
    SYSC_APP_CPU_CLKG_SET_EMMC1_POS = 20,
    SYSC_APP_CPU_CLKG_CLR_EMMC1_MASK = (int)0x200000,
    SYSC_APP_CPU_CLKG_CLR_EMMC1_POS = 21,
    SYSC_APP_CPU_CLKG_SET_EMMC2_MASK = (int)0x400000,
    SYSC_APP_CPU_CLKG_SET_EMMC2_POS = 22,
    SYSC_APP_CPU_CLKG_CLR_EMMC2_MASK = (int)0x800000,
    SYSC_APP_CPU_CLKG_CLR_EMMC2_POS = 23,
    SYSC_APP_CPU_CLKG_SET_LTPI_SCM_MASK = (int)0x1000000,
    SYSC_APP_CPU_CLKG_SET_LTPI_SCM_POS = 24,
    SYSC_APP_CPU_CLKG_CLR_LTPI_SCM_MASK = (int)0x2000000,
    SYSC_APP_CPU_CLKG_CLR_LTPI_SCM_POS = 25,
    SYSC_APP_CPU_CLKG_SET_LTPI_HPM_MASK = (int)0x4000000,
    SYSC_APP_CPU_CLKG_SET_LTPI_HPM_POS = 26,
    SYSC_APP_CPU_CLKG_CLR_LTPI_HPM_MASK = (int)0x8000000,
    SYSC_APP_CPU_CLKG_CLR_LTPI_HPM_POS = 27,
    SYSC_APP_CPU_CLKG_SET_LTPI_PHY_MASK = (int)0x10000000,
    SYSC_APP_CPU_CLKG_SET_LTPI_PHY_POS = 28,
    SYSC_APP_CPU_CLKG_CLR_LTPI_PHY_MASK = (int)0x20000000,
    SYSC_APP_CPU_CLKG_CLR_LTPI_PHY_POS = 29,
};

enum SYSC_APP_CPU_REG_PD_CPU_SRST_FIELD {
    SYSC_APP_CPU_SRST_SET_CACHE2_MASK = (int)0x10,
    SYSC_APP_CPU_SRST_SET_CACHE2_POS = 4,
    SYSC_APP_CPU_SRST_CLR_CACHE2_MASK = (int)0x20,
    SYSC_APP_CPU_SRST_CLR_CACHE2_POS = 5,
    SYSC_APP_CPU_SRST_SET_QSPI2_MASK = (int)0x100,
    SYSC_APP_CPU_SRST_SET_QSPI2_POS = 8,
    SYSC_APP_CPU_SRST_CLR_QSPI2_MASK = (int)0x200,
    SYSC_APP_CPU_SRST_CLR_QSPI2_POS = 9,
    SYSC_APP_CPU_SRST_SET_USB1_MASK = (int)0x400,
    SYSC_APP_CPU_SRST_SET_USB1_POS = 10,
    SYSC_APP_CPU_SRST_CLR_USB1_MASK = (int)0x800,
    SYSC_APP_CPU_SRST_CLR_USB1_POS = 11,
    SYSC_APP_CPU_SRST_SET_USB2_MASK = (int)0x1000,
    SYSC_APP_CPU_SRST_SET_USB2_POS = 12,
    SYSC_APP_CPU_SRST_CLR_USB2_MASK = (int)0x2000,
    SYSC_APP_CPU_SRST_CLR_USB2_POS = 13,
    SYSC_APP_CPU_SRST_SET_DMAC1_MASK = (int)0x4000,
    SYSC_APP_CPU_SRST_SET_DMAC1_POS = 14,
    SYSC_APP_CPU_SRST_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_APP_CPU_SRST_CLR_DMAC1_POS = 15,
    SYSC_APP_CPU_SRST_SET_DMAC2_MASK = (int)0x10000,
    SYSC_APP_CPU_SRST_SET_DMAC2_POS = 16,
    SYSC_APP_CPU_SRST_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_APP_CPU_SRST_CLR_DMAC2_POS = 17,
    SYSC_APP_CPU_SRST_SET_ESPI1_MASK = (int)0x40000,
    SYSC_APP_CPU_SRST_SET_ESPI1_POS = 18,
    SYSC_APP_CPU_SRST_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_APP_CPU_SRST_CLR_ESPI1_POS = 19,
    SYSC_APP_CPU_SRST_SET_ESPI2_MASK = (int)0x100000,
    SYSC_APP_CPU_SRST_SET_ESPI2_POS = 20,
    SYSC_APP_CPU_SRST_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_APP_CPU_SRST_CLR_ESPI2_POS = 21,
    SYSC_APP_CPU_SRST_SET_LPC1_MASK = (int)0x400000,
    SYSC_APP_CPU_SRST_SET_LPC1_POS = 22,
    SYSC_APP_CPU_SRST_CLR_LPC1_MASK = (int)0x800000,
    SYSC_APP_CPU_SRST_CLR_LPC1_POS = 23,
    SYSC_APP_CPU_SRST_SET_LPC2_MASK = (int)0x1000000,
    SYSC_APP_CPU_SRST_SET_LPC2_POS = 24,
    SYSC_APP_CPU_SRST_CLR_LPC2_MASK = (int)0x2000000,
    SYSC_APP_CPU_SRST_CLR_LPC2_POS = 25,
    SYSC_APP_CPU_SRST_SET_FDCAN_MASK = (int)0x4000000,
    SYSC_APP_CPU_SRST_SET_FDCAN_POS = 26,
    SYSC_APP_CPU_SRST_CLR_FDCAN_MASK = (int)0x8000000,
    SYSC_APP_CPU_SRST_CLR_FDCAN_POS = 27,
    SYSC_APP_CPU_SRST_SET_PSRAM_MASK = (int)0x10000000,
    SYSC_APP_CPU_SRST_SET_PSRAM_POS = 28,
    SYSC_APP_CPU_SRST_CLR_PSRAM_MASK = (int)0x20000000,
    SYSC_APP_CPU_SRST_CLR_PSRAM_POS = 29,
};

enum SYSC_APP_CPU_REG_PD_CPU_SRST1_FIELD {
    SYSC_APP_CPU_SRST_SET_SPI3_MASK = (int)0x1,
    SYSC_APP_CPU_SRST_SET_SPI3_POS = 0,
    SYSC_APP_CPU_SRST_CLR_SPI3_MASK = (int)0x2,
    SYSC_APP_CPU_SRST_CLR_SPI3_POS = 1,
    SYSC_APP_CPU_SRST_SET_SPI4_MASK = (int)0x4,
    SYSC_APP_CPU_SRST_SET_SPI4_POS = 2,
    SYSC_APP_CPU_SRST_CLR_SPI4_MASK = (int)0x8,
    SYSC_APP_CPU_SRST_CLR_SPI4_POS = 3,
    SYSC_APP_CPU_SRST_SET_SPIS1_MASK = (int)0x10,
    SYSC_APP_CPU_SRST_SET_SPIS1_POS = 4,
    SYSC_APP_CPU_SRST_CLR_SPIS1_MASK = (int)0x20,
    SYSC_APP_CPU_SRST_CLR_SPIS1_POS = 5,
    SYSC_APP_CPU_SRST_SET_SPIS2_MASK = (int)0x40,
    SYSC_APP_CPU_SRST_SET_SPIS2_POS = 6,
    SYSC_APP_CPU_SRST_CLR_SPIS2_MASK = (int)0x80,
    SYSC_APP_CPU_SRST_CLR_SPIS2_POS = 7,
    SYSC_APP_CPU_SRST_SET_SPI1_FLT_MASK = (int)0x100,
    SYSC_APP_CPU_SRST_SET_SPI1_FLT_POS = 8,
    SYSC_APP_CPU_SRST_CLR_SPI1_FLT_MASK = (int)0x200,
    SYSC_APP_CPU_SRST_CLR_SPI1_FLT_POS = 9,
    SYSC_APP_CPU_SRST_SET_SPI2_FLT_MASK = (int)0x400,
    SYSC_APP_CPU_SRST_SET_SPI2_FLT_POS = 10,
    SYSC_APP_CPU_SRST_CLR_SPI2_FLT_MASK = (int)0x800,
    SYSC_APP_CPU_SRST_CLR_SPI2_FLT_POS = 11,
    SYSC_APP_CPU_SRST_SET_SPI3_FLT_MASK = (int)0x1000,
    SYSC_APP_CPU_SRST_SET_SPI3_FLT_POS = 12,
    SYSC_APP_CPU_SRST_CLR_SPI3_FLT_MASK = (int)0x2000,
    SYSC_APP_CPU_SRST_CLR_SPI3_FLT_POS = 13,
    SYSC_APP_CPU_SRST_SET_SPI4_FLT_MASK = (int)0x4000,
    SYSC_APP_CPU_SRST_SET_SPI4_FLT_POS = 14,
    SYSC_APP_CPU_SRST_CLR_SPI4_FLT_MASK = (int)0x8000,
    SYSC_APP_CPU_SRST_CLR_SPI4_FLT_POS = 15,
    SYSC_APP_CPU_SRST_SET_ETH1_MASK = (int)0x10000,
    SYSC_APP_CPU_SRST_SET_ETH1_POS = 16,
    SYSC_APP_CPU_SRST_CLR_ETH1_MASK = (int)0x20000,
    SYSC_APP_CPU_SRST_CLR_ETH1_POS = 17,
    SYSC_APP_CPU_SRST_SET_ETH2_MASK = (int)0x40000,
    SYSC_APP_CPU_SRST_SET_ETH2_POS = 18,
    SYSC_APP_CPU_SRST_CLR_ETH2_MASK = (int)0x80000,
    SYSC_APP_CPU_SRST_CLR_ETH2_POS = 19,
    SYSC_APP_CPU_SRST_SET_EMMC1_MASK = (int)0x100000,
    SYSC_APP_CPU_SRST_SET_EMMC1_POS = 20,
    SYSC_APP_CPU_SRST_CLR_EMMC1_MASK = (int)0x200000,
    SYSC_APP_CPU_SRST_CLR_EMMC1_POS = 21,
    SYSC_APP_CPU_SRST_SET_EMMC2_MASK = (int)0x400000,
    SYSC_APP_CPU_SRST_SET_EMMC2_POS = 22,
    SYSC_APP_CPU_SRST_CLR_EMMC2_MASK = (int)0x800000,
    SYSC_APP_CPU_SRST_CLR_EMMC2_POS = 23,
    SYSC_APP_CPU_SRST_SET_LTPI_SCM_MASK = (int)0x1000000,
    SYSC_APP_CPU_SRST_SET_LTPI_SCM_POS = 24,
    SYSC_APP_CPU_SRST_CLR_LTPI_SCM_MASK = (int)0x2000000,
    SYSC_APP_CPU_SRST_CLR_LTPI_SCM_POS = 25,
    SYSC_APP_CPU_SRST_SET_LTPI_HPM_MASK = (int)0x4000000,
    SYSC_APP_CPU_SRST_SET_LTPI_HPM_POS = 26,
    SYSC_APP_CPU_SRST_CLR_LTPI_HPM_MASK = (int)0x8000000,
    SYSC_APP_CPU_SRST_CLR_LTPI_HPM_POS = 27,
    SYSC_APP_CPU_SRST_SET_LTPI_PHY_MASK = (int)0x10000000,
    SYSC_APP_CPU_SRST_SET_LTPI_PHY_POS = 28,
    SYSC_APP_CPU_SRST_CLR_LTPI_PHY_MASK = (int)0x20000000,
    SYSC_APP_CPU_SRST_CLR_LTPI_PHY_POS = 29,
};

enum SYSC_APP_CPU_REG_APP_CPU_INTR_FIELD {
    SYSC_APP_CPU_APP_CPU_INTR_MASK = (int)0x1,
    SYSC_APP_CPU_APP_CPU_INTR_POS = 0,
};

enum SYSC_APP_CPU_REG_APP_CPU_IMSK_FIELD {
    SYSC_APP_CPU_APP_CPU_IMSK_MASK = (int)0x1,
    SYSC_APP_CPU_APP_CPU_IMSK_POS = 0,
};

enum SYSC_APP_CPU_REG_FDCAN_TIMESTAMP_H_FIELD {
    SYSC_APP_CPU_FDCAN_TIMESTAMP_H_MASK = (int)0xffffffff,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_H_POS = 0,
};

enum SYSC_APP_CPU_REG_FDCAN_TIMESTAMP_L_FIELD {
    SYSC_APP_CPU_FDCAN_TIMESTAMP_L_MASK = (int)0xffffffff,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_L_POS = 0,
};

enum SYSC_APP_CPU_REG_FDCAN_TIM_CTRL_FIELD {
    SYSC_APP_CPU_FDCAN_TIMESTAMP_ENABLE_MASK = (int)0x1,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_ENABLE_POS = 0,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_CLEAR_MASK = (int)0x2,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_CLEAR_POS = 1,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_PRECALER_MASK = (int)0xff00,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_PRECALER_POS = 8,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_STEP_MASK = (int)0xff0000,
    SYSC_APP_CPU_FDCAN_TIMESTAMP_STEP_POS = 16,
    SYSC_APP_CPU_FDCAN_SCS_MASK = (int)0x1000000,
    SYSC_APP_CPU_FDCAN_SCS_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC1_CH01_SEL_FIELD {
    SYSC_APP_CPU_DMAC1_CH0_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC1_CH0_SEL_POS = 0,
    SYSC_APP_CPU_DMAC1_CH0_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC1_CH0_MOD_POS = 8,
    SYSC_APP_CPU_DMAC1_CH1_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC1_CH1_SEL_POS = 16,
    SYSC_APP_CPU_DMAC1_CH1_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC1_CH1_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC1_CH23_SEL_FIELD {
    SYSC_APP_CPU_DMAC1_CH2_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC1_CH2_SEL_POS = 0,
    SYSC_APP_CPU_DMAC1_CH2_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC1_CH2_MOD_POS = 8,
    SYSC_APP_CPU_DMAC1_CH3_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC1_CH3_SEL_POS = 16,
    SYSC_APP_CPU_DMAC1_CH3_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC1_CH3_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC1_CH45_SEL_FIELD {
    SYSC_APP_CPU_DMAC1_CH4_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC1_CH4_SEL_POS = 0,
    SYSC_APP_CPU_DMAC1_CH4_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC1_CH4_MOD_POS = 8,
    SYSC_APP_CPU_DMAC1_CH5_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC1_CH5_SEL_POS = 16,
    SYSC_APP_CPU_DMAC1_CH5_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC1_CH5_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC1_CH67_SEL_FIELD {
    SYSC_APP_CPU_DMAC1_CH6_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC1_CH6_SEL_POS = 0,
    SYSC_APP_CPU_DMAC1_CH6_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC1_CH6_MOD_POS = 8,
    SYSC_APP_CPU_DMAC1_CH7_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC1_CH7_SEL_POS = 16,
    SYSC_APP_CPU_DMAC1_CH7_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC1_CH7_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC2_CH01_SEL_FIELD {
    SYSC_APP_CPU_DMAC2_CH0_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC2_CH0_SEL_POS = 0,
    SYSC_APP_CPU_DMAC2_CH0_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC2_CH0_MOD_POS = 8,
    SYSC_APP_CPU_DMAC2_CH1_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC2_CH1_SEL_POS = 16,
    SYSC_APP_CPU_DMAC2_CH1_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC2_CH1_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC2_CH23_SEL_FIELD {
    SYSC_APP_CPU_DMAC2_CH2_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC2_CH2_SEL_POS = 0,
    SYSC_APP_CPU_DMAC2_CH2_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC2_CH2_MOD_POS = 8,
    SYSC_APP_CPU_DMAC2_CH3_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC2_CH3_SEL_POS = 16,
    SYSC_APP_CPU_DMAC2_CH3_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC2_CH3_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC2_CH45_SEL_FIELD {
    SYSC_APP_CPU_DMAC2_CH4_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC2_CH4_SEL_POS = 0,
    SYSC_APP_CPU_DMAC2_CH4_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC2_CH4_MOD_POS = 8,
    SYSC_APP_CPU_DMAC2_CH5_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC2_CH5_SEL_POS = 16,
    SYSC_APP_CPU_DMAC2_CH5_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC2_CH5_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_DMAC2_CH67_SEL_FIELD {
    SYSC_APP_CPU_DMAC2_CH6_SEL_MASK = (int)0xff,
    SYSC_APP_CPU_DMAC2_CH6_SEL_POS = 0,
    SYSC_APP_CPU_DMAC2_CH6_MOD_MASK = (int)0x300,
    SYSC_APP_CPU_DMAC2_CH6_MOD_POS = 8,
    SYSC_APP_CPU_DMAC2_CH7_SEL_MASK = (int)0xff0000,
    SYSC_APP_CPU_DMAC2_CH7_SEL_POS = 16,
    SYSC_APP_CPU_DMAC2_CH7_MOD_MASK = (int)0x3000000,
    SYSC_APP_CPU_DMAC2_CH7_MOD_POS = 24,
};

enum SYSC_APP_CPU_REG_ETH1_PHY_CTRL_FIELD {
    SYSC_APP_CPU_ETH1_PHY_INTF_SEL_MASK = (int)0x7,
    SYSC_APP_CPU_ETH1_PHY_INTF_SEL_POS = 0,
    SYSC_APP_CPU_ETH1_PHY_SEL_MASK = (int)0x8,
    SYSC_APP_CPU_ETH1_PHY_SEL_POS = 3,
    SYSC_APP_CPU_ETH1_PHY_INTR_MASK = (int)0x10,
    SYSC_APP_CPU_ETH1_PHY_INTR_POS = 4,
    SYSC_APP_CPU_ETH1_RMII_PAD_MODE_MASK = (int)0xc0,
    SYSC_APP_CPU_ETH1_RMII_PAD_MODE_POS = 6,
    SYSC_APP_CPU_ETH1_RGMII_DLY_CTL_MASK = (int)0xff00,
    SYSC_APP_CPU_ETH1_RGMII_DLY_CTL_POS = 8,
    SYSC_APP_CPU_ETH1_MDC_CHID_MASK = (int)0x3000000,
    SYSC_APP_CPU_ETH1_MDC_CHID_POS = 24,
};

enum SYSC_APP_CPU_REG_ETH2_PHY_CTRL_FIELD {
    SYSC_APP_CPU_ETH2_PHY_INTF_SEL_MASK = (int)0x7,
    SYSC_APP_CPU_ETH2_PHY_INTF_SEL_POS = 0,
    SYSC_APP_CPU_ETH2_PHY_SEL_MASK = (int)0x8,
    SYSC_APP_CPU_ETH2_PHY_SEL_POS = 3,
    SYSC_APP_CPU_ETH2_PHY_INTR_MASK = (int)0x10,
    SYSC_APP_CPU_ETH2_PHY_INTR_POS = 4,
    SYSC_APP_CPU_ETH2_RMII_PAD_MODE_MASK = (int)0xc0,
    SYSC_APP_CPU_ETH2_RMII_PAD_MODE_POS = 6,
    SYSC_APP_CPU_ETH2_RGMII_DLY_CTL_MASK = (int)0x1ff00,
    SYSC_APP_CPU_ETH2_RGMII_DLY_CTL_POS = 8,
    SYSC_APP_CPU_ETH2_MDC_CHID_MASK = (int)0x3000000,
    SYSC_APP_CPU_ETH2_MDC_CHID_POS = 24,
};

enum SYSC_APP_CPU_REG_EMMC1_DLL_CTRL_FIELD {
    SYSC_APP_CPU_EMMC1_DLL_CTRL_MASK = (int)0xffffff,
    SYSC_APP_CPU_EMMC1_DLL_CTRL_POS = 0,
    SYSC_APP_CPU_EMMC1_DLL_CTRL_RD_MASK = (int)0xff000000,
    SYSC_APP_CPU_EMMC1_DLL_CTRL_RD_POS = 24,
};

enum SYSC_APP_CPU_REG_EMMC1_CTRL_FIELD {
    SYSC_APP_CPU_EMMC1_TX_CLK_DLY_CTL_MASK = (int)0x1ff,
    SYSC_APP_CPU_EMMC1_TX_CLK_DLY_CTL_POS = 0,
    SYSC_APP_CPU_EMMC1_AUTO_TUNING_MASK = (int)0x400,
    SYSC_APP_CPU_EMMC1_AUTO_TUNING_POS = 10,
    SYSC_APP_CPU_EMMC1_TX_DLL_SEL_MASK = (int)0x800,
    SYSC_APP_CPU_EMMC1_TX_DLL_SEL_POS = 11,
    SYSC_APP_CPU_EMMC1_TX_CLK_SEL_MASK = (int)0x3000,
    SYSC_APP_CPU_EMMC1_TX_CLK_SEL_POS = 12,
    SYSC_APP_CPU_EMMC1_RX_CLK_SEL_MASK = (int)0xc000,
    SYSC_APP_CPU_EMMC1_RX_CLK_SEL_POS = 14,
    SYSC_APP_CPU_EMMC1_RX_CLK_DLY_CTL_MASK = (int)0x1ff0000,
    SYSC_APP_CPU_EMMC1_RX_CLK_DLY_CTL_POS = 16,
    SYSC_APP_CPU_EMMC1_CARD_DETECT_N_MASK = (int)0x2000000,
    SYSC_APP_CPU_EMMC1_CARD_DETECT_N_POS = 25,
    SYSC_APP_CPU_EMMC1_CARD_WRITE_PROT_MASK = (int)0x4000000,
    SYSC_APP_CPU_EMMC1_CARD_WRITE_PROT_POS = 26,
};

enum SYSC_APP_CPU_REG_EMMC2_DLL_CTRL_FIELD {
    SYSC_APP_CPU_EMMC2_DLL_CTRL_MASK = (int)0xffffff,
    SYSC_APP_CPU_EMMC2_DLL_CTRL_POS = 0,
    SYSC_APP_CPU_EMMC2_DLL_CTRL_RD_MASK = (int)0xff000000,
    SYSC_APP_CPU_EMMC2_DLL_CTRL_RD_POS = 24,
};

enum SYSC_APP_CPU_REG_EMMC2_CTRL_FIELD {
    SYSC_APP_CPU_EMMC2_TX_CLK_DLY_CTL_MASK = (int)0x1ff,
    SYSC_APP_CPU_EMMC2_TX_CLK_DLY_CTL_POS = 0,
    SYSC_APP_CPU_EMMC2_AUTO_TUNING_MASK = (int)0x400,
    SYSC_APP_CPU_EMMC2_AUTO_TUNING_POS = 10,
    SYSC_APP_CPU_EMMC2_TX_DLL_SEL_MASK = (int)0x800,
    SYSC_APP_CPU_EMMC2_TX_DLL_SEL_POS = 11,
    SYSC_APP_CPU_EMMC2_TX_CLK_SEL_MASK = (int)0x3000,
    SYSC_APP_CPU_EMMC2_TX_CLK_SEL_POS = 12,
    SYSC_APP_CPU_EMMC2_RX_CLK_SEL_MASK = (int)0xc000,
    SYSC_APP_CPU_EMMC2_RX_CLK_SEL_POS = 14,
    SYSC_APP_CPU_EMMC2_RX_CLK_DLY_CTL_MASK = (int)0x1ff0000,
    SYSC_APP_CPU_EMMC2_RX_CLK_DLY_CTL_POS = 16,
    SYSC_APP_CPU_EMMC2_CARD_DETECT_N_MASK = (int)0x2000000,
    SYSC_APP_CPU_EMMC2_CARD_DETECT_N_POS = 25,
    SYSC_APP_CPU_EMMC2_CARD_WRITE_PROT_MASK = (int)0x4000000,
    SYSC_APP_CPU_EMMC2_CARD_WRITE_PROT_POS = 26,
};

enum SYSC_APP_CPU_REG_PSRAM_CTRL_FIELD {
    SYSC_APP_CPU_PSRAM_XIP_EN_MASK = (int)0x1,
    SYSC_APP_CPU_PSRAM_XIP_EN_POS = 0,
    SYSC_APP_CPU_PSRAM_SLV_SEL_MASK = (int)0x2,
    SYSC_APP_CPU_PSRAM_SLV_SEL_POS = 1,
    SYSC_APP_CPU_PSRAM_CSN_IN_MASK = (int)0x4,
    SYSC_APP_CPU_PSRAM_CSN_IN_POS = 2,
    SYSC_APP_CPU_PSRAM_MODE_MASK = (int)0x30,
    SYSC_APP_CPU_PSRAM_MODE_POS = 4,
    SYSC_APP_CPU_PSRAM_SLEEP_MASK = (int)0x40,
    SYSC_APP_CPU_PSRAM_SLEEP_POS = 6,
};

#endif
