#ifndef REG_SYSC_CPU_TYPE_H_
#define REG_SYSC_CPU_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#define SYSC_CPU ((reg_sysc_cpu_t *)QSH_SYSC_CPU_ADDR)

typedef struct
{
    volatile uint32_t CPU_SYSC; //0x0
    volatile uint32_t SYS_CLK; //0x4
    volatile uint32_t APP_CPU_ADDR_CFG; //0x8
    volatile uint32_t APP_CPU_SRST; //0xc
    volatile uint32_t PD_CPU_CLKG[2]; //0x10
    volatile uint32_t PD_CPU_SRST[2]; //0x18
    volatile uint32_t APP_CPU_INTR; //0x20
    volatile uint32_t APP_CPU_IMSK; //0x24
    volatile uint32_t SEC_CPU_INTR; //0x28
    volatile uint32_t SEC_CPU_IMSK; //0x2c
    volatile uint32_t FDCAN_TIMESTAMP_H; //0x30
    volatile uint32_t FDCAN_TIMESTAMP_L; //0x34
    volatile uint32_t FDCAN_TIM_CTRL; //0x38
    volatile uint32_t RESERVED1[1];
    volatile uint32_t DMAC1_CH01_SEL; //0x40
    volatile uint32_t DMAC1_CH23_SEL; //0x44
    volatile uint32_t DMAC1_CH45_SEL; //0x48
    volatile uint32_t DMAC1_CH67_SEL; //0x4c
    volatile uint32_t DMAC2_CH01_SEL; //0x50
    volatile uint32_t DMAC2_CH23_SEL; //0x54
    volatile uint32_t DMAC2_CH45_SEL; //0x58
    volatile uint32_t DMAC2_CH67_SEL; //0x5c
    volatile uint32_t INTR_CTRL_MSK; //0x60
    volatile uint32_t INTR_CTRL_CLR; //0x64
    volatile uint32_t INTR_CTRL_STT; //0x68
    volatile uint32_t INTR_CTRL_RAW; //0x6c
    volatile uint32_t OTBN_STT; //0x70
    volatile uint32_t OTBN_CTRL1; //0x74
    volatile uint32_t EDN_RND_BUS; //0x78
    volatile uint32_t EDN_URND_BUS; //0x7c
    volatile uint32_t OTBN_OTP_NONCE_0; //0x80
    volatile uint32_t OTBN_OTP_NONCE_1; //0x84
    volatile uint32_t OTBN_OTP_KEY_0; //0x88
    volatile uint32_t OTBN_OTP_KEY_1; //0x8c
    volatile uint32_t OTBN_OTP_KEY_2; //0x90
    volatile uint32_t OTBN_OTP_KEY_3; //0x94
    volatile uint32_t KEYMGR_KEY0_00; //0x98
    volatile uint32_t KEYMGR_KEY0_01; //0x9c
    volatile uint32_t KEYMGR_KEY0_02; //0xa0
    volatile uint32_t KEYMGR_KEY0_03; //0xa4
    volatile uint32_t KEYMGR_KEY0_04; //0xa8
    volatile uint32_t KEYMGR_KEY0_05; //0xac
    volatile uint32_t KEYMGR_KEY0_06; //0xb0
    volatile uint32_t KEYMGR_KEY0_07; //0xb4
    volatile uint32_t KEYMGR_KEY0_08; //0xb8
    volatile uint32_t KEYMGR_KEY0_09; //0xbc
    volatile uint32_t KEYMGR_KEY0_10; //0xc0
    volatile uint32_t KEYMGR_KEY0_11; //0xc4
    volatile uint32_t KEYMGR_KEY1_00; //0xc8
    volatile uint32_t KEYMGR_KEY1_01; //0xcc
    volatile uint32_t KEYMGR_KEY1_02; //0xd0
    volatile uint32_t KEYMGR_KEY1_03; //0xd4
    volatile uint32_t KEYMGR_KEY1_04; //0xd8
    volatile uint32_t KEYMGR_KEY1_05; //0xdc
    volatile uint32_t KEYMGR_KEY1_06; //0xe0
    volatile uint32_t KEYMGR_KEY1_07; //0xe4
    volatile uint32_t KEYMGR_KEY1_08; //0xe8
    volatile uint32_t KEYMGR_KEY1_09; //0xec
    volatile uint32_t KEYMGR_KEY1_10; //0xf0
    volatile uint32_t KEYMGR_KEY1_11; //0xf4
    volatile uint32_t SPID_TX_ALERT; //0xf8
    volatile uint32_t SPID_RX_ALERT; //0xfc
}reg_sysc_cpu_t;

enum SYSC_CPU_REG_CPU_SYSC_FIELD
{
    SYSC_CPU_CACHE1_MEMTST_MASK = (int)0x10,
    SYSC_CPU_CACHE1_MEMTST_POS = 4,
    SYSC_CPU_CACHE2_MEMTST_MASK = (int)0x20,
    SYSC_CPU_CACHE2_MEMTST_POS = 5,
    SYSC_CPU_WDT_DBG_MASK = (int)0x100,
    SYSC_CPU_WDT_DBG_POS = 8,
    SYSC_CPU_WWDT_DBG_MASK = (int)0x1000,
    SYSC_CPU_WWDT_DBG_POS = 12,
};

enum SYSC_CPU_REG_SYS_CLK_FIELD
{
    SYSC_CPU_GATE_SYS_EN_MASK = (int)0x1,
    SYSC_CPU_GATE_SYS_EN_POS = 0,
    SYSC_CPU_USB1_RX_DIFF_SEL_MASK = (int)0x10,
    SYSC_CPU_USB1_RX_DIFF_SEL_POS = 4,
    SYSC_CPU_USB2_RX_DIFF_SEL_MASK = (int)0x20,
    SYSC_CPU_USB2_RX_DIFF_SEL_POS = 5,
    SYSC_CPU_RGMII_PHY_SEL_MASK = (int)0x40,
    SYSC_CPU_RGMII_PHY_SEL_POS = 6,
};

enum SYSC_CPU_REG_APP_CPU_ADDR_CFG_FIELD
{
    SYSC_CPU_APP_CPU_ADDR_CFG_MASK = (int)0xffffffff,
    SYSC_CPU_APP_CPU_ADDR_CFG_POS = 0,
};

enum SYSC_CPU_REG_APP_CPU_SRST_FIELD
{
    SYSC_CPU_APP_CPU_SRST_MASK = (int)0x1,
    SYSC_CPU_APP_CPU_SRST_POS = 0,
};

enum SYSC_CPU_REG_PD_CPU_CLKG0_FIELD
{
    SYSC_CPU_CLKG_SET_CPU_DBG_MASK = (int)0x1,
    SYSC_CPU_CLKG_SET_CPU_DBG_POS = 0,
    SYSC_CPU_CLKG_CLR_CPU_DBG_MASK = (int)0x2,
    SYSC_CPU_CLKG_CLR_CPU_DBG_POS = 1,
    SYSC_CPU_CLKG_SET_CACHE1_MASK = (int)0x4,
    SYSC_CPU_CLKG_SET_CACHE1_POS = 2,
    SYSC_CPU_CLKG_CLR_CACHE1_MASK = (int)0x8,
    SYSC_CPU_CLKG_CLR_CACHE1_POS = 3,
    SYSC_CPU_CLKG_SET_CACHE2_MASK = (int)0x10,
    SYSC_CPU_CLKG_SET_CACHE2_POS = 4,
    SYSC_CPU_CLKG_CLR_CACHE2_MASK = (int)0x20,
    SYSC_CPU_CLKG_CLR_CACHE2_POS = 5,
    SYSC_CPU_CLKG_SET_QSPI1_MASK = (int)0x40,
    SYSC_CPU_CLKG_SET_QSPI1_POS = 6,
    SYSC_CPU_CLKG_CLR_QSPI1_MASK = (int)0x80,
    SYSC_CPU_CLKG_CLR_QSPI1_POS = 7,
    SYSC_CPU_CLKG_SET_QSPI2_MASK = (int)0x100,
    SYSC_CPU_CLKG_SET_QSPI2_POS = 8,
    SYSC_CPU_CLKG_CLR_QSPI2_MASK = (int)0x200,
    SYSC_CPU_CLKG_CLR_QSPI2_POS = 9,
    SYSC_CPU_CLKG_SET_USB1_MASK = (int)0x400,
    SYSC_CPU_CLKG_SET_USB1_POS = 10,
    SYSC_CPU_CLKG_CLR_USB1_MASK = (int)0x800,
    SYSC_CPU_CLKG_CLR_USB1_POS = 11,
    SYSC_CPU_CLKG_SET_USB2_MASK = (int)0x1000,
    SYSC_CPU_CLKG_SET_USB2_POS = 12,
    SYSC_CPU_CLKG_CLR_USB2_MASK = (int)0x2000,
    SYSC_CPU_CLKG_CLR_USB2_POS = 13,
    SYSC_CPU_CLKG_SET_DMAC1_MASK = (int)0x4000,
    SYSC_CPU_CLKG_SET_DMAC1_POS = 14,
    SYSC_CPU_CLKG_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_CPU_CLKG_CLR_DMAC1_POS = 15,
    SYSC_CPU_CLKG_SET_DMAC2_MASK = (int)0x10000,
    SYSC_CPU_CLKG_SET_DMAC2_POS = 16,
    SYSC_CPU_CLKG_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_CPU_CLKG_CLR_DMAC2_POS = 17,
    SYSC_CPU_CLKG_SET_ESPI1_MASK = (int)0x40000,
    SYSC_CPU_CLKG_SET_ESPI1_POS = 18,
    SYSC_CPU_CLKG_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_CPU_CLKG_CLR_ESPI1_POS = 19,
    SYSC_CPU_CLKG_SET_ESPI2_MASK = (int)0x100000,
    SYSC_CPU_CLKG_SET_ESPI2_POS = 20,
    SYSC_CPU_CLKG_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_CPU_CLKG_CLR_ESPI2_POS = 21,
    SYSC_CPU_CLKG_SET_LPC_MASK = (int)0x400000,
    SYSC_CPU_CLKG_SET_LPC_POS = 22,
    SYSC_CPU_CLKG_CLR_LPC_MASK = (int)0x800000,
    SYSC_CPU_CLKG_CLR_LPC_POS = 23,
    SYSC_CPU_CLKG_SET_FDCAN_MASK = (int)0x1000000,
    SYSC_CPU_CLKG_SET_FDCAN_POS = 24,
    SYSC_CPU_CLKG_CLR_FDCAN_MASK = (int)0x2000000,
    SYSC_CPU_CLKG_CLR_FDCAN_POS = 25,
    SYSC_CPU_CLKG_SET_RGMII_MASK = (int)0x4000000,
    SYSC_CPU_CLKG_SET_RGMII_POS = 26,
    SYSC_CPU_CLKG_CLR_RGMII_MASK = (int)0x8000000,
    SYSC_CPU_CLKG_CLR_RGMII_POS = 27,
};

enum SYSC_CPU_REG_PD_CPU_CLKG1_FIELD
{
    SYSC_CPU_CLKG_SET_CALC_CRC_MASK = (int)0x1,
    SYSC_CPU_CLKG_SET_CALC_CRC_POS = 0,
    SYSC_CPU_CLKG_CLR_CALC_CRC_MASK = (int)0x2,
    SYSC_CPU_CLKG_CLR_CALC_CRC_POS = 1,
    SYSC_CPU_CLKG_SET_CALC_MASK = (int)0x4,
    SYSC_CPU_CLKG_SET_CALC_POS = 2,
    SYSC_CPU_CLKG_CLR_CALC_MASK = (int)0x8,
    SYSC_CPU_CLKG_CLR_CALC_POS = 3,
    SYSC_CPU_CLKG_SET_CRYPT_MASK = (int)0x10,
    SYSC_CPU_CLKG_SET_CRYPT_POS = 4,
    SYSC_CPU_CLKG_CLR_CRYPT_MASK = (int)0x20,
    SYSC_CPU_CLKG_CLR_CRYPT_POS = 5,
    SYSC_CPU_CLKG_SET_CALC_SHA_MASK = (int)0x100,
    SYSC_CPU_CLKG_SET_CALC_SHA_POS = 8,
    SYSC_CPU_CLKG_CLR_CALC_SHA_MASK = (int)0x200,
    SYSC_CPU_CLKG_CLR_CALC_SHA_POS = 9,
    SYSC_CPU_CLKG_SET_CALC_SM4_MASK = (int)0x400,
    SYSC_CPU_CLKG_SET_CALC_SM4_POS = 10,
    SYSC_CPU_CLKG_CLR_CALC_SM4_MASK = (int)0x800,
    SYSC_CPU_CLKG_CLR_CALC_SM4_POS = 11,
    SYSC_CPU_CLKG_SET_OTBN_MASK = (int)0x1000,
    SYSC_CPU_CLKG_SET_OTBN_POS = 12,
    SYSC_CPU_CLKG_CLR_OTBN_MASK = (int)0x2000,
    SYSC_CPU_CLKG_CLR_OTBN_POS = 13,
    SYSC_CPU_CLKG_SET_SPID1_MASK = (int)0x4000,
    SYSC_CPU_CLKG_SET_SPID1_POS = 14,
    SYSC_CPU_CLKG_CLR_SPID1_MASK = (int)0x8000,
    SYSC_CPU_CLKG_CLR_SPID1_POS = 15,
    SYSC_CPU_CLKG_SET_SPID2_MASK = (int)0x10000,
    SYSC_CPU_CLKG_SET_SPID2_POS = 16,
    SYSC_CPU_CLKG_CLR_SPID2_MASK = (int)0x20000,
    SYSC_CPU_CLKG_CLR_SPID2_POS = 17,
};

enum SYSC_CPU_REG_PD_CPU_SRST_FIELD
{
    SYSC_CPU_SRST_SET_CACHE1_MASK = (int)0x4,
    SYSC_CPU_SRST_SET_CACHE1_POS = 2,
    SYSC_CPU_SRST_CLR_CACHE1_MASK = (int)0x8,
    SYSC_CPU_SRST_CLR_CACHE1_POS = 3,
    SYSC_CPU_SRST_SET_CACHE2_MASK = (int)0x10,
    SYSC_CPU_SRST_SET_CACHE2_POS = 4,
    SYSC_CPU_SRST_CLR_CACHE2_MASK = (int)0x20,
    SYSC_CPU_SRST_CLR_CACHE2_POS = 5,
    SYSC_CPU_SRST_SET_QSPI1_MASK = (int)0x40,
    SYSC_CPU_SRST_SET_QSPI1_POS = 6,
    SYSC_CPU_SRST_CLR_QSPI1_MASK = (int)0x80,
    SYSC_CPU_SRST_CLR_QSPI1_POS = 7,
    SYSC_CPU_SRST_SET_QSPI2_MASK = (int)0x100,
    SYSC_CPU_SRST_SET_QSPI2_POS = 8,
    SYSC_CPU_SRST_CLR_QSPI2_MASK = (int)0x200,
    SYSC_CPU_SRST_CLR_QSPI2_POS = 9,
    SYSC_CPU_SRST_SET_USB1_MASK = (int)0x400,
    SYSC_CPU_SRST_SET_USB1_POS = 10,
    SYSC_CPU_SRST_CLR_USB1_MASK = (int)0x800,
    SYSC_CPU_SRST_CLR_USB1_POS = 11,
    SYSC_CPU_SRST_SET_USB2_MASK = (int)0x1000,
    SYSC_CPU_SRST_SET_USB2_POS = 12,
    SYSC_CPU_SRST_CLR_USB2_MASK = (int)0x2000,
    SYSC_CPU_SRST_CLR_USB2_POS = 13,
    SYSC_CPU_SRST_SET_DMAC1_MASK = (int)0x4000,
    SYSC_CPU_SRST_SET_DMAC1_POS = 14,
    SYSC_CPU_SRST_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_CPU_SRST_CLR_DMAC1_POS = 15,
    SYSC_CPU_SRST_SET_DMAC2_MASK = (int)0x10000,
    SYSC_CPU_SRST_SET_DMAC2_POS = 16,
    SYSC_CPU_SRST_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_CPU_SRST_CLR_DMAC2_POS = 17,
    SYSC_CPU_SRST_SET_ESPI1_MASK = (int)0x40000,
    SYSC_CPU_SRST_SET_ESPI1_POS = 18,
    SYSC_CPU_SRST_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_CPU_SRST_CLR_ESPI1_POS = 19,
    SYSC_CPU_SRST_SET_ESPI2_MASK = (int)0x100000,
    SYSC_CPU_SRST_SET_ESPI2_POS = 20,
    SYSC_CPU_SRST_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_CPU_SRST_CLR_ESPI2_POS = 21,
    SYSC_CPU_SRST_SET_LPC_MASK = (int)0x400000,
    SYSC_CPU_SRST_SET_LPC_POS = 22,
    SYSC_CPU_SRST_CLR_LPC_MASK = (int)0x800000,
    SYSC_CPU_SRST_CLR_LPC_POS = 23,
    SYSC_CPU_SRST_SET_FDCAN_MASK = (int)0x1000000,
    SYSC_CPU_SRST_SET_FDCAN_POS = 24,
    SYSC_CPU_SRST_CLR_FDCAN_MASK = (int)0x2000000,
    SYSC_CPU_SRST_CLR_FDCAN_POS = 25,
    SYSC_CPU_SRST_SET_RGMII_MASK = (int)0x4000000,
    SYSC_CPU_SRST_SET_RGMII_POS = 26,
    SYSC_CPU_SRST_CLR_RGMII_MASK = (int)0x8000000,
    SYSC_CPU_SRST_CLR_RGMII_POS = 27,
};

enum SYSC_CPU_REG_PD_CPU_SRST1_FIELD
{
    SYSC_CPU_SRST_SET_CALC_CRC_MASK = (int)0x1,
    SYSC_CPU_SRST_SET_CALC_CRC_POS = 0,
    SYSC_CPU_SRST_CLR_CALC_CRC_MASK = (int)0x2,
    SYSC_CPU_SRST_CLR_CALC_CRC_POS = 1,
    SYSC_CPU_SRST_SET_CALC_MASK = (int)0x4,
    SYSC_CPU_SRST_SET_CALC_POS = 2,
    SYSC_CPU_SRST_CLR_CALC_MASK = (int)0x8,
    SYSC_CPU_SRST_CLR_CALC_POS = 3,
    SYSC_CPU_SRST_SET_CRYPT_MASK = (int)0x10,
    SYSC_CPU_SRST_SET_CRYPT_POS = 4,
    SYSC_CPU_SRST_CLR_CRYPT_MASK = (int)0x20,
    SYSC_CPU_SRST_CLR_CRYPT_POS = 5,
    SYSC_CPU_SRST_SET_CALC_SHA_MASK = (int)0x100,
    SYSC_CPU_SRST_SET_CALC_SHA_POS = 8,
    SYSC_CPU_SRST_CLR_CALC_SHA_MASK = (int)0x200,
    SYSC_CPU_SRST_CLR_CALC_SHA_POS = 9,
    SYSC_CPU_SRST_SET_CALC_SM4_MASK = (int)0x400,
    SYSC_CPU_SRST_SET_CALC_SM4_POS = 10,
    SYSC_CPU_SRST_CLR_CALC_SM4_MASK = (int)0x800,
    SYSC_CPU_SRST_CLR_CALC_SM4_POS = 11,
    SYSC_CPU_SRST_SET_OTBN_MASK = (int)0x1000,
    SYSC_CPU_SRST_SET_OTBN_POS = 12,
    SYSC_CPU_SRST_CLR_OTBN_MASK = (int)0x2000,
    SYSC_CPU_SRST_CLR_OTBN_POS = 13,
    SYSC_CPU_SRST_SET_SPID1_MASK = (int)0x4000,
    SYSC_CPU_SRST_SET_SPID1_POS = 14,
    SYSC_CPU_SRST_CLR_SPID1_MASK = (int)0x8000,
    SYSC_CPU_SRST_CLR_SPID1_POS = 15,
    SYSC_CPU_SRST_SET_SPID2_MASK = (int)0x10000,
    SYSC_CPU_SRST_SET_SPID2_POS = 16,
    SYSC_CPU_SRST_CLR_SPID2_MASK = (int)0x20000,
    SYSC_CPU_SRST_CLR_SPID2_POS = 17,
};

enum SYSC_CPU_REG_APP_CPU_INTR_FIELD
{
    SYSC_CPU_APP_CPU_INTR_MASK = (int)0xffffffff,
    SYSC_CPU_APP_CPU_INTR_POS = 0,
};

enum SYSC_CPU_REG_APP_CPU_IMSK_FIELD
{
    SYSC_CPU_APP_CPU_IMSK_MASK = (int)0xffffffff,
    SYSC_CPU_APP_CPU_IMSK_POS = 0,
};

enum SYSC_CPU_REG_SEC_CPU_INTR_FIELD
{
    SYSC_CPU_SEC_CPU_INTR_MASK = (int)0xffffffff,
    SYSC_CPU_SEC_CPU_INTR_POS = 0,
};

enum SYSC_CPU_REG_SEC_CPU_IMSK_FIELD
{
    SYSC_CPU_SEC_CPU_IMSK_MASK = (int)0xffffffff,
    SYSC_CPU_SEC_CPU_IMSK_POS = 0,
};

enum SYSC_CPU_REG_FDCAN_TIMESTAMP_H_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_H_MASK = (int)0xffffffff,
    SYSC_CPU_FDCAN_TIMESTAMP_H_POS = 0,
};

enum SYSC_CPU_REG_FDCAN_TIMESTAMP_L_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_L_MASK = (int)0xffffffff,
    SYSC_CPU_FDCAN_TIMESTAMP_L_POS = 0,
};

enum SYSC_CPU_REG_FDCAN_TIM_CTRL_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_ENABLE_MASK = (int)0x1,
    SYSC_CPU_FDCAN_TIMESTAMP_ENABLE_POS = 0,
    SYSC_CPU_FDCAN_TIMESTAMP_CLEAR_MASK = (int)0x2,
    SYSC_CPU_FDCAN_TIMESTAMP_CLEAR_POS = 1,
    SYSC_CPU_FDCAN_TIMESTAMP_PRECALER_MASK = (int)0xff00,
    SYSC_CPU_FDCAN_TIMESTAMP_PRECALER_POS = 8,
    SYSC_CPU_FDCAN_TIMESTAMP_STEP_MASK = (int)0xff0000,
    SYSC_CPU_FDCAN_TIMESTAMP_STEP_POS = 16,
    SYSC_CPU_FDCAN_SCS_MASK = (int)0x1000000,
    SYSC_CPU_FDCAN_SCS_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH01_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH0_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH0_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH0_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH0_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH1_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH1_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH1_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH1_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH23_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH2_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH2_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH2_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH2_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH3_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH3_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH3_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH3_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH45_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH4_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH4_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH4_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH4_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH5_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH5_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH5_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH5_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH67_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH6_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH6_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH6_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH6_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH7_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH7_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH7_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH7_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH01_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH0_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH0_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH0_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH0_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH1_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH1_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH1_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH1_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH23_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH2_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH2_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH2_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH2_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH3_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH3_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH3_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH3_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH45_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH4_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH4_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH4_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH4_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH5_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH5_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH5_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH5_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH67_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH6_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH6_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH6_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH6_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH7_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH7_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH7_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH7_MOD_POS = 24,
};

enum SYSC_CPU_REG_INTR_CTRL_MSK_FIELD
{
    SYSC_CPU_INTR_CTRL_MSK_MASK = (int)0x7ff,
    SYSC_CPU_INTR_CTRL_MSK_POS = 0,
};

enum SYSC_CPU_REG_INTR_CTRL_CLR_FIELD
{
    SYSC_CPU_INTR_CTRL_CLR_MASK = (int)0x7ff,
    SYSC_CPU_INTR_CTRL_CLR_POS = 0,
};

enum SYSC_CPU_REG_INTR_CTRL_STT_FIELD
{
    SYSC_CPU_INTR_CTRL_STT_MASK = (int)0x7ff,
    SYSC_CPU_INTR_CTRL_STT_POS = 0,
};

enum SYSC_CPU_REG_INTR_CTRL_RAW_FIELD
{
    SYSC_CPU_INTR_CTRL_RAW_MASK = (int)0x7ff,
    SYSC_CPU_INTR_CTRL_RAW_POS = 0,
};

enum SYSC_CPU_REG_OTBN_STT_FIELD
{
    SYSC_CPU_I_ALERT_TX0_ALERT_P_MASK = (int)0x1,
    SYSC_CPU_I_ALERT_TX0_ALERT_P_POS = 0,
    SYSC_CPU_I_ALERT_TX0_ALERT_N_MASK = (int)0x2,
    SYSC_CPU_I_ALERT_TX0_ALERT_N_POS = 1,
    SYSC_CPU_I_ALERT_TX1_ALERT_P_MASK = (int)0x4,
    SYSC_CPU_I_ALERT_TX1_ALERT_P_POS = 2,
    SYSC_CPU_I_ALERT_TX1_ALERT_N_MASK = (int)0x8,
    SYSC_CPU_I_ALERT_TX1_ALERT_N_POS = 3,
    SYSC_CPU_I_LC_RMA_ACK_MASK = (int)0xf0,
    SYSC_CPU_I_LC_RMA_ACK_POS = 4,
    SYSC_CPU_I_EDN_RND_REQ_MASK = (int)0x100,
    SYSC_CPU_I_EDN_RND_REQ_POS = 8,
    SYSC_CPU_I_EDN_URND_REQ_MASK = (int)0x200,
    SYSC_CPU_I_EDN_URND_REQ_POS = 9,
    SYSC_CPU_I_OTBN_OTP_REQ_MASK = (int)0x400,
    SYSC_CPU_I_OTBN_OTP_REQ_POS = 10,
    SYSC_CPU_I_OTBN_IDLE_MASK = (int)0x7800,
    SYSC_CPU_I_OTBN_IDLE_POS = 11,
};

enum SYSC_CPU_REG_OTBN_CTRL1_FIELD
{
    SYSC_CPU_OTBN_ALERT_RX0_PING_P_MASK = (int)0x1,
    SYSC_CPU_OTBN_ALERT_RX0_PING_P_POS = 0,
    SYSC_CPU_OTBN_ALERT_RX0_PING_N_MASK = (int)0x2,
    SYSC_CPU_OTBN_ALERT_RX0_PING_N_POS = 1,
    SYSC_CPU_OTBN_ALERT_RX0_ACK_P_MASK = (int)0x4,
    SYSC_CPU_OTBN_ALERT_RX0_ACK_P_POS = 2,
    SYSC_CPU_OTBN_ALERT_RX0_ACK_N_MASK = (int)0x8,
    SYSC_CPU_OTBN_ALERT_RX0_ACK_N_POS = 3,
    SYSC_CPU_OTBN_ALERT_RX1_PING_P_MASK = (int)0x10,
    SYSC_CPU_OTBN_ALERT_RX1_PING_P_POS = 4,
    SYSC_CPU_OTBN_ALERT_RX1_PING_N_MASK = (int)0x20,
    SYSC_CPU_OTBN_ALERT_RX1_PING_N_POS = 5,
    SYSC_CPU_OTBN_ALERT_RX1_ACK_P_MASK = (int)0x40,
    SYSC_CPU_OTBN_ALERT_RX1_ACK_P_POS = 6,
    SYSC_CPU_OTBN_ALERT_RX1_ACK_N_MASK = (int)0x80,
    SYSC_CPU_OTBN_ALERT_RX1_ACK_N_POS = 7,
    SYSC_CPU_EDN_RND_ACK_MASK = (int)0x100,
    SYSC_CPU_EDN_RND_ACK_POS = 8,
    SYSC_CPU_EDN_RND_FIPS_MASK = (int)0x200,
    SYSC_CPU_EDN_RND_FIPS_POS = 9,
    SYSC_CPU_EDN_URND_ACK_MASK = (int)0x400,
    SYSC_CPU_EDN_URND_ACK_POS = 10,
    SYSC_CPU_EDN_URND_FIPS_MASK = (int)0x800,
    SYSC_CPU_EDN_URND_FIPS_POS = 11,
    SYSC_CPU_OTBN_TOP_ACK_MASK = (int)0x1000,
    SYSC_CPU_OTBN_TOP_ACK_POS = 12,
    SYSC_CPU_OTBN_TOP_SEED_VAILD_MASK = (int)0x2000,
    SYSC_CPU_OTBN_TOP_SEED_VAILD_POS = 13,
    SYSC_CPU_KEYMGR_VALID_MASK = (int)0x4000,
    SYSC_CPU_KEYMGR_VALID_POS = 14,
    SYSC_CPU_LC_ESCALATE_EN_MASK = (int)0xf0000,
    SYSC_CPU_LC_ESCALATE_EN_POS = 16,
    SYSC_CPU_LC_RMA_REQ_MASK = (int)0xf00000,
    SYSC_CPU_LC_RMA_REQ_POS = 20,
};

enum SYSC_CPU_REG_EDN_RND_BUS_FIELD
{
    SYSC_CPU_EDN_RND_BUS_MASK = (int)0xffffffff,
    SYSC_CPU_EDN_RND_BUS_POS = 0,
};

enum SYSC_CPU_REG_EDN_URND_BUS_FIELD
{
    SYSC_CPU_EDN_URND_BUS_MASK = (int)0xffffffff,
    SYSC_CPU_EDN_URND_BUS_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_NONCE_0_FIELD
{
    SYSC_CPU_OTBN_OTP_NONCE_0_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_NONCE_0_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_NONCE_1_FIELD
{
    SYSC_CPU_OTBN_OTP_NONCE_1_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_NONCE_1_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_KEY_0_FIELD
{
    SYSC_CPU_OTBN_OTP_KEY_0_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_KEY_0_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_KEY_1_FIELD
{
    SYSC_CPU_OTBN_OTP_KEY_1_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_KEY_1_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_KEY_2_FIELD
{
    SYSC_CPU_OTBN_OTP_KEY_2_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_KEY_2_POS = 0,
};

enum SYSC_CPU_REG_OTBN_OTP_KEY_3_FIELD
{
    SYSC_CPU_OTBN_OTP_KEY_3_MASK = (int)0xffffffff,
    SYSC_CPU_OTBN_OTP_KEY_3_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_00_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_00_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_00_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_01_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_01_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_01_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_02_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_02_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_02_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_03_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_03_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_03_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_04_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_04_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_04_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_05_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_05_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_05_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_06_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_06_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_06_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_07_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_07_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_07_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_08_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_08_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_08_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_09_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_09_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_09_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_10_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_10_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_10_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY0_11_FIELD
{
    SYSC_CPU_KEYMGR_KEY0_11_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY0_11_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_00_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_00_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_00_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_01_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_01_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_01_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_02_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_02_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_02_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_03_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_03_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_03_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_04_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_04_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_04_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_05_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_05_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_05_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_06_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_06_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_06_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_07_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_07_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_07_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_08_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_08_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_08_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_09_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_09_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_09_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_10_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_10_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_10_POS = 0,
};

enum SYSC_CPU_REG_KEYMGR_KEY1_11_FIELD
{
    SYSC_CPU_KEYMGR_KEY1_11_MASK = (int)0xffffffff,
    SYSC_CPU_KEYMGR_KEY1_11_POS = 0,
};

enum SYSC_CPU_REG_SPID_TX_ALERT_FIELD
{
    SYSC_CPU_SPID1_ALERT_TX0_ALERT_P_MASK = (int)0x1,
    SYSC_CPU_SPID1_ALERT_TX0_ALERT_P_POS = 0,
    SYSC_CPU_SPID1_ALERT_TX0_ALERT_N_MASK = (int)0x2,
    SYSC_CPU_SPID1_ALERT_TX0_ALERT_N_POS = 1,
    SYSC_CPU_SPID1_ALERT_TX1_ALERT_P_MASK = (int)0x4,
    SYSC_CPU_SPID1_ALERT_TX1_ALERT_P_POS = 2,
    SYSC_CPU_SPID1_ALERT_TX1_ALERT_N_MASK = (int)0x8,
    SYSC_CPU_SPID1_ALERT_TX1_ALERT_N_POS = 3,
    SYSC_CPU_SPID2_ALERT_TX0_ALERT_P_MASK = (int)0x10,
    SYSC_CPU_SPID2_ALERT_TX0_ALERT_P_POS = 4,
    SYSC_CPU_SPID2_ALERT_TX0_ALERT_N_MASK = (int)0x20,
    SYSC_CPU_SPID2_ALERT_TX0_ALERT_N_POS = 5,
    SYSC_CPU_SPID2_ALERT_TX1_ALERT_P_MASK = (int)0x40,
    SYSC_CPU_SPID2_ALERT_TX1_ALERT_P_POS = 6,
    SYSC_CPU_SPID2_ALERT_TX1_ALERT_N_MASK = (int)0x80,
    SYSC_CPU_SPID2_ALERT_TX1_ALERT_N_POS = 7,
};

enum SYSC_CPU_REG_SPID_RX_ALERT_FIELD
{
    SYSC_CPU_SPID1_ALERT_RX0_PING_P_MASK = (int)0x1,
    SYSC_CPU_SPID1_ALERT_RX0_PING_P_POS = 0,
    SYSC_CPU_SPID1_ALERT_RX0_PING_N_MASK = (int)0x2,
    SYSC_CPU_SPID1_ALERT_RX0_PING_N_POS = 1,
    SYSC_CPU_SPID1_ALERT_RX0_ACK_P_MASK = (int)0x4,
    SYSC_CPU_SPID1_ALERT_RX0_ACK_P_POS = 2,
    SYSC_CPU_SPID1_ALERT_RX0_ACK_N_MASK = (int)0x8,
    SYSC_CPU_SPID1_ALERT_RX0_ACK_N_POS = 3,
    SYSC_CPU_SPID1_ALERT_RX1_PING_P_MASK = (int)0x10,
    SYSC_CPU_SPID1_ALERT_RX1_PING_P_POS = 4,
    SYSC_CPU_SPID1_ALERT_RX1_PING_N_MASK = (int)0x20,
    SYSC_CPU_SPID1_ALERT_RX1_PING_N_POS = 5,
    SYSC_CPU_SPID1_ALERT_RX1_ACK_P_MASK = (int)0x40,
    SYSC_CPU_SPID1_ALERT_RX1_ACK_P_POS = 6,
    SYSC_CPU_SPID1_ALERT_RX1_ACK_N_MASK = (int)0x80,
    SYSC_CPU_SPID1_ALERT_RX1_ACK_N_POS = 7,
    SYSC_CPU_SPID2_ALERT_RX0_PING_P_MASK = (int)0x100,
    SYSC_CPU_SPID2_ALERT_RX0_PING_P_POS = 8,
    SYSC_CPU_SPID2_ALERT_RX0_PING_N_MASK = (int)0x200,
    SYSC_CPU_SPID2_ALERT_RX0_PING_N_POS = 9,
    SYSC_CPU_SPID2_ALERT_RX0_ACK_P_MASK = (int)0x400,
    SYSC_CPU_SPID2_ALERT_RX0_ACK_P_POS = 10,
    SYSC_CPU_SPID2_ALERT_RX0_ACK_N_MASK = (int)0x800,
    SYSC_CPU_SPID2_ALERT_RX0_ACK_N_POS = 11,
    SYSC_CPU_SPID2_ALERT_RX1_PING_P_MASK = (int)0x1000,
    SYSC_CPU_SPID2_ALERT_RX1_PING_P_POS = 12,
    SYSC_CPU_SPID2_ALERT_RX1_PING_N_MASK = (int)0x2000,
    SYSC_CPU_SPID2_ALERT_RX1_PING_N_POS = 13,
    SYSC_CPU_SPID2_ALERT_RX1_ACK_P_MASK = (int)0x4000,
    SYSC_CPU_SPID2_ALERT_RX1_ACK_P_POS = 14,
    SYSC_CPU_SPID2_ALERT_RX1_ACK_N_MASK = (int)0x8000,
    SYSC_CPU_SPID2_ALERT_RX1_ACK_N_POS = 15,
    SYSC_CPU_SPID1_MODE_MASK = (int)0x70000,
    SYSC_CPU_SPID1_MODE_POS = 16,
    SYSC_CPU_SPID2_MODE_MASK = (int)0x700000,
    SYSC_CPU_SPID2_MODE_POS = 20,
};

static inline void cpu_intr0_unmask(void)
{
    SYSC_CPU->APP_CPU_IMSK = 1;
}

static inline void cpu_intr0_mask(void)
{
    SYSC_CPU->APP_CPU_IMSK = 0;
}

static inline void cpu_intr0_activate(void)
{
    SYSC_CPU->APP_CPU_INTR = 1;
}

static inline void cpu_intr0_clr(void)
{
    SYSC_CPU->APP_CPU_INTR = 0;
}

static inline void cpu_intr1_unmask(void)
{
    SYSC_CPU->SEC_CPU_IMSK = 1;
}

static inline void cpu_intr1_mask(void)
{
    SYSC_CPU->SEC_CPU_IMSK = 0;
}

static inline void cpu_intr1_activate(void)
{
    SYSC_CPU->SEC_CPU_INTR = 1;
}

static inline void cpu_intr1_clr(void)
{
    SYSC_CPU->SEC_CPU_INTR = 0;
}

static inline void app_cpu_reset(void)
{
    SYSC_CPU->APP_CPU_SRST = 0;
}

static inline void app_cpu_dereset(void)
{
    SYSC_CPU->APP_CPU_SRST = 1;
}

static inline void app_cpu_reset_pc(uint32_t addr)
{
    SYSC_CPU->APP_CPU_ADDR_CFG = addr;
}

#endif

