#ifndef REG_SYSC_CPU_TYPE_H_
#define REG_SYSC_CPU_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#define SYSC_CPU ((reg_sysc_cpu_t *)QSH_SYSC_CPU_ADDR)

typedef struct
{
    volatile uint32_t CPU_SYSC; //0x0
    volatile uint32_t GATE_SYS; //0x4
    volatile uint32_t APP_CPU_ADDR_CFG; //0x8
    volatile uint32_t APP_CPU_SRST; //0xc
    volatile uint32_t PD_CPU_CLKG[2]; //0x10
    volatile uint32_t PD_CPU_SRST[2]; //0x18
    volatile uint32_t RESERVED0[4];
    volatile uint32_t FDCAN_TIMESTAMP_H; //0x30
    volatile uint32_t FDCAN_TIMESTAMP_L; //0x34
    volatile uint32_t FDCAN_TIM_CTRL; //0x38
    volatile uint32_t RESERVED1[1];
    volatile uint32_t DMAC1_CH01_SEL; //0x40
    volatile uint32_t DMAC1_CH23_SEL; //0x44
    volatile uint32_t DMAC1_CH45_SEL; //0x48
    volatile uint32_t DMAC1_CH67_SEL; //0x4c
    volatile uint32_t DMAC2_CH01_SEL; //0x50
    volatile uint32_t DMAC2_CH23_SEL; //0x54
    volatile uint32_t DMAC2_CH45_SEL; //0x58
    volatile uint32_t DMAC2_CH67_SEL; //0x5c
}reg_sysc_cpu_t;

enum SYSC_CPU_REG_CPU_SYSC_FIELD
{
    SYSC_CPU_CACHE1_MEMTST_MASK = (int)0x10,
    SYSC_CPU_CACHE1_MEMTST_POS = 4,
    SYSC_CPU_CACHE2_MEMTST_MASK = (int)0x20,
    SYSC_CPU_CACHE2_MEMTST_POS = 5,
    SYSC_CPU_WDT_DBG_MASK = (int)0x100,
    SYSC_CPU_WDT_DBG_POS = 8,
    SYSC_CPU_WWDT_DBG_MASK = (int)0x1000,
    SYSC_CPU_WWDT_DBG_POS = 12,
};

enum SYSC_CPU_REG_GATE_SYS_FIELD
{
    SYSC_CPU_GATE_SYS_EN_MASK = (int)0x1,
    SYSC_CPU_GATE_SYS_EN_POS = 0,
    SYSC_CPU_USB1_RX_DIFF_SEL_MASK = (int)0x10,
    SYSC_CPU_USB1_RX_DIFF_SEL_POS = 4,
    SYSC_CPU_USB2_RX_DIFF_SEL_MASK = (int)0x20,
    SYSC_CPU_USB2_RX_DIFF_SEL_POS = 5,
};

enum SYSC_CPU_REG_APP_CPU_ADDR_CFG_FIELD
{
    SYSC_CPU_APP_CPU_ADDR_CFG_MASK = (int)0xffffffff,
    SYSC_CPU_APP_CPU_ADDR_CFG_POS = 0,
};

enum SYSC_CPU_REG_APP_CPU_SRST_FIELD
{
    SYSC_CPU_APP_CPU_SRST_MASK = (int)0x1,
    SYSC_CPU_APP_CPU_SRST_POS = 0,
};

enum SYSC_CPU_REG_PD_CPU_CLKG0_FIELD
{
    SYSC_CPU_CLKG_SET_CPU_DBG_MASK = (int)0x1,
    SYSC_CPU_CLKG_SET_CPU_DBG_POS = 0,
    SYSC_CPU_CLKG_CLR_CPU_DBG_MASK = (int)0x2,
    SYSC_CPU_CLKG_CLR_CPU_DBG_POS = 1,
    SYSC_CPU_CLKG_SET_CACHE1_MASK = (int)0x4,
    SYSC_CPU_CLKG_SET_CACHE1_POS = 2,
    SYSC_CPU_CLKG_CLR_CACHE1_MASK = (int)0x8,
    SYSC_CPU_CLKG_CLR_CACHE1_POS = 3,
    SYSC_CPU_CLKG_SET_CACHE2_MASK = (int)0x10,
    SYSC_CPU_CLKG_SET_CACHE2_POS = 4,
    SYSC_CPU_CLKG_CLR_CACHE2_MASK = (int)0x20,
    SYSC_CPU_CLKG_CLR_CACHE2_POS = 5,
    SYSC_CPU_CLKG_SET_QSPI1_MASK = (int)0x40,
    SYSC_CPU_CLKG_SET_QSPI1_POS = 6,
    SYSC_CPU_CLKG_CLR_QSPI1_MASK = (int)0x80,
    SYSC_CPU_CLKG_CLR_QSPI1_POS = 7,
    SYSC_CPU_CLKG_SET_QSPI2_MASK = (int)0x100,
    SYSC_CPU_CLKG_SET_QSPI2_POS = 8,
    SYSC_CPU_CLKG_CLR_QSPI3_MASK = (int)0x200,
    SYSC_CPU_CLKG_CLR_QSPI3_POS = 9,
    SYSC_CPU_CLKG_SET_USB1_MASK = (int)0x400,
    SYSC_CPU_CLKG_SET_USB1_POS = 10,
    SYSC_CPU_CLKG_CLR_USB1_MASK = (int)0x800,
    SYSC_CPU_CLKG_CLR_USB1_POS = 11,
    SYSC_CPU_CLKG_SET_USB2_MASK = (int)0x1000,
    SYSC_CPU_CLKG_SET_USB2_POS = 12,
    SYSC_CPU_CLKG_CLR_USB2_MASK = (int)0x2000,
    SYSC_CPU_CLKG_CLR_USB2_POS = 13,
    SYSC_CPU_CLKG_SET_DMAC1_MASK = (int)0x4000,
    SYSC_CPU_CLKG_SET_DMAC1_POS = 14,
    SYSC_CPU_CLKG_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_CPU_CLKG_CLR_DMAC1_POS = 15,
    SYSC_CPU_CLKG_SET_DMAC2_MASK = (int)0x10000,
    SYSC_CPU_CLKG_SET_DMAC2_POS = 16,
    SYSC_CPU_CLKG_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_CPU_CLKG_CLR_DMAC2_POS = 17,
    SYSC_CPU_CLKG_SET_ESPI1_MASK = (int)0x40000,
    SYSC_CPU_CLKG_SET_ESPI1_POS = 18,
    SYSC_CPU_CLKG_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_CPU_CLKG_CLR_ESPI1_POS = 19,
    SYSC_CPU_CLKG_SET_ESPI2_MASK = (int)0x100000,
    SYSC_CPU_CLKG_SET_ESPI2_POS = 20,
    SYSC_CPU_CLKG_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_CPU_CLKG_CLR_ESPI2_POS = 21,
    SYSC_CPU_CLKG_SET_LPC_MASK = (int)0x400000,
    SYSC_CPU_CLKG_SET_LPC_POS = 22,
    SYSC_CPU_CLKG_CLR_LPC_MASK = (int)0x800000,
    SYSC_CPU_CLKG_CLR_LPC_POS = 23,
    SYSC_CPU_CLKG_SET_FDCAN_MASK = (int)0x1000000,
    SYSC_CPU_CLKG_SET_FDCAN_POS = 24,
    SYSC_CPU_CLKG_CLR_FDCAN_MASK = (int)0x2000000,
    SYSC_CPU_CLKG_CLR_FDCAN_POS = 25,
};

enum SYSC_CPU_REG_PD_CPU_CLKG1_FIELD
{
    SYSC_CPU_CLKG_SET_CALC_CRC_MASK = (int)0x1,
    SYSC_CPU_CLKG_SET_CALC_CRC_POS = 0,
    SYSC_CPU_CLKG_CLR_CALC_CRC_MASK = (int)0x2,
    SYSC_CPU_CLKG_CLR_CALC_CRC_POS = 1,
    SYSC_CPU_CLKG_SET_CALC_MASK = (int)0x4,
    SYSC_CPU_CLKG_SET_CALC_POS = 2,
    SYSC_CPU_CLKG_CLR_CALC_MASK = (int)0x8,
    SYSC_CPU_CLKG_CLR_CALC_POS = 3,
    SYSC_CPU_CLKG_SET_CRYPT_MASK = (int)0x10,
    SYSC_CPU_CLKG_SET_CRYPT_POS = 4,
    SYSC_CPU_CLKG_CLR_CRYPT_MASK = (int)0x20,
    SYSC_CPU_CLKG_CLR_CRYPT_POS = 5,
    SYSC_CPU_CLKG_SET_ECC_MASK = (int)0x40,
    SYSC_CPU_CLKG_SET_ECC_POS = 6,
    SYSC_CPU_CLKG_CLR_ECC_MASK = (int)0x80,
    SYSC_CPU_CLKG_CLR_ECC_POS = 7,
    SYSC_CPU_CLKG_SET_CALC_SHA_MASK = (int)0x100,
    SYSC_CPU_CLKG_SET_CALC_SHA_POS = 8,
    SYSC_CPU_CLKG_CLR_CALC_SHA_MASK = (int)0x200,
    SYSC_CPU_CLKG_CLR_CALC_SHA_POS = 9,
    SYSC_CPU_CLKG_SET_CALC_SM4_MASK = (int)0x400,
    SYSC_CPU_CLKG_SET_CALC_SM4_POS = 10,
    SYSC_CPU_CLKG_CLR_CALC_SM4_MASK = (int)0x800,
    SYSC_CPU_CLKG_CLR_CALC_SM4_POS = 11,
    SYSC_CPU_CLKG_SET_CALC_OTBN_MASK = (int)0x1000,
    SYSC_CPU_CLKG_SET_CALC_OTBN_POS = 12,
    SYSC_CPU_CLKG_CLR_CALC_OTBN_MASK = (int)0x2000,
    SYSC_CPU_CLKG_CLR_CALC_OTBN_POS = 13,
};

enum SYSC_CPU_REG_PD_CPU_SRST_FIELD
{
    SYSC_CPU_SRST_SET_CPU_DBG_MASK = (int)0x1,
    SYSC_CPU_SRST_SET_CPU_DBG_POS = 0,
    SYSC_CPU_SRST_CLR_CPU_DBG_MASK = (int)0x2,
    SYSC_CPU_SRST_CLR_CPU_DBG_POS = 1,
    SYSC_CPU_SRST_SET_CACHE1_MASK = (int)0x4,
    SYSC_CPU_SRST_SET_CACHE1_POS = 2,
    SYSC_CPU_SRST_CLR_CACHE1_MASK = (int)0x8,
    SYSC_CPU_SRST_CLR_CACHE1_POS = 3,
    SYSC_CPU_SRST_SET_CACHE2_MASK = (int)0x10,
    SYSC_CPU_SRST_SET_CACHE2_POS = 4,
    SYSC_CPU_SRST_CLR_CACHE2_MASK = (int)0x20,
    SYSC_CPU_SRST_CLR_CACHE2_POS = 5,
    SYSC_CPU_SRST_SET_QSPI1_MASK = (int)0x40,
    SYSC_CPU_SRST_SET_QSPI1_POS = 6,
    SYSC_CPU_SRST_CLR_QSPI1_MASK = (int)0x80,
    SYSC_CPU_SRST_CLR_QSPI1_POS = 7,
    SYSC_CPU_SRST_SET_QSPI2_MASK = (int)0x100,
    SYSC_CPU_SRST_SET_QSPI2_POS = 8,
    SYSC_CPU_SRST_CLR_QSPI3_MASK = (int)0x200,
    SYSC_CPU_SRST_CLR_QSPI3_POS = 9,
    SYSC_CPU_SRST_SET_USB1_MASK = (int)0x400,
    SYSC_CPU_SRST_SET_USB1_POS = 10,
    SYSC_CPU_SRST_CLR_USB1_MASK = (int)0x800,
    SYSC_CPU_SRST_CLR_USB1_POS = 11,
    SYSC_CPU_SRST_SET_USB2_MASK = (int)0x1000,
    SYSC_CPU_SRST_SET_USB2_POS = 12,
    SYSC_CPU_SRST_CLR_USB2_MASK = (int)0x2000,
    SYSC_CPU_SRST_CLR_USB2_POS = 13,
    SYSC_CPU_SRST_SET_DMAC1_MASK = (int)0x4000,
    SYSC_CPU_SRST_SET_DMAC1_POS = 14,
    SYSC_CPU_SRST_CLR_DMAC1_MASK = (int)0x8000,
    SYSC_CPU_SRST_CLR_DMAC1_POS = 15,
    SYSC_CPU_SRST_SET_DMAC2_MASK = (int)0x10000,
    SYSC_CPU_SRST_SET_DMAC2_POS = 16,
    SYSC_CPU_SRST_CLR_DMAC2_MASK = (int)0x20000,
    SYSC_CPU_SRST_CLR_DMAC2_POS = 17,
    SYSC_CPU_SRST_SET_ESPI1_MASK = (int)0x40000,
    SYSC_CPU_SRST_SET_ESPI1_POS = 18,
    SYSC_CPU_SRST_CLR_ESPI1_MASK = (int)0x80000,
    SYSC_CPU_SRST_CLR_ESPI1_POS = 19,
    SYSC_CPU_SRST_SET_ESPI2_MASK = (int)0x100000,
    SYSC_CPU_SRST_SET_ESPI2_POS = 20,
    SYSC_CPU_SRST_CLR_ESPI2_MASK = (int)0x200000,
    SYSC_CPU_SRST_CLR_ESPI2_POS = 21,
    SYSC_CPU_SRST_SET_LPC_MASK = (int)0x400000,
    SYSC_CPU_SRST_SET_LPC_POS = 22,
    SYSC_CPU_SRST_CLR_LPC_MASK = (int)0x800000,
    SYSC_CPU_SRST_CLR_LPC_POS = 23,
    SYSC_CPU_SRST_SET_FDCAN_MASK = (int)0x1000000,
    SYSC_CPU_SRST_SET_FDCAN_POS = 24,
    SYSC_CPU_SRST_CLR_FDCAN_MASK = (int)0x2000000,
    SYSC_CPU_SRST_CLR_FDCAN_POS = 25,
};

enum SYSC_CPU_REG_PD_CPU_SRST1_FIELD
{
    SYSC_CPU_SRST_SET_CALC_CRC_MASK = (int)0x1,
    SYSC_CPU_SRST_SET_CALC_CRC_POS = 0,
    SYSC_CPU_SRST_CLR_CALC_CRC_MASK = (int)0x2,
    SYSC_CPU_SRST_CLR_CALC_CRC_POS = 1,
    SYSC_CPU_SRST_SET_CALC_MASK = (int)0x4,
    SYSC_CPU_SRST_SET_CALC_POS = 2,
    SYSC_CPU_SRST_CLR_CALC_MASK = (int)0x8,
    SYSC_CPU_SRST_CLR_CALC_POS = 3,
    SYSC_CPU_SRST_SET_CRYPT_MASK = (int)0x10,
    SYSC_CPU_SRST_SET_CRYPT_POS = 4,
    SYSC_CPU_SRST_CLR_CRYPT_MASK = (int)0x20,
    SYSC_CPU_SRST_CLR_CRYPT_POS = 5,
    SYSC_CPU_SRST_SET_ECC_MASK = (int)0x40,
    SYSC_CPU_SRST_SET_ECC_POS = 6,
    SYSC_CPU_SRST_CLR_ECC_MASK = (int)0x80,
    SYSC_CPU_SRST_CLR_ECC_POS = 7,
    SYSC_CPU_SRST_SET_CALC_SHA_MASK = (int)0x100,
    SYSC_CPU_SRST_SET_CALC_SHA_POS = 8,
    SYSC_CPU_SRST_CLR_CALC_SHA_MASK = (int)0x200,
    SYSC_CPU_SRST_CLR_CALC_SHA_POS = 9,
    SYSC_CPU_SRST_SET_CALC_SM4_MASK = (int)0x400,
    SYSC_CPU_SRST_SET_CALC_SM4_POS = 10,
    SYSC_CPU_SRST_CLR_CALC_SM4_MASK = (int)0x800,
    SYSC_CPU_SRST_CLR_CALC_SM4_POS = 11,
    SYSC_CPU_SRST_SET_CALC_OTBN_MASK = (int)0x1000,
    SYSC_CPU_SRST_SET_CALC_OTBN_POS = 12,
    SYSC_CPU_SRST_CLR_CALC_OTBN_MASK = (int)0x2000,
    SYSC_CPU_SRST_CLR_CALC_OTBN_POS = 13,
};

enum SYSC_CPU_REG_FDCAN_TIMESTAMP_H_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_H_MASK = (int)0xffffffff,
    SYSC_CPU_FDCAN_TIMESTAMP_H_POS = 0,
};

enum SYSC_CPU_REG_FDCAN_TIMESTAMP_L_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_L_MASK = (int)0xffffffff,
    SYSC_CPU_FDCAN_TIMESTAMP_L_POS = 0,
};

enum SYSC_CPU_REG_FDCAN_TIM_CTRL_FIELD
{
    SYSC_CPU_FDCAN_TIMESTAMP_ENABLE_MASK = (int)0x1,
    SYSC_CPU_FDCAN_TIMESTAMP_ENABLE_POS = 0,
    SYSC_CPU_FDCAN_TIMESTAMP_CLEAR_MASK = (int)0x2,
    SYSC_CPU_FDCAN_TIMESTAMP_CLEAR_POS = 1,
    SYSC_CPU_FDCAN_TIMESTAMP_PRECALER_MASK = (int)0xff00,
    SYSC_CPU_FDCAN_TIMESTAMP_PRECALER_POS = 8,
    SYSC_CPU_FDCAN_TIMESTAMP_STEP_MASK = (int)0xff0000,
    SYSC_CPU_FDCAN_TIMESTAMP_STEP_POS = 16,
    SYSC_CPU_FDCAN_SCS_MASK = (int)0x1000000,
    SYSC_CPU_FDCAN_SCS_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH01_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH0_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH0_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH0_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH0_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH1_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH1_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH1_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH1_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH23_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH2_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH2_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH2_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH2_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH3_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH3_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH3_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH3_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH45_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH4_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH4_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH4_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH4_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH5_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH5_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH5_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH5_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC1_CH67_SEL_FIELD
{
    SYSC_CPU_DMAC1_CH6_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC1_CH6_SEL_POS = 0,
    SYSC_CPU_DMAC1_CH6_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC1_CH6_MOD_POS = 8,
    SYSC_CPU_DMAC1_CH7_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC1_CH7_SEL_POS = 16,
    SYSC_CPU_DMAC1_CH7_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC1_CH7_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH01_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH0_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH0_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH0_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH0_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH1_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH1_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH1_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH1_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH23_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH2_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH2_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH2_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH2_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH3_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH3_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH3_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH3_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH45_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH4_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH4_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH4_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH4_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH5_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH5_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH5_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH5_MOD_POS = 24,
};

enum SYSC_CPU_REG_DMAC2_CH67_SEL_FIELD
{
    SYSC_CPU_DMAC2_CH6_SEL_MASK = (int)0xff,
    SYSC_CPU_DMAC2_CH6_SEL_POS = 0,
    SYSC_CPU_DMAC2_CH6_MOD_MASK = (int)0x300,
    SYSC_CPU_DMAC2_CH6_MOD_POS = 8,
    SYSC_CPU_DMAC2_CH7_SEL_MASK = (int)0xff0000,
    SYSC_CPU_DMAC2_CH7_SEL_POS = 16,
    SYSC_CPU_DMAC2_CH7_MOD_MASK = (int)0x3000000,
    SYSC_CPU_DMAC2_CH7_MOD_POS = 24,
};

#endif

