import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env['OPT_LVL'] = ' -Os '
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
     'main.c',
     'tmall_light_cfg.c',
     'tmall_mesh_ctl.c',
     '../genie_ota/tmall_genie_ota.c',
     '../genie_ota/tmall_genie_ais.c',
     '../genie_ota/genie_crc16.c',
     '../genie_ota/genie_crypto.c',
     '../genie_ota/genie_triple.c',
     '../genie_ota/ali_dfu_port.c',
     '../../../../module/tinycrypt/lib/source/aes_encrypt.c',
     '../../../../module/tinycrypt/lib/source/aes_decrypt.c'
]
inc = [
    '.',
    '../genie_ota/.'
]
env.app_build('tmall_mesh_gatt_glp',src,inc,mesh = True)
