import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env['OPT_LVL'] = ' -Os '
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
     'main.c',
     'tmall_light_cfg.c',
     'tmall_mesh_ctl.c'
]
inc = [
    '.'
]
env.app_build('tmall_mesh_gatt_glp',src,inc,mesh = True)
