#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define SDK_USER_TINYFS_NODE_MAX 50
#define SDK_DEEP_SLEEP_ENABLE 0

#define SDK_HCLK_MHZ (16)

#define AMIC_SAMPLE_PCM		0x01
#define AMIC_SAMPLE_ADPCM	0x02
#define AMIC_STREAM_FORMAT	(AMIC_SAMPLE_PCM)

#define AMIC_SAMPLE_RATE_8K	0x01
#define AMIC_SAMPLE_RATE_16K	0x02
#define AMIC_SAMPLE_RATE		AMIC_SAMPLE_RATE_16K

#define AMIC_SAMPLE_ALGORITHM_NONE	0x01	// the adc value not left shift
#define AMIC_SAMPLE_ALGORITHM_LSH 	0x02	// the adc value left shift to turn up the volume
#define AMIC_SAMPLE_ALGORITHM_MODE 	AMIC_SAMPLE_ALGORITHM_LSH

#define UART_TRANSMIT_POLLING	0x01
#define UART_TRANSMIT_IT		0x02
#define UART_TRANSMIT_DMA		0x04
#define UART_TRANSMIT_MODE		UART_TRANSMIT_DMA

#define BUILD_SW_VER_H 0x00
#define BUILD_SW_VER_M 0x01
#define BUILD_SW_VER_L 0x02

#endif
