import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    '../../../../module/adpcm/adpcm.c',
]
inc = [
    '.',
    '../../../../module/adpcm',
]
env.app_build('single_dac_adpcm_audio',src,inc,ble = False)