import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/main.c',
    '../../Source/at_cmd_parse.c',
    '../../Source/at_recv_cmd.c',
]
inc = [
    '../../Include/.',
    '../../.',
]
env.app_build('ble_at_proj',src,inc)
