import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    '../bsp.c',
    '$SDK_ROOT/module/tinyusb/examples/device/hid_composite/src/main.c',
    '$SDK_ROOT/module/tinyusb/examples/device/hid_composite/src/usb_descriptors.c',
]
inc = [
    '.',
    '$SDK_ROOT/module/tinyusb/examples/device/hid_composite/src/',
]
env.app_build('usbd_hid_composite',src,inc, ble = False,usb = True)
