import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env['IC'] = 'leo'
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    'by25qxx.c',
    'exflash_ssi.c'
]
inc = [
    '.'
]
env.app_build('ssi_exflash',src,inc,ble = False)
