import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
     'main.c',
     'ls_mesh_light_cfg.c'
]
inc = [
    '.'
]
env.app_build('ls_mesh',src,inc)
