import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
]
inc = [
    '.'
]
env['LINKSCRIPT'] = File(env.subst('$IC/ram_link.txt'))
env.image_build('ram_test',src,inc)
