#ifndef REG_ANA_TOP_CRG_TYPE_H_
#define REG_ANA_TOP_CRG_TYPE_H_
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ANA_TOP ((reg_ana_top_crg_t *)REG_TOP_SYS_CFG2_ANA_TOP_CRG_BASE)

typedef struct
{
    volatile uint32_t PMU_CTRL0; //0x0
    volatile uint32_t PMU_CTRL1; //0x4
    volatile uint32_t BISR_RD; //0x8
} reg_ana_top_crg_t;

enum ANA_TOP_CRG_REG_PMU_CTRL0_FIELD
{
    ANA_TOP_CRG_BG_ENB_MASK = (int)0x1,
    ANA_TOP_CRG_BG_ENB_POS = 0,
    ANA_TOP_CRG_VREF_BUF_EN_MASK = (int)0x2,
    ANA_TOP_CRG_VREF_BUF_EN_POS = 1,
    ANA_TOP_CRG_BOR18_EN_MASK = (int)0x4,
    ANA_TOP_CRG_BOR18_EN_POS = 2,
    ANA_TOP_CRG_VREF_OK_09V_MASK = (int)0x8,
    ANA_TOP_CRG_VREF_OK_09V_POS = 3,
    ANA_TOP_CRG_BG_TESTEN_MASK = (int)0x10,
    ANA_TOP_CRG_BG_TESTEN_POS = 4,
    ANA_TOP_CRG_BAT_DET_EN_MASK = (int)0x20,
    ANA_TOP_CRG_BAT_DET_EN_POS = 5,
    ANA_TOP_CRG_LVD_H_EN_MASK = (int)0x40,
    ANA_TOP_CRG_LVD_H_EN_POS = 6,
    ANA_TOP_CRG_BG_IBIAS_ENB_MASK = (int)0x80,
    ANA_TOP_CRG_BG_IBIAS_ENB_POS = 7,
    ANA_TOP_CRG_LVD_L_EN_MASK = (int)0x100,
    ANA_TOP_CRG_LVD_L_EN_POS = 8,
    ANA_TOP_CRG_BOR09_EN_MASK = (int)0x200,
    ANA_TOP_CRG_BOR09_EN_POS = 9,
    ANA_TOP_CRG_BOR09_SEL_MASK = (int)0xc00,
    ANA_TOP_CRG_BOR09_SEL_POS = 10,
    ANA_TOP_CRG_BAT_DET_ADJ_MASK = (int)0x3000,
    ANA_TOP_CRG_BAT_DET_ADJ_POS = 12,
    ANA_TOP_CRG_LVD_L_SEL_MASK = (int)0xc000,
    ANA_TOP_CRG_LVD_L_SEL_POS = 14,
    ANA_TOP_CRG_BG_VREF_FINE_MASK = (int)0x30000,
    ANA_TOP_CRG_BG_VREF_FINE_POS = 16,
    ANA_TOP_CRG_BOR18_SEL_MASK = (int)0xc0000,
    ANA_TOP_CRG_BOR18_SEL_POS = 18,
    ANA_TOP_CRG_BG_IBG_TRIM_MASK = (int)0xf00000,
    ANA_TOP_CRG_BG_IBG_TRIM_POS = 20,
    ANA_TOP_CRG_LVD_H_SEL_MASK = (int)0xf000000,
    ANA_TOP_CRG_LVD_H_SEL_POS = 24,
};

enum ANA_TOP_CRG_REG_PMU_CTRL1_FIELD
{
    ANA_TOP_CRG_BG_VREF_TRIM_MASK = (int)0x3f,
    ANA_TOP_CRG_BG_VREF_TRIM_POS = 0,
    ANA_TOP_CRG_LVD_L_09V_INTR_EN_MASK = (int)0x40,
    ANA_TOP_CRG_LVD_L_09V_INTR_EN_POS = 6,
    ANA_TOP_CRG_LVD_L_09V_INTR_POL_MASK = (int)0x80,
    ANA_TOP_CRG_LVD_L_09V_INTR_POL_POS = 7,
    ANA_TOP_CRG_LVD_L_09V_INTR_CLR_MASK = (int)0x100,
    ANA_TOP_CRG_LVD_L_09V_INTR_CLR_POS = 8,
    ANA_TOP_CRG_LVD_L_09V_MASK = (int)0x200,
    ANA_TOP_CRG_LVD_L_09V_POS = 9,
    ANA_TOP_CRG_LVD_L_09V_INTR_RAW_MASK = (int)0x400,
    ANA_TOP_CRG_LVD_L_09V_INTR_RAW_POS = 10,
    ANA_TOP_CRG_LVD_H_09V_INTR_EN_MASK = (int)0x800,
    ANA_TOP_CRG_LVD_H_09V_INTR_EN_POS = 11,
    ANA_TOP_CRG_LVD_H_09V_INTR_POL_MASK = (int)0x1000,
    ANA_TOP_CRG_LVD_H_09V_INTR_POL_POS = 12,
    ANA_TOP_CRG_LVD_H_09V_INTR_CLR_MASK = (int)0x2000,
    ANA_TOP_CRG_LVD_H_09V_INTR_CLR_POS = 13,
    ANA_TOP_CRG_LVD_H_09V_MASK = (int)0x4000,
    ANA_TOP_CRG_LVD_H_09V_POS = 14,
    ANA_TOP_CRG_LVD_H_09V_INTR_RAW_MASK = (int)0x8000,
    ANA_TOP_CRG_LVD_H_09V_INTR_RAW_POS = 15,
};

enum ANA_TOP_CRG_REG_BISR_RD_FIELD
{
    ANA_TOP_CRG_BISR_GO_MASK = (int)0x1,
    ANA_TOP_CRG_BISR_GO_POS = 0,
    ANA_TOP_CRG_BISR_DONE_MASK = (int)0x2,
    ANA_TOP_CRG_BISR_DONE_POS = 1,
};

#ifdef __cplusplus
}
#endif

#endif

