#ifndef REG_TOP_DIG_TYPE_H_
#define REG_TOP_DIG_TYPE_H_
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TOP_DIG_CFG            ((reg_top_dig_t *)   (REG_TOP_DIG_APB_CFG_BASE))

typedef struct
{
    volatile uint32_t WDT5_LRC_CLK_CLK_DEGLITCH_SW2_REG; //0x0
    volatile uint32_t WDT5_LRC_CLK_CLK_CG0_REG; //0x4
    volatile uint32_t TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0; //0x8
    volatile uint32_t TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_CLR; //0xc
    volatile uint32_t TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0; //0x10
    volatile uint32_t TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_CLR; //0x14
    volatile uint32_t TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0; //0x18
    volatile uint32_t TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_CLR; //0x1c
    volatile uint32_t TOP_SYS_CFG_REG1; //0x20
    volatile uint32_t TOP_SYS_CFG_REG2; //0x24
    volatile uint32_t TOP_SYS_CFG_REG3; //0x28
    volatile uint32_t TOP_SYS_CFG_LOCK; //0x2c
    volatile uint32_t ANA_SYS_ADJUST_ADB400_EN; //0x30
    volatile uint32_t ANA_ADB400_MST_ADJUST_AXI_EN; //0x34
    volatile uint32_t APLL_CTL0; //0x38
    volatile uint32_t APLL_CTL1; //0x3c
    volatile uint32_t BPLL_CTL0; //0x40
    volatile uint32_t BPLL_CTL1; //0x44
    volatile uint32_t CPLL_CTL0; //0x48
    volatile uint32_t CPLL_CTL1; //0x4c
    volatile uint32_t DPLL_CTL0; //0x50
    volatile uint32_t DPLL_CTL1; //0x54
    volatile uint32_t VPLL_CTL0; //0x58
    volatile uint32_t VPLL_CTL1; //0x5c
} reg_top_dig_t;

enum TOP_DIG_REG_WDT5_LRC_CLK_CLK_DEGLITCH_SW2_REG_FIELD
{
    TOP_DIG_WDT5_LRC_CLK_CLK_DEGLITCH_SW2_REG_MASK = (int)0x1f,
    TOP_DIG_WDT5_LRC_CLK_CLK_DEGLITCH_SW2_REG_POS = 0,
};

enum TOP_DIG_REG_WDT5_LRC_CLK_CLK_CG0_REG_FIELD
{
    TOP_DIG_WDT5_LRC_CLK_CLK_CG0_REG_MASK = (int)0x1,
    TOP_DIG_WDT5_LRC_CLK_CLK_CG0_REG_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_CLR_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_CLR_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS0_APB_CLK_TOP_RST_N_REG0_CLR_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_CLR_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_CLR_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS_AXI_CLK_TOP_RST_N_REG0_CLR_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_POS = 0,
};

enum TOP_DIG_REG_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_CLR_FIELD
{
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_CLR_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_DIG_CRG_TOP_SYS1_APB_CLK_TOP_RST_N_REG0_CLR_POS = 0,
};

enum TOP_DIG_REG_TOP_SYS_CFG_REG1_FIELD
{
    TOP_DIG_TOP_TOP_SYS_CFG_REG1_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_SYS_CFG_REG1_POS = 0,
};

enum TOP_DIG_REG_TOP_SYS_CFG_REG2_FIELD
{
    TOP_DIG_TOP_TOP_SYS_CFG_REG2_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_SYS_CFG_REG2_POS = 0,
};

enum TOP_DIG_REG_TOP_SYS_CFG_REG3_FIELD
{
    TOP_DIG_TOP_TOP_SYS_CFG_REG3_MASK = (int)0xffffffff,
    TOP_DIG_TOP_TOP_SYS_CFG_REG3_POS = 0,
};

enum TOP_DIG_REG_TOP_SYS_CFG_LOCK_FIELD
{
    TOP_DIG_TOP_SYS_CFG_LOCK_MASK = (int)0x1,
    TOP_DIG_TOP_SYS_CFG_LOCK_POS = 0,
};

enum TOP_DIG_REG_ANA_SYS_ADJUST_ADB400_EN_FIELD
{
    TOP_DIG_ADJUST_ADB400_CPU_ANA_EN_MASK = (int)0x1,
    TOP_DIG_ADJUST_ADB400_CPU_ANA_EN_POS = 0,
    TOP_DIG_ADJUST_ADB400_PIPE_ANA_EN_MASK = (int)0x2,
    TOP_DIG_ADJUST_ADB400_PIPE_ANA_EN_POS = 1,
};

enum TOP_DIG_REG_ANA_ADB400_MST_ADJUST_AXI_EN_FIELD
{
    TOP_DIG_ANA_ADB400_MST_ADJUST_AXI_EN_MASK = (int)0x1,
    TOP_DIG_ANA_ADB400_MST_ADJUST_AXI_EN_POS = 0,
};

enum TOP_DIG_REG_APLL_CTL0_FIELD
{
    TOP_DIG_APLL_BYPASS_CLKDIVPD_MASK = (int)0x1,
    TOP_DIG_APLL_BYPASS_CLKDIVPD_POS = 0,
    TOP_DIG_APLL_CLKDIV1_MASK = (int)0xe,
    TOP_DIG_APLL_CLKDIV1_POS = 1,
    TOP_DIG_APLL_CLKDIV2_MASK = (int)0x70,
    TOP_DIG_APLL_CLKDIV2_POS = 4,
    TOP_DIG_APLL_CLKDIVPD_MASK = (int)0x80,
    TOP_DIG_APLL_CLKDIVPD_POS = 7,
    TOP_DIG_APLL_CLKPHASEPD_MASK = (int)0x100,
    TOP_DIG_APLL_CLKPHASEPD_POS = 8,
    TOP_DIG_APLL_PD_MASK = (int)0x200,
    TOP_DIG_APLL_PD_POS = 9,
    TOP_DIG_APLL_REFDIV_MASK = (int)0xfc00,
    TOP_DIG_APLL_REFDIV_POS = 10,
    TOP_DIG_APLL_V2I_PD_MASK = (int)0x10000,
    TOP_DIG_APLL_V2I_PD_POS = 16,
    TOP_DIG_APLL_FRPD_MASK = (int)0x20000,
    TOP_DIG_APLL_FRPD_POS = 17,
    TOP_DIG_APLL_VCO_OUT_PD_MASK = (int)0x40000,
    TOP_DIG_APLL_VCO_OUT_PD_POS = 18,
    TOP_DIG_APLL_FBDIV_INT_MASK = (int)0x7ff80000,
    TOP_DIG_APLL_FBDIV_INT_POS = 19,
    TOP_DIG_APLL_LOCK_MASK = (int)0x80000000,
    TOP_DIG_APLL_LOCK_POS = 31,
};

enum TOP_DIG_REG_APLL_CTL1_FIELD
{
    TOP_DIG_APLL_FBDIV_FRA_MASK = (int)0xffffff,
    TOP_DIG_APLL_FBDIV_FRA_POS = 0,
};

enum TOP_DIG_REG_BPLL_CTL0_FIELD
{
    TOP_DIG_BPLL_BYPASS_CLKDIVPD_MASK = (int)0x1,
    TOP_DIG_BPLL_BYPASS_CLKDIVPD_POS = 0,
    TOP_DIG_BPLL_CLKDIV1_MASK = (int)0xe,
    TOP_DIG_BPLL_CLKDIV1_POS = 1,
    TOP_DIG_BPLL_CLKDIV2_MASK = (int)0x70,
    TOP_DIG_BPLL_CLKDIV2_POS = 4,
    TOP_DIG_BPLL_CLKDIVPD_MASK = (int)0x80,
    TOP_DIG_BPLL_CLKDIVPD_POS = 7,
    TOP_DIG_BPLL_CLKPHASEPD_MASK = (int)0x100,
    TOP_DIG_BPLL_CLKPHASEPD_POS = 8,
    TOP_DIG_BPLL_PD_MASK = (int)0x200,
    TOP_DIG_BPLL_PD_POS = 9,
    TOP_DIG_BPLL_REFDIV_MASK = (int)0xfc00,
    TOP_DIG_BPLL_REFDIV_POS = 10,
    TOP_DIG_BPLL_V2I_PD_MASK = (int)0x10000,
    TOP_DIG_BPLL_V2I_PD_POS = 16,
    TOP_DIG_BPLL_FRPD_MASK = (int)0x20000,
    TOP_DIG_BPLL_FRPD_POS = 17,
    TOP_DIG_BPLL_VCO_OUT_PD_MASK = (int)0x40000,
    TOP_DIG_BPLL_VCO_OUT_PD_POS = 18,
    TOP_DIG_BPLL_FBDIV_INT_MASK = (int)0x7ff80000,
    TOP_DIG_BPLL_FBDIV_INT_POS = 19,
    TOP_DIG_BPLL_LOCK_MASK = (int)0x80000000,
    TOP_DIG_BPLL_LOCK_POS = 31,
};

enum TOP_DIG_REG_BPLL_CTL1_FIELD
{
    TOP_DIG_BPLL_FBDIV_FRA_MASK = (int)0xffffff,
    TOP_DIG_BPLL_FBDIV_FRA_POS = 0,
};

enum TOP_DIG_REG_CPLL_CTL0_FIELD
{
    TOP_DIG_CPLL_BYPASS_CLKDIVPD_MASK = (int)0x1,
    TOP_DIG_CPLL_BYPASS_CLKDIVPD_POS = 0,
    TOP_DIG_CPLL_CLKDIV1_MASK = (int)0xe,
    TOP_DIG_CPLL_CLKDIV1_POS = 1,
    TOP_DIG_CPLL_CLKDIV2_MASK = (int)0x70,
    TOP_DIG_CPLL_CLKDIV2_POS = 4,
    TOP_DIG_CPLL_CLKDIVPD_MASK = (int)0x80,
    TOP_DIG_CPLL_CLKDIVPD_POS = 7,
    TOP_DIG_CPLL_CLKPHASEPD_MASK = (int)0x100,
    TOP_DIG_CPLL_CLKPHASEPD_POS = 8,
    TOP_DIG_CPLL_PD_MASK = (int)0x200,
    TOP_DIG_CPLL_PD_POS = 9,
    TOP_DIG_CPLL_REFDIV_MASK = (int)0xfc00,
    TOP_DIG_CPLL_REFDIV_POS = 10,
    TOP_DIG_CPLL_V2I_PD_MASK = (int)0x10000,
    TOP_DIG_CPLL_V2I_PD_POS = 16,
    TOP_DIG_CPLL_FRPD_MASK = (int)0x20000,
    TOP_DIG_CPLL_FRPD_POS = 17,
    TOP_DIG_CPLL_VCO_OUT_PD_MASK = (int)0x40000,
    TOP_DIG_CPLL_VCO_OUT_PD_POS = 18,
    TOP_DIG_CPLL_FBDIV_INT_MASK = (int)0x7ff80000,
    TOP_DIG_CPLL_FBDIV_INT_POS = 19,
    TOP_DIG_CPLL_LOCK_MASK = (int)0x80000000,
    TOP_DIG_CPLL_LOCK_POS = 31,
};

enum TOP_DIG_REG_CPLL_CTL1_FIELD
{
    TOP_DIG_CPLL_FBDIV_FRA_MASK = (int)0xffffff,
    TOP_DIG_CPLL_FBDIV_FRA_POS = 0,
};

enum TOP_DIG_REG_DPLL_CTL0_FIELD
{
    TOP_DIG_DPLL_BYPASS_CLKDIVPD_MASK = (int)0x1,
    TOP_DIG_DPLL_BYPASS_CLKDIVPD_POS = 0,
    TOP_DIG_DPLL_CLKDIV1_MASK = (int)0xe,
    TOP_DIG_DPLL_CLKDIV1_POS = 1,
    TOP_DIG_DPLL_CLKDIV2_MASK = (int)0x70,
    TOP_DIG_DPLL_CLKDIV2_POS = 4,
    TOP_DIG_DPLL_CLKDIVPD_MASK = (int)0x80,
    TOP_DIG_DPLL_CLKDIVPD_POS = 7,
    TOP_DIG_DPLL_CLKPHASEPD_MASK = (int)0x100,
    TOP_DIG_DPLL_CLKPHASEPD_POS = 8,
    TOP_DIG_DPLL_PD_MASK = (int)0x200,
    TOP_DIG_DPLL_PD_POS = 9,
    TOP_DIG_DPLL_REFDIV_MASK = (int)0xfc00,
    TOP_DIG_DPLL_REFDIV_POS = 10,
    TOP_DIG_DPLL_V2I_PD_MASK = (int)0x10000,
    TOP_DIG_DPLL_V2I_PD_POS = 16,
    TOP_DIG_DPLL_FRPD_MASK = (int)0x20000,
    TOP_DIG_DPLL_FRPD_POS = 17,
    TOP_DIG_DPLL_VCO_OUT_PD_MASK = (int)0x40000,
    TOP_DIG_DPLL_VCO_OUT_PD_POS = 18,
    TOP_DIG_DPLL_FBDIV_INT_MASK = (int)0x7ff80000,
    TOP_DIG_DPLL_FBDIV_INT_POS = 19,
    TOP_DIG_DPLL_LOCK_MASK = (int)0x80000000,
    TOP_DIG_DPLL_LOCK_POS = 31,
};

enum TOP_DIG_REG_DPLL_CTL1_FIELD
{
    TOP_DIG_DPLL_FBDIV_FRA_MASK = (int)0xffffff,
    TOP_DIG_DPLL_FBDIV_FRA_POS = 0,
};

enum TOP_DIG_REG_VPLL_CTL0_FIELD
{
    TOP_DIG_VPLL_BYPASS_CLKDIVPD_MASK = (int)0x1,
    TOP_DIG_VPLL_BYPASS_CLKDIVPD_POS = 0,
    TOP_DIG_VPLL_CLKDIV1_MASK = (int)0xe,
    TOP_DIG_VPLL_CLKDIV1_POS = 1,
    TOP_DIG_VPLL_CLKDIV2_MASK = (int)0x70,
    TOP_DIG_VPLL_CLKDIV2_POS = 4,
    TOP_DIG_VPLL_CLKDIVPD_MASK = (int)0x80,
    TOP_DIG_VPLL_CLKDIVPD_POS = 7,
    TOP_DIG_VPLL_CLKPHASEPD_MASK = (int)0x100,
    TOP_DIG_VPLL_CLKPHASEPD_POS = 8,
    TOP_DIG_VPLL_PD_MASK = (int)0x200,
    TOP_DIG_VPLL_PD_POS = 9,
    TOP_DIG_VPLL_REFDIV_MASK = (int)0xfc00,
    TOP_DIG_VPLL_REFDIV_POS = 10,
    TOP_DIG_VPLL_V2I_PD_MASK = (int)0x10000,
    TOP_DIG_VPLL_V2I_PD_POS = 16,
    TOP_DIG_VPLL_FRPD_MASK = (int)0x20000,
    TOP_DIG_VPLL_FRPD_POS = 17,
    TOP_DIG_VPLL_VCO_OUT_PD_MASK = (int)0x40000,
    TOP_DIG_VPLL_VCO_OUT_PD_POS = 18,
    TOP_DIG_VPLL_FBDIV_INT_MASK = (int)0x7ff80000,
    TOP_DIG_VPLL_FBDIV_INT_POS = 19,
    TOP_DIG_VPLL_LOCK_MASK = (int)0x80000000,
    TOP_DIG_VPLL_LOCK_POS = 31,
};

enum TOP_DIG_REG_VPLL_CTL1_FIELD
{
    TOP_DIG_VPLL_FBDIV_FRA_MASK = (int)0xffffff,
    TOP_DIG_VPLL_FBDIV_FRA_POS = 0,
    TOP_DIG_REF_CLK_SEL_MASK = (int)0xf000000,
    TOP_DIG_REF_CLK_SEL_POS = 24,
};

#ifdef __cplusplus
}
#endif

#endif

