#ifndef REG_SYSC_AWO_TYPE_H_
#define REG_SYSC_AWO_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SYSC_AWO_CFG           ((reg_sysc_awo_t *)   (REG_TOP_SYS_CFG3_PIN_MUX_BASE))

typedef struct
{
    volatile uint32_t FUNC0_ABCD_EN; //0x0
    volatile uint32_t FUNC0_EFGH_EN; //0x4
    volatile uint32_t FUNC0_IJKL_EN; //0x8
    volatile uint32_t FUNC0_MNOP_EN; //0xc
    volatile uint32_t FUNC0_QRST_EN; //0x10
    volatile uint32_t FUNC0_UVWX_EN; //0x14
    volatile uint32_t FUNC0_YZEEFF_EN; //0x18
    volatile uint32_t FUNC0_AABBCCDD_EN; //0x1c
    volatile uint32_t IO_FUNC1_EN[8]; //0x20
    volatile uint32_t FUNC1_JTAGMS_EN; //0x40
    volatile uint32_t IO_FUNC2_EN[8]; //0x44
    volatile uint32_t FUNC2_JTAGMS_EN; //0x64
    volatile uint32_t IO_FUNC3_EN[8]; //0x68
    volatile uint32_t IO_FUNC4_EN[8]; //0x88
    volatile uint32_t IO_FUNC5_EN[8]; //0xa8
    volatile uint32_t IO_VAL[8]; //0xc8
    volatile uint32_t GPJTAGMS_O; //0xe8
    volatile uint32_t OE[8]; //0xec
    volatile uint32_t GPJTAGMS_OE; //0x10c
    volatile uint32_t IO_INPUT[8]; //0x110
    volatile uint32_t GPJTAGMS_I; //0x130
    volatile uint32_t IE[8]; //0x134
    volatile uint32_t GPJTAGMS_IE; //0x154
    volatile uint32_t IO_REN[8]; //0x158
    volatile uint32_t GPJTAGMS_REN; //0x178
    volatile uint32_t IO_ODE[8]; //0x17c
    volatile uint32_t GPJTAGMS_ODE; //0x19c
    volatile uint32_t GPA_H_PU[2]; //0x1A0
    volatile uint32_t GPIL_PU; //0x1a8
    volatile uint32_t GPJK_PU[2]; //0x1ac - 0x1b0
    volatile uint32_t GPM_DD_PU[5]; //0x1b4
    volatile uint32_t GPJTAGMS_PU; //0x1c8
    volatile uint32_t IO_PULL_DOWN[8]; //0x1cc
    volatile uint32_t GPJTAGMS_PD; //0x1ec
    volatile uint32_t IO_DS0[8]; //0x1f0
    volatile uint32_t GPJTAGMS_DS0; //0x210
    volatile uint32_t IO_DS1[8]; //0x214
    volatile uint32_t GPJTAGMS_DS1; //0x234
    volatile uint32_t IO_DS2[8]; //0x238
    volatile uint32_t GPJTAGMS_DS2; //0x258
    volatile uint32_t IO_DS3[8]; //0x25c
    volatile uint32_t GPJTAGMS_DS3; //0x27c
    volatile uint32_t IO_SCHMITT_TRIG[8]; //0x280
    volatile uint32_t GPJTAGMS_ST; //0x2a0
    volatile uint32_t IO_SLEW_RATE_CTRL[8]; //0x2a4
    volatile uint32_t GPJTAGMS_SL; //0x2c4
    volatile uint32_t MULTIPLEX_SEL; //0x2c8
    volatile uint32_t SIG_SEL; //0x2cc
    volatile uint32_t GPIO_INTR_SEL; //0x2d0
    volatile uint32_t GPAB_INTR0_MSK; //0x2d4
    volatile uint32_t GPCD_INTR0_MSK; //0x2d8
    volatile uint32_t GPEF_INTR0_MSK; //0x2dc
    volatile uint32_t GPGH_INTR0_MSK; //0x2e0
    volatile uint32_t GPIJ_INTR0_MSK; //0x2e4
    volatile uint32_t GPKL_INTR0_MSK; //0x2e8
    volatile uint32_t GPMN_INTR0_MSK; //0x2ec
    volatile uint32_t GPOP_INTR0_MSK; //0x2f0
    volatile uint32_t GPQR_INTR0_MSK; //0x2f4
    volatile uint32_t GPST_INTR0_MSK; //0x2f8
    volatile uint32_t GPUV_INTR0_MSK; //0x2fc
    volatile uint32_t GPWX_INTR0_MSK; //0x300
    volatile uint32_t GPYZ_INTR0_MSK; //0x304
    volatile uint32_t GPEEFF_INTR0_MSK; //0x308
    volatile uint32_t GPAABB_INTR0_MSK; //0x30c
    volatile uint32_t GPCCDD_INTR0_MSK; //0x310
    volatile uint32_t GPJTAGMS_INTR0_MSK; //0x314
    volatile uint32_t GPAIO_INTR0_MSK; //0x318
    volatile uint32_t GPAB_INTR0_CLR; //0x31c
    volatile uint32_t GPCD_INTR0_CLR; //0x320
    volatile uint32_t GPEF_INTR0_CLR; //0x324
    volatile uint32_t GPGH_INTR0_CLR; //0x328
    volatile uint32_t GPIJ_INTR0_CLR; //0x32c
    volatile uint32_t GPKL_INTR0_CLR; //0x330
    volatile uint32_t GPMN_INTR0_CLR; //0x334
    volatile uint32_t GPOP_INTR0_CLR; //0x338
    volatile uint32_t GPQR_INTR0_CLR; //0x33c
    volatile uint32_t GPST_INTR0_CLR; //0x340
    volatile uint32_t GPUV_INTR0_CLR; //0x344
    volatile uint32_t GPWX_INTR0_CLR; //0x348
    volatile uint32_t GPYZ_INTR0_CLR; //0x34c
    volatile uint32_t GPEEFF_INTR0_CLR; //0x350
    volatile uint32_t GPAABB_INTR0_CLR; //0x354
    volatile uint32_t GPCCDD_INTR0_CLR; //0x358
    volatile uint32_t GPJTAGMS_INTR0_CLR; //0x35c
    volatile uint32_t GPAIO_INTR0_CLR; //0x360
    volatile uint32_t GPAB_INTR0_RAW; //0x364
    volatile uint32_t GPCD_INTR0_RAW; //0x368
    volatile uint32_t GPEF_INTR0_RAW; //0x36c
    volatile uint32_t GPGH_INTR0_RAW; //0x370
    volatile uint32_t GPIJ_INTR0_RAW; //0x374
    volatile uint32_t GPKL_INTR0_RAW; //0x378
    volatile uint32_t GPMN_INTR0_RAW; //0x37c
    volatile uint32_t GPOP_INTR0_RAW; //0x380
    volatile uint32_t GPQR_INTR0_RAW; //0x384
    volatile uint32_t GPST_INTR0_RAW; //0x388
    volatile uint32_t GPUV_INTR0_RAW; //0x38c
    volatile uint32_t GPWX_INTR0_RAW; //0x390
    volatile uint32_t GPYZ_INTR0_RAW; //0x394
    volatile uint32_t GPEEFF_INTR0_RAW; //0x398
    volatile uint32_t GPAABB_INTR0_RAW; //0x39c
    volatile uint32_t GPCCDD_INTR0_RAW; //0x3a0
    volatile uint32_t GPJTAGMS_INTR0_RAW; //0x3a4
    volatile uint32_t GPAIO_INTR0_RAW; //0x3a8
    volatile uint32_t GPAB_INTR0_STT; //0x3ac
    volatile uint32_t GPCD_INTR0_STT; //0x3b0
    volatile uint32_t GPEF_INTR0_STT; //0x3b4
    volatile uint32_t GPGH_INTR0_STT; //0x3b8
    volatile uint32_t GPIJ_INTR0_STT; //0x3bc
    volatile uint32_t GPKL_INTR0_STT; //0x3c0
    volatile uint32_t GPMN_INTR0_STT; //0x3c4
    volatile uint32_t GPOP_INTR0_STT; //0x3c8
    volatile uint32_t GPQR_INTR0_STT; //0x3cc
    volatile uint32_t GPST_INTR0_STT; //0x3d0
    volatile uint32_t GPUV_INTR0_STT; //0x3d4
    volatile uint32_t GPWX_INTR0_STT; //0x3d8
    volatile uint32_t GPYZ_INTR0_STT; //0x3dc
    volatile uint32_t GPEEFF_INTR0_STT; //0x3e0
    volatile uint32_t GPAABB_INTR0_STT; //0x3e4
    volatile uint32_t GPCCDD_INTR0_STT; //0x3e8
    volatile uint32_t GPJTAGMS_INTR0_STT; //0x3ec
    volatile uint32_t GPAIO_INTR0_STT; //0x3f0
    volatile uint32_t GPAB_INTR1_MSK; //0x3f4
    volatile uint32_t GPCD_INTR1_MSK; //0x3f8
    volatile uint32_t GPEF_INTR1_MSK; //0x3fc
    volatile uint32_t GPGH_INTR1_MSK; //0x400
    volatile uint32_t GPIJ_INTR1_MSK; //0x404
    volatile uint32_t GPKL_INTR1_MSK; //0x408
    volatile uint32_t GPMN_INTR1_MSK; //0x40c
    volatile uint32_t GPOP_INTR1_MSK; //0x410
    volatile uint32_t GPQR_INTR1_MSK; //0x414
    volatile uint32_t GPST_INTR1_MSK; //0x418
    volatile uint32_t GPUV_INTR1_MSK; //0x41c
    volatile uint32_t GPWX_INTR1_MSK; //0x420
    volatile uint32_t GPYZ_INTR1_MSK; //0x424
    volatile uint32_t GPEEFF_INTR1_MSK; //0x428
    volatile uint32_t GPAABB_INTR1_MSK; //0x42c
    volatile uint32_t GPCCDD_INTR1_MSK; //0x430
    volatile uint32_t GPJTAGMS_INTR1_MSK; //0x434
    volatile uint32_t GPAIO_INTR1_MSK; //0x438
    volatile uint32_t GPAB_INTR1_CLR; //0x43c
    volatile uint32_t GPCD_INTR1_CLR; //0x440
    volatile uint32_t GPEF_INTR1_CLR; //0x444
    volatile uint32_t GPGH_INTR1_CLR; //0x448
    volatile uint32_t GPIJ_INTR1_CLR; //0x44c
    volatile uint32_t GPKL_INTR1_CLR; //0x450
    volatile uint32_t GPMN_INTR1_CLR; //0x454
    volatile uint32_t GPOP_INTR1_CLR; //0x458
    volatile uint32_t GPQR_INTR1_CLR; //0x45c
    volatile uint32_t GPST_INTR1_CLR; //0x460
    volatile uint32_t GPUV_INTR1_CLR; //0x464
    volatile uint32_t GPWX_INTR1_CLR; //0x468
    volatile uint32_t GPYZ_INTR1_CLR; //0x46c
    volatile uint32_t GPEEFF_INTR1_CLR; //0x470
    volatile uint32_t GPAABB_INTR1_CLR; //0x474
    volatile uint32_t GPCCDD_INTR1_CLR; //0x478
    volatile uint32_t GPJTAGMS_INTR1_CLR; //0x47c
    volatile uint32_t GPAIO_INTR1_CLR; //0x480
    volatile uint32_t GPAB_INTR1_RAW; //0x484
    volatile uint32_t GPCD_INTR1_RAW; //0x488
    volatile uint32_t GPEF_INTR1_RAW; //0x48c
    volatile uint32_t GPGH_INTR1_RAW; //0x490
    volatile uint32_t GPIJ_INTR1_RAW; //0x494
    volatile uint32_t GPKL_INTR1_RAW; //0x498
    volatile uint32_t GPMN_INTR1_RAW; //0x49c
    volatile uint32_t GPOP_INTR1_RAW; //0x4a0
    volatile uint32_t GPQR_INTR1_RAW; //0x4a4
    volatile uint32_t GPST_INTR1_RAW; //0x4a8
    volatile uint32_t GPUV_INTR1_RAW; //0x4ac
    volatile uint32_t GPWX_INTR1_RAW; //0x4b0
    volatile uint32_t GPYZ_INTR1_RAW; //0x4b4
    volatile uint32_t GPEEFF_INTR1_RAW; //0x4b8
    volatile uint32_t GPAABB_INTR1_RAW; //0x4bc
    volatile uint32_t GPCCDD_INTR1_RAW; //0x4c0
    volatile uint32_t GPJTAGMS_INTR1_RAW; //0x4c4
    volatile uint32_t GPAIO_INTR1_RAW; //0x4c8
    volatile uint32_t GPAB_INTR1_STT; //0x4cc
    volatile uint32_t GPCD_INTR1_STT; //0x4d0
    volatile uint32_t GPEF_INTR1_STT; //0x4d4
    volatile uint32_t GPGH_INTR1_STT; //0x4d8
    volatile uint32_t GPIJ_INTR1_STT; //0x4dc
    volatile uint32_t GPKL_INTR1_STT; //0x4e0
    volatile uint32_t GPMN_INTR1_STT; //0x4e4
    volatile uint32_t GPOP_INTR1_STT; //0x4e8
    volatile uint32_t GPQR_INTR1_STT; //0x4ec
    volatile uint32_t GPST_INTR1_STT; //0x4f0
    volatile uint32_t GPUV_INTR1_STT; //0x4f4
    volatile uint32_t GPWX_INTR1_STT; //0x4f8
    volatile uint32_t GPYZ_INTR1_STT; //0x4fc
    volatile uint32_t GPEEFF_INTR1_STT; //0x500
    volatile uint32_t GPAABB_INTR1_STT; //0x504
    volatile uint32_t GPCCDD_INTR1_STT; //0x508
    volatile uint32_t GPJTAGMS_INTR1_STT; //0x50c
    volatile uint32_t GPAIO_INTR1_STT; //0x510
    volatile uint32_t GPEYZ_AE; //0x514
    volatile uint32_t APB_EXTI0_INTR; //0x518
    volatile uint32_t APB_EXTI1_INTR; //0x51c
    volatile uint32_t APB_EXTI2_INTR; //0x520
    volatile uint32_t APB_EXTI3_INTR; //0x524
    volatile uint32_t GP_MD_LP_CTRL0; //0x528
    volatile uint32_t GP_MD_LP_CTRL1; //0x52c
    volatile uint32_t UART03_RX_MULTIPLEX_SEL; //0x530
    volatile uint32_t UART47_RX_MULTIPLEX_SEL; //0x534
    volatile uint32_t UART811_RX_MULTIPLEX_SEL; //0x538
    volatile uint32_t UART12_RX_MULTIPLEX_SEL; //0x53c
    volatile uint32_t UART03_TX_MULTIPLEX_SEL; //0x540
    volatile uint32_t UART47_TX_MULTIPLEX_SEL; //0x544
    volatile uint32_t UART811_TX_MULTIPLEX_SEL; //0x548
    volatile uint32_t UART1231_TX_MULTIPLEX_SEL; //0x54c
} reg_sysc_awo_t;

enum SYSC_AWO_REG_FUNC0_ABCD_EN_FIELD
{
    SYSC_AWO_FUNC0_IOA_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOA_EN_POS = 0,
    SYSC_AWO_FUNC0_IOB_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOB_EN_POS = 8,
    SYSC_AWO_FUNC0_IOC_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOC_EN_POS = 16,
    SYSC_AWO_FUNC0_IOD_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOD_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_EFGH_EN_FIELD
{
    SYSC_AWO_FUNC0_IOE_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOE_EN_POS = 0,
    SYSC_AWO_FUNC0_IOF_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOF_EN_POS = 8,
    SYSC_AWO_FUNC0_IOG_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOG_EN_POS = 16,
    SYSC_AWO_FUNC0_IOH_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOH_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_IJKL_EN_FIELD
{
    SYSC_AWO_FUNC0_IOI_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOI_EN_POS = 0,
    SYSC_AWO_FUNC0_IOJ_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOJ_EN_POS = 8,
    SYSC_AWO_FUNC0_IOK_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOK_EN_POS = 16,
    SYSC_AWO_FUNC0_IOL_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOL_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_MNOP_EN_FIELD
{
    SYSC_AWO_FUNC0_IOM_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOM_EN_POS = 0,
    SYSC_AWO_FUNC0_ION_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_ION_EN_POS = 8,
    SYSC_AWO_FUNC0_IOO_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOO_EN_POS = 16,
    SYSC_AWO_FUNC0_IOP_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOP_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_QRST_EN_FIELD
{
    SYSC_AWO_FUNC0_IOQ_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOQ_EN_POS = 0,
    SYSC_AWO_FUNC0_IOR_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOR_EN_POS = 8,
    SYSC_AWO_FUNC0_IOS_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOS_EN_POS = 16,
    SYSC_AWO_FUNC0_IOT_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOT_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_UVWX_EN_FIELD
{
    SYSC_AWO_FUNC0_IOU_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOU_EN_POS = 0,
    SYSC_AWO_FUNC0_IOV_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOV_EN_POS = 8,
    SYSC_AWO_FUNC0_IOW_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOW_EN_POS = 16,
    SYSC_AWO_FUNC0_IOX_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IOX_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_YZEEFF_EN_FIELD
{
    SYSC_AWO_FUNC0_IOY_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOY_EN_POS = 0,
    SYSC_AWO_FUNC0_IOZ_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOZ_EN_POS = 8,
    SYSC_AWO_FUNC0_IOEE_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOEE_EN_POS = 16,
    SYSC_AWO_FUNC0_IOFF_EN_MASK = (int)0xf000000,
    SYSC_AWO_FUNC0_IOFF_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC0_AABBCCDD_EN_FIELD
{
    SYSC_AWO_FUNC0_IOAA_EN_MASK = (int)0xff,
    SYSC_AWO_FUNC0_IOAA_EN_POS = 0,
    SYSC_AWO_FUNC0_IOBB_EN_MASK = (int)0xff00,
    SYSC_AWO_FUNC0_IOBB_EN_POS = 8,
    SYSC_AWO_FUNC0_IOCC_EN_MASK = (int)0xff0000,
    SYSC_AWO_FUNC0_IOCC_EN_POS = 16,
    SYSC_AWO_FUNC0_IODD_EN_MASK = (int)0xff000000,
    SYSC_AWO_FUNC0_IODD_EN_POS = 24,
};

enum SYSC_AWO_REG_FUNC1_JTAGMS_EN_FIELD
{
    SYSC_AWO_FUNC1_IOJTAGMS_EN_MASK = (int)0x1f,
    SYSC_AWO_FUNC1_IOJTAGMS_EN_POS = 0,
};

enum SYSC_AWO_REG_FUNC2_JTAGMS_EN_FIELD
{
    SYSC_AWO_FUNC2_IOJTAGMS_EN_MASK = (int)0x1f,
    SYSC_AWO_FUNC2_IOJTAGMS_EN_POS = 0,
};

enum SYSC_AWO_REG_GPJTAGMS_O_FIELD
{
    SYSC_AWO_GPIOJTAGMS_O_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_O_POS = 0,
    SYSC_AWO_GPIOAIO_O_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_O_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_OE_FIELD
{
    SYSC_AWO_GPIOJTAGMS_OE_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_OE_POS = 0,
    SYSC_AWO_GPIOAIO_OE_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_OE_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_I_FIELD
{
    SYSC_AWO_GPIOJTAGMS_I_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_I_POS = 0,
    SYSC_AWO_GPIOAIO_I_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_I_POS = 5,
    SYSC_AWO_TSPRST_I_MASK = (int)0x2000,
    SYSC_AWO_TSPRST_I_POS = 13,
};

enum SYSC_AWO_REG_GPJTAGMS_IE_FIELD
{
    SYSC_AWO_GPIOJTAGMS_IE_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_IE_POS = 0,
    SYSC_AWO_GPIOAIO_IE_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_IE_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_REN_FIELD
{
    SYSC_AWO_GPIOJTAGMS_REN_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_REN_POS = 0,
    SYSC_AWO_GPIOAIO_REN_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_REN_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_ODE_FIELD
{
    SYSC_AWO_GPIOJTAGMS_ODE_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_ODE_POS = 0,
    SYSC_AWO_GPIOAIO_ODE_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_ODE_POS = 5,
};

enum SYSC_AWO_REG_GPIL_PU_FIELD
{
    SYSC_AWO_GPIOI_PU_MASK = (int)0xff,
    SYSC_AWO_GPIOI_PU_POS = 0,
    SYSC_AWO_GPIOL_PU_MASK = (int)0xff00,
    SYSC_AWO_GPIOL_PU_POS = 8,
};

enum SYSC_AWO_REG_GPJTAGMS_PU_FIELD
{
    SYSC_AWO_GPIOJTAGMS_PU_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_PU_POS = 0,
    SYSC_AWO_GPIOAIO_PU_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_PU_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_PD_FIELD
{
    SYSC_AWO_GPIOJTAGMS_PD_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_PD_POS = 0,
    SYSC_AWO_GPIOAIO_PD_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_PD_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_DS0_FIELD
{
    SYSC_AWO_GPIOJTAGMS_DS0_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_DS0_POS = 0,
    SYSC_AWO_GPIOAIO_DS0_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_DS0_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_DS1_FIELD
{
    SYSC_AWO_GPIOJTAGMS_DS1_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_DS1_POS = 0,
    SYSC_AWO_GPIOAIO_DS1_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_DS1_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_DS2_FIELD
{
    SYSC_AWO_GPIOJTAGMS_DS2_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_DS2_POS = 0,
    SYSC_AWO_GPIOAIO_DS2_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_DS2_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_DS3_FIELD
{
    SYSC_AWO_GPIOJTAGMS_DS3_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_DS3_POS = 0,
    SYSC_AWO_GPIOAIO_DS3_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_DS3_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_ST_FIELD
{
    SYSC_AWO_GPIOJTAGMS_ST_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_ST_POS = 0,
    SYSC_AWO_GPIOAIO_ST_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_ST_POS = 5,
};

enum SYSC_AWO_REG_GPJTAGMS_SL_FIELD
{
    SYSC_AWO_GPIOJTAGMS_SL_MASK = (int)0x1f,
    SYSC_AWO_GPIOJTAGMS_SL_POS = 0,
    SYSC_AWO_GPIOAIO_SL_MASK = (int)0x1fe0,
    SYSC_AWO_GPIOAIO_SL_POS = 5,
};

enum SYSC_AWO_REG_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_I2C_MULTIPLEX_SEL_MASK = (int)0xffff,
    SYSC_AWO_I2C_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_SPI_MULTIPLEX_SEL_MASK = (int)0x30000,
    SYSC_AWO_SPI_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_LTPI_I2C_MULTIPLEX_SEL_MASK = (int)0x3ffc0000,
    SYSC_AWO_LTPI_I2C_MULTIPLEX_SEL_POS = 18,
    SYSC_AWO_SGPIO_MASTER_MULTIPLEX_SEL_MASK = (int)0x40000000,
    SYSC_AWO_SGPIO_MASTER_MULTIPLEX_SEL_POS = 30,
};

enum SYSC_AWO_REG_SIG_SEL_FIELD
{
    SYSC_AWO_FUNC_USB_DEBUG_SIG_MASK = (int)0x1f,
    SYSC_AWO_FUNC_USB_DEBUG_SIG_POS = 0,
    SYSC_AWO_FUNC_PTEST_JTAG_SIG_MASK = (int)0x3e0,
    SYSC_AWO_FUNC_PTEST_JTAG_SIG_POS = 5,
};

enum SYSC_AWO_REG_GPIO_INTR_SEL_FIELD
{
    SYSC_AWO_GPIO_INTR0_SEL_MASK = (int)0x1,
    SYSC_AWO_GPIO_INTR0_SEL_POS = 0,
    SYSC_AWO_GPIO_INTR1_SEL_MASK = (int)0x2,
    SYSC_AWO_GPIO_INTR1_SEL_POS = 1,
};

enum SYSC_AWO_REG_GPAB_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOA_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOB_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOC_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOD_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOE_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOF_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOG_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOH_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOI_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOJ_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOK_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOL_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOM_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR0_MSK_POS = 0,
    SYSC_AWO_GPION_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOO_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOP_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOQ_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOR_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOS_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOT_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOU_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOV_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOW_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOX_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOY_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOZ_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOEE_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOFF_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOAA_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOBB_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOCC_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIODD_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR0_MSK_FIELD
{
    SYSC_AWO_GPIOAIO_INTR0_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR0_MSK_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR0_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR0_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOA_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOB_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOC_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOD_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOE_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOF_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOG_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOH_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOI_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOJ_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOK_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOL_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOM_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR0_CLR_POS = 0,
    SYSC_AWO_GPION_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOO_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOP_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOQ_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOR_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOS_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOT_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOU_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOV_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOW_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOX_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOY_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOZ_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOEE_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOFF_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOAA_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOBB_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOCC_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIODD_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR0_CLR_FIELD
{
    SYSC_AWO_GPIOAIO_INTR0_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR0_CLR_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR0_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR0_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOA_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOB_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOC_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOD_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOE_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOF_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOG_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOH_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOI_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOJ_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOK_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOL_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOM_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR0_RAW_POS = 0,
    SYSC_AWO_GPION_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOO_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOP_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOQ_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOR_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOS_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOT_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOU_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOV_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOW_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOX_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOY_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOZ_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOEE_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOFF_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOAA_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOBB_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOCC_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIODD_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR0_RAW_FIELD
{
    SYSC_AWO_GPIOAIO_INTR0_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR0_RAW_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR0_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR0_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOA_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOB_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOC_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOD_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOE_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOF_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOG_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOH_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOI_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOJ_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOK_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOL_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOM_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR0_STT_POS = 0,
    SYSC_AWO_GPION_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOO_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOP_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOQ_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOR_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOS_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOT_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOU_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOV_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOW_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOX_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOY_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOZ_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOEE_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOFF_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOAA_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOBB_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOCC_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR0_STT_POS = 0,
    SYSC_AWO_GPIODD_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR0_STT_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR0_STT_FIELD
{
    SYSC_AWO_GPIOAIO_INTR0_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR0_STT_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR0_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR0_STT_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOA_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOB_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOC_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOD_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOE_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOF_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOG_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOH_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOI_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOJ_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOK_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOL_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOM_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR1_MSK_POS = 0,
    SYSC_AWO_GPION_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOO_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOP_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOQ_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOR_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOS_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOT_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOU_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOV_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOW_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOX_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOY_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOZ_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOEE_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOFF_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOAA_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOBB_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOCC_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIODD_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR1_MSK_FIELD
{
    SYSC_AWO_GPIOAIO_INTR1_MSK_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR1_MSK_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR1_MSK_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR1_MSK_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOA_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOB_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOC_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOD_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOE_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOF_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOG_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOH_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOI_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOJ_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOK_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOL_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOM_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR1_CLR_POS = 0,
    SYSC_AWO_GPION_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOO_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOP_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOQ_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOR_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOS_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOT_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOU_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOV_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOW_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOX_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOY_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOZ_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOEE_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOFF_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOAA_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOBB_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOCC_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIODD_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR1_CLR_FIELD
{
    SYSC_AWO_GPIOAIO_INTR1_CLR_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR1_CLR_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR1_CLR_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR1_CLR_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOA_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOB_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOC_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOD_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOE_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOF_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOG_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOH_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOI_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOJ_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOK_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOL_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOM_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR1_RAW_POS = 0,
    SYSC_AWO_GPION_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOO_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOP_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOQ_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOR_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOS_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOT_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOU_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOV_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOW_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOX_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOY_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOZ_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOEE_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOFF_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOAA_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOBB_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOCC_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIODD_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR1_RAW_FIELD
{
    SYSC_AWO_GPIOAIO_INTR1_RAW_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR1_RAW_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR1_RAW_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR1_RAW_POS = 16,
};

enum SYSC_AWO_REG_GPAB_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOA_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOA_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOB_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOB_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPCD_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOC_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOC_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOD_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOD_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPEF_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOE_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOE_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOF_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOF_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPGH_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOG_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOG_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOH_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOH_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPIJ_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOI_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOI_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOJ_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOJ_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPKL_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOK_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOK_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOL_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOL_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPMN_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOM_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOM_INTR1_STT_POS = 0,
    SYSC_AWO_GPION_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPION_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPOP_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOO_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOO_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOP_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOP_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPQR_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOQ_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOQ_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOR_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOR_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPST_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOS_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOS_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOT_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOT_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPUV_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOU_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOU_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOV_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOV_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPWX_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOW_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOW_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOX_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOX_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPYZ_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOY_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOY_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOZ_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOZ_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPEEFF_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOEE_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOEE_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOFF_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOFF_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPAABB_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOAA_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOAA_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOBB_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOBB_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPCCDD_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOCC_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOCC_INTR1_STT_POS = 0,
    SYSC_AWO_GPIODD_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIODD_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPJTAGMS_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOJTAGMS_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOJTAGMS_INTR1_STT_POS = 0,
    SYSC_AWO_GPIORSTIND_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIORSTIND_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPAIO_INTR1_STT_FIELD
{
    SYSC_AWO_GPIOAIO_INTR1_STT_MASK = (int)0xffff,
    SYSC_AWO_GPIOAIO_INTR1_STT_POS = 0,
    SYSC_AWO_GPIOTSPRST_INTR1_STT_MASK = (int)0xffff0000,
    SYSC_AWO_GPIOTSPRST_INTR1_STT_POS = 16,
};

enum SYSC_AWO_REG_GPEYZ_AE_FIELD
{
    SYSC_AWO_GPIOY_AE_MASK = (int)0xff,
    SYSC_AWO_GPIOY_AE_POS = 0,
    SYSC_AWO_GPIOZ_AE_MASK = (int)0xff00,
    SYSC_AWO_GPIOZ_AE_POS = 8,
    SYSC_AWO_GPIOAIO_AE_MASK = (int)0x1ff0000,
    SYSC_AWO_GPIOAIO_AE_POS = 16,
};

enum SYSC_AWO_REG_APB_EXTI0_INTR_FIELD
{
    SYSC_AWO_APB_EXTI0_CMP_MASK = (int)0xf,
    SYSC_AWO_APB_EXTI0_CMP_POS = 0,
    SYSC_AWO_APB_EXTI0_EXTI_DBC_CMP_MASK = (int)0xf0,
    SYSC_AWO_APB_EXTI0_EXTI_DBC_CMP_POS = 4,
    SYSC_AWO_APB_EXTI0_COMP_ADTRIG_MASK = (int)0xf00,
    SYSC_AWO_APB_EXTI0_COMP_ADTRIG_POS = 8,
    SYSC_AWO_APB_EXTI0_GPIO_ADTRIG_MASK = (int)0x1000,
    SYSC_AWO_APB_EXTI0_GPIO_ADTRIG_POS = 12,
};

enum SYSC_AWO_REG_APB_EXTI1_INTR_FIELD
{
    SYSC_AWO_APB_EXTI1_CMP_MASK = (int)0xf,
    SYSC_AWO_APB_EXTI1_CMP_POS = 0,
    SYSC_AWO_APB_EXTI1_EXTI_DBC_CMP_MASK = (int)0xf0,
    SYSC_AWO_APB_EXTI1_EXTI_DBC_CMP_POS = 4,
    SYSC_AWO_APB_EXTI1_COMP_ADTRIG_MASK = (int)0xf00,
    SYSC_AWO_APB_EXTI1_COMP_ADTRIG_POS = 8,
    SYSC_AWO_APB_EXTI1_GPIO_ADTRIG_MASK = (int)0x1000,
    SYSC_AWO_APB_EXTI1_GPIO_ADTRIG_POS = 12,
};

enum SYSC_AWO_REG_APB_EXTI2_INTR_FIELD
{
    SYSC_AWO_APB_EXTI2_CMP_MASK = (int)0xf,
    SYSC_AWO_APB_EXTI2_CMP_POS = 0,
    SYSC_AWO_APB_EXTI2_EXTI_DBC_CMP_MASK = (int)0xf0,
    SYSC_AWO_APB_EXTI2_EXTI_DBC_CMP_POS = 4,
    SYSC_AWO_APB_EXTI2_COMP_ADTRIG_MASK = (int)0xf00,
    SYSC_AWO_APB_EXTI2_COMP_ADTRIG_POS = 8,
    SYSC_AWO_APB_EXTI2_GPIO_ADTRIG_MASK = (int)0x1000,
    SYSC_AWO_APB_EXTI2_GPIO_ADTRIG_POS = 12,
};

enum SYSC_AWO_REG_APB_EXTI3_INTR_FIELD
{
    SYSC_AWO_APB_EXTI3_CMP_MASK = (int)0xf,
    SYSC_AWO_APB_EXTI3_CMP_POS = 0,
    SYSC_AWO_APB_EXTI3_EXTI_DBC_CMP_MASK = (int)0xf0,
    SYSC_AWO_APB_EXTI3_EXTI_DBC_CMP_POS = 4,
    SYSC_AWO_APB_EXTI3_COMP_ADTRIG_MASK = (int)0xf00,
    SYSC_AWO_APB_EXTI3_COMP_ADTRIG_POS = 8,
    SYSC_AWO_APB_EXTI3_GPIO_ADTRIG_MASK = (int)0x1000,
    SYSC_AWO_APB_EXTI3_GPIO_ADTRIG_POS = 12,
};

enum SYSC_AWO_REG_GP_MD_LP_CTRL0_FIELD
{
    SYSC_AWO_GPIOEMC_MS_MASK = (int)0x1,
    SYSC_AWO_GPIOEMC_MS_POS = 0,
    SYSC_AWO_GPIOESP1_MS_MASK = (int)0x2,
    SYSC_AWO_GPIOESP1_MS_POS = 1,
    SYSC_AWO_GPIOIO0_MD_MASK = (int)0x4,
    SYSC_AWO_GPIOIO0_MD_POS = 2,
    SYSC_AWO_GPIOIO0_LP_MASK = (int)0x8,
    SYSC_AWO_GPIOIO0_LP_POS = 3,
    SYSC_AWO_GPIOIO1_MD_MASK = (int)0x10,
    SYSC_AWO_GPIOIO1_MD_POS = 4,
    SYSC_AWO_GPIOIO1_LP_MASK = (int)0x20,
    SYSC_AWO_GPIOIO1_LP_POS = 5,
    SYSC_AWO_GPIOIO2_MD_MASK = (int)0x40,
    SYSC_AWO_GPIOIO2_MD_POS = 6,
    SYSC_AWO_GPIOIO2_LP_MASK = (int)0x80,
    SYSC_AWO_GPIOIO2_LP_POS = 7,
    SYSC_AWO_GPIOURT_MD_MASK = (int)0x100,
    SYSC_AWO_GPIOURT_MD_POS = 8,
    SYSC_AWO_GPIOURT_LP_MASK = (int)0x200,
    SYSC_AWO_GPIOURT_LP_POS = 9,
    SYSC_AWO_GPIOH3C0_MD_MASK = (int)0x400,
    SYSC_AWO_GPIOH3C0_MD_POS = 10,
    SYSC_AWO_GPIOH3C0_LP_MASK = (int)0x800,
    SYSC_AWO_GPIOH3C0_LP_POS = 11,
    SYSC_AWO_GPIOH3C1_MD_MASK = (int)0x1000,
    SYSC_AWO_GPIOH3C1_MD_POS = 12,
    SYSC_AWO_GPIOH3C1_LP_MASK = (int)0x2000,
    SYSC_AWO_GPIOH3C1_LP_POS = 13,
    SYSC_AWO_GPIOESP0_MD_MASK = (int)0x4000,
    SYSC_AWO_GPIOESP0_MD_POS = 14,
    SYSC_AWO_GPIOESP0_LP_MASK = (int)0x8000,
    SYSC_AWO_GPIOESP0_LP_POS = 15,
    SYSC_AWO_GPIOSPI0_MD_MASK = (int)0x10000,
    SYSC_AWO_GPIOSPI0_MD_POS = 16,
    SYSC_AWO_GPIOSPI0_LP_MASK = (int)0x20000,
    SYSC_AWO_GPIOSPI0_LP_POS = 17,
    SYSC_AWO_GPIOSPI1_MD_MASK = (int)0x40000,
    SYSC_AWO_GPIOSPI1_MD_POS = 18,
    SYSC_AWO_GPIOSPI1_LP_MASK = (int)0x80000,
    SYSC_AWO_GPIOSPI1_LP_POS = 19,
    SYSC_AWO_GPIOSPI2_MD_MASK = (int)0x100000,
    SYSC_AWO_GPIOSPI2_MD_POS = 20,
    SYSC_AWO_GPIOSPI2_LP_MASK = (int)0x200000,
    SYSC_AWO_GPIOSPI2_LP_POS = 21,
    SYSC_AWO_GPIOBMC33_MD_MASK = (int)0x400000,
    SYSC_AWO_GPIOBMC33_MD_POS = 22,
    SYSC_AWO_GPIOBMC33_LP_MASK = (int)0x800000,
    SYSC_AWO_GPIOBMC33_LP_POS = 23,
    SYSC_AWO_GPIOFSP_MD_MASK = (int)0x1000000,
    SYSC_AWO_GPIOFSP_MD_POS = 24,
    SYSC_AWO_GPIOFSP_LP_MASK = (int)0x2000000,
    SYSC_AWO_GPIOFSP_LP_POS = 25,
    SYSC_AWO_GPIOSMB0_MD_MASK = (int)0x4000000,
    SYSC_AWO_GPIOSMB0_MD_POS = 26,
    SYSC_AWO_GPIOSMB0_LP_MASK = (int)0x8000000,
    SYSC_AWO_GPIOSMB0_LP_POS = 27,
    SYSC_AWO_GPIOSMB1_MD_MASK = (int)0x10000000,
    SYSC_AWO_GPIOSMB1_MD_POS = 28,
    SYSC_AWO_GPIOSMB1_LP_MASK = (int)0x20000000,
    SYSC_AWO_GPIOSMB1_LP_POS = 29,
    SYSC_AWO_GPIOSGP0_MD_MASK = (int)0x40000000,
    SYSC_AWO_GPIOSGP0_MD_POS = 30,
    SYSC_AWO_GPIOSGP0_LP_MASK = (int)0x80000000,
    SYSC_AWO_GPIOSGP0_LP_POS = 31,
};

enum SYSC_AWO_REG_GP_MD_LP_CTRL1_FIELD
{
    SYSC_AWO_GPIOSGP1_MD_MASK = (int)0x1,
    SYSC_AWO_GPIOSGP1_MD_POS = 0,
    SYSC_AWO_GPIOSGP1_LP_MASK = (int)0x2,
    SYSC_AWO_GPIOSGP1_LP_POS = 1,
    SYSC_AWO_GPIORGM0_MD_MASK = (int)0x4,
    SYSC_AWO_GPIORGM0_MD_POS = 2,
    SYSC_AWO_GPIORGM0_LP_MASK = (int)0x8,
    SYSC_AWO_GPIORGM0_LP_POS = 3,
    SYSC_AWO_GPIORGM1_MD_MASK = (int)0x10,
    SYSC_AWO_GPIORGM1_MD_POS = 4,
    SYSC_AWO_GPIORGM1_LP_MASK = (int)0x20,
    SYSC_AWO_GPIORGM1_LP_POS = 5,
};

enum SYSC_AWO_REG_UART03_RX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART0_RX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART0_RX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART1_RX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART1_RX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART2_RX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART2_RX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART3_RX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART3_RX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART47_RX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART4_RX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART4_RX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART5_RX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART5_RX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART6_RX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART6_RX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART7_RX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART7_RX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART811_RX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART8_RX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART8_RX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART9_RX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART9_RX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART10_RX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART10_RX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART11_RX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART11_RX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART12_RX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART12_RX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART12_RX_MULTIPLEX_SEL_POS = 0,
};

enum SYSC_AWO_REG_UART03_TX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART0_TX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART0_TX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART1_TX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART1_TX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART2_TX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART2_TX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART30_TX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART30_TX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART47_TX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART4_TX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART4_TX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART5_TX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART5_TX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART6_TX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART6_TX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART7_TX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART7_TX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART811_TX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART8_TX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART8_TX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART9_TX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART9_TX_MULTIPLEX_SEL_POS = 8,
    SYSC_AWO_UART10_TX_MULTIPLEX_SEL_MASK = (int)0xff0000,
    SYSC_AWO_UART10_TX_MULTIPLEX_SEL_POS = 16,
    SYSC_AWO_UART11_TX_MULTIPLEX_SEL_MASK = (int)0xff000000,
    SYSC_AWO_UART11_TX_MULTIPLEX_SEL_POS = 24,
};

enum SYSC_AWO_REG_UART1231_TX_MULTIPLEX_SEL_FIELD
{
    SYSC_AWO_UART12_TX_MULTIPLEX_SEL_MASK = (int)0xff,
    SYSC_AWO_UART12_TX_MULTIPLEX_SEL_POS = 0,
    SYSC_AWO_UART31_TX_MULTIPLEX_SEL_MASK = (int)0xff00,
    SYSC_AWO_UART31_TX_MULTIPLEX_SEL_POS = 8,
};

#ifdef __cplusplus
}
#endif

#endif

