import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    'at_sig_mesh_prover_recv_cmd.c',
    'at_sig_mesh_prover_cmd_parse.c',
    'at_sig_mesh_prover_cmd_ind.c',
]
inc = [
    '.'
]
env.app_build('sig_mesh_provisioner',src,inc,mesh = True)