import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c'
]
inc = [
    '.'
]
env.app_build('ble_hid',src,inc)
env.Append(LIBS = [File(env.subst('$SDK_ROOT/soc/arm_cm/le501x/bin/rssi_smth_algo.o'))])
