#ifndef QSPIV2_CONFIG_H_
#define QSPIV2_CONFIG_H_

#define QSPI_CLK_CYCLE 1
#define QSPI_CS_INTERVAL 4
#define QSPI_CS_HOLD 2
#define QSPI_CS_SETUP 2
#define QSPI_CAPTURE_DELAY 2
#define QSPI_CAPTURE_NEG 1
#endif

