#ifndef REG_SYSC_CPU_TYPE_H_
#define REG_SYSC_CPU_TYPE_H_
#include <stdint.h>

#define SYSC_CPU ((reg_sysc_cpu_t *)0x4000c000)

typedef struct
{
    volatile uint32_t CPU_SYSC; //0x0
    volatile uint32_t GATE_SYS; //0x4
    volatile uint32_t SYS_TICK_CALIB; //0x8
    volatile uint32_t RESERVED0[1];
    volatile uint32_t PD_CPU_CLKG; //0x10
    volatile uint32_t PD_CPU_SRST; //0x14
    volatile uint32_t RESERVED1[2];
    volatile uint32_t DMAC_CH_SEL0; //0x20
    volatile uint32_t DMAC_CH_SEL1; //0x24
}reg_sysc_cpu_t;

enum SYSC_CPU_REG_CPU_SYSC_FIELD
{
    SYSC_CPU_CACHE_MEMTST_MASK = (int)0x10,
    SYSC_CPU_CACHE_MEMTST_POS = 4,
    SYSC_CPU_WDT_DBG_MASK = (int)0x100,
    SYSC_CPU_WDT_DBG_POS = 8,
    SYSC_CPU_WWDT_DBG_MASK = (int)0x1000,
    SYSC_CPU_WWDT_DBG_POS = 12,
};

enum SYSC_CPU_REG_GATE_SYS_FIELD
{
    SYSC_CPU_GATE_SYS_EN_MASK = (int)0x1,
    SYSC_CPU_GATE_SYS_EN_POS = 0,
    SYSC_CPU_USB_RX_DIFF_SEL_MASK = (int)0x10,
    SYSC_CPU_USB_RX_DIFF_SEL_POS = 4,
};

enum SYSC_CPU_REG_SYS_TICK_CALIB_FIELD
{
    SYSC_CPU_CPU_ST_CALIB_MASK = (int)0x3ffffff,
    SYSC_CPU_CPU_ST_CALIB_POS = 0,
};

enum SYSC_CPU_REG_PD_CPU_CLKG_FIELD
{
    SYSC_CPU_CLKG_SET_CACHE_MASK = (int)0x4,
    SYSC_CPU_CLKG_SET_CACHE_POS = 2,
    SYSC_CPU_CLKG_CLR_CACHE_MASK = (int)0x8,
    SYSC_CPU_CLKG_CLR_CACHE_POS = 3,
    SYSC_CPU_CLKG_SET_QSPI_MASK = (int)0x10,
    SYSC_CPU_CLKG_SET_QSPI_POS = 4,
    SYSC_CPU_CLKG_CLR_QSPI_MASK = (int)0x20,
    SYSC_CPU_CLKG_CLR_QSPI_POS = 5,
    SYSC_CPU_CLKG_SET_USB_MASK = (int)0x40,
    SYSC_CPU_CLKG_SET_USB_POS = 6,
    SYSC_CPU_CLKG_CLR_USB_MASK = (int)0x80,
    SYSC_CPU_CLKG_CLR_USB_POS = 7,
    SYSC_CPU_CLKG_SET_DMAC_MASK = (int)0x100,
    SYSC_CPU_CLKG_SET_DMAC_POS = 8,
    SYSC_CPU_CLKG_CLR_DMAC_MASK = (int)0x200,
    SYSC_CPU_CLKG_CLR_DMAC_POS = 9,
    SYSC_CPU_CLKG_SET_CALC_CRC_MASK = (int)0x400,
    SYSC_CPU_CLKG_SET_CALC_CRC_POS = 10,
    SYSC_CPU_CLKG_CLR_CALC_CRC_MASK = (int)0x800,
    SYSC_CPU_CLKG_CLR_CALC_CRC_POS = 11,
    SYSC_CPU_CLKG_SET_CALC_MASK = (int)0x1000,
    SYSC_CPU_CLKG_SET_CALC_POS = 12,
    SYSC_CPU_CLKG_CLR_CALC_MASK = (int)0x2000,
    SYSC_CPU_CLKG_CLR_CALC_POS = 13,
    SYSC_CPU_CLKG_SET_BXCAN_MASK = (int)0x4000,
    SYSC_CPU_CLKG_SET_BXCAN_POS = 14,
    SYSC_CPU_CLKG_CLR_BXCAN_MASK = (int)0x8000,
    SYSC_CPU_CLKG_CLR_BXCAN_POS = 15,
    SYSC_CPU_CLKG_SET_CRYPT_MASK = (int)0x10000,
    SYSC_CPU_CLKG_SET_CRYPT_POS = 16,
    SYSC_CPU_CLKG_CLR_CRYPT_MASK = (int)0x20000,
    SYSC_CPU_CLKG_CLR_CRYPT_POS = 17,
    SYSC_CPU_CLKG_SET_ECC_MASK = (int)0x40000,
    SYSC_CPU_CLKG_SET_ECC_POS = 18,
    SYSC_CPU_CLKG_CLR_ECC_MASK = (int)0x80000,
    SYSC_CPU_CLKG_CLR_ECC_POS = 19,
    SYSC_CPU_CLKG_SET_CALC_SHA_MASK = (int)0x100000,
    SYSC_CPU_CLKG_SET_CALC_SHA_POS = 20,
    SYSC_CPU_CLKG_CLR_CALC_SHA_MASK = (int)0x200000,
    SYSC_CPU_CLKG_CLR_CALC_SHA_POS = 21,
    SYSC_CPU_CLKG_SET_CALC_SM4_MASK = (int)0x400000,
    SYSC_CPU_CLKG_SET_CALC_SM4_POS = 22,
    SYSC_CPU_CLKG_CLR_CALC_SM4_MASK = (int)0x800000,
    SYSC_CPU_CLKG_CLR_CALC_SM4_POS = 23,
};

enum SYSC_CPU_REG_PD_CPU_SRST_FIELD
{
    SYSC_CPU_SRST_SET_CACHE_N_MASK = (int)0x4,
    SYSC_CPU_SRST_SET_CACHE_N_POS = 2,
    SYSC_CPU_SRST_CLR_CACHE_N_MASK = (int)0x8,
    SYSC_CPU_SRST_CLR_CACHE_N_POS = 3,
    SYSC_CPU_SRST_SET_QSPI_N_MASK = (int)0x10,
    SYSC_CPU_SRST_SET_QSPI_N_POS = 4,
    SYSC_CPU_SRST_CLR_QSPI_N_MASK = (int)0x20,
    SYSC_CPU_SRST_CLR_QSPI_N_POS = 5,
    SYSC_CPU_SRST_SET_USB_N_MASK = (int)0x40,
    SYSC_CPU_SRST_SET_USB_N_POS = 6,
    SYSC_CPU_SRST_CLR_USB_N_MASK = (int)0x80,
    SYSC_CPU_SRST_CLR_USB_N_POS = 7,
    SYSC_CPU_SRST_SET_DMAC_MASK = (int)0x100,
    SYSC_CPU_SRST_SET_DMAC_POS = 8,
    SYSC_CPU_SRST_CLR_DMAC_MASK = (int)0x200,
    SYSC_CPU_SRST_CLR_DMAC_POS = 9,
    SYSC_CPU_SRST_SET_CALC_CRC_MASK = (int)0x400,
    SYSC_CPU_SRST_SET_CALC_CRC_POS = 10,
    SYSC_CPU_SRST_CLR_CALC_CRC_MASK = (int)0x800,
    SYSC_CPU_SRST_CLR_CALC_CRC_POS = 11,
    SYSC_CPU_SRST_SET_CALC_MASK = (int)0x1000,
    SYSC_CPU_SRST_SET_CALC_POS = 12,
    SYSC_CPU_SRST_CLR_CALC_MASK = (int)0x2000,
    SYSC_CPU_SRST_CLR_CALC_POS = 13,
    SYSC_CPU_SRST_SET_BXCAN_MASK = (int)0x4000,
    SYSC_CPU_SRST_SET_BXCAN_POS = 14,
    SYSC_CPU_SRST_CLR_BXCAN_MASK = (int)0x8000,
    SYSC_CPU_SRST_CLR_BXCAN_POS = 15,
    SYSC_CPU_SRST_SET_CRYPT_MASK = (int)0x10000,
    SYSC_CPU_SRST_SET_CRYPT_POS = 16,
    SYSC_CPU_SRST_CLR_CRYPT_MASK = (int)0x20000,
    SYSC_CPU_SRST_CLR_CRYPT_POS = 17,
    SYSC_CPU_SRST_SET_ECC_MASK = (int)0x40000,
    SYSC_CPU_SRST_SET_ECC_POS = 18,
    SYSC_CPU_SRST_CLR_ECC_MASK = (int)0x80000,
    SYSC_CPU_SRST_CLR_ECC_POS = 19,
    SYSC_CPU_SRST_SET_CALC_SHA_MASK = (int)0x100000,
    SYSC_CPU_SRST_SET_CALC_SHA_POS = 20,
    SYSC_CPU_SRST_CLR_CALC_SHA_MASK = (int)0x200000,
    SYSC_CPU_SRST_CLR_CALC_SHA_POS = 21,
    SYSC_CPU_SRST_SET_CALC_SM4_MASK = (int)0x400000,
    SYSC_CPU_SRST_SET_CALC_SM4_POS = 22,
    SYSC_CPU_SRST_CLR_CALC_SM4_MASK = (int)0x800000,
    SYSC_CPU_SRST_CLR_CALC_SM4_POS = 23,
};

enum SYSC_CPU_REG_DMAC_CH_SEL0_FIELD
{
    SYSC_CPU_DMAC_CH0_SEL_MASK = (int)0x7f,
    SYSC_CPU_DMAC_CH0_SEL_POS = 0,
    SYSC_CPU_DMAC_CH1_SEL_MASK = (int)0x7f00,
    SYSC_CPU_DMAC_CH1_SEL_POS = 8,
    SYSC_CPU_DMAC_CH2_SEL_MASK = (int)0x7f0000,
    SYSC_CPU_DMAC_CH2_SEL_POS = 16,
    SYSC_CPU_DMAC_CH3_SEL_MASK = (int)0x7f000000,
    SYSC_CPU_DMAC_CH3_SEL_POS = 24,
};

enum SYSC_CPU_REG_DMAC_CH_SEL1_FIELD
{
    SYSC_CPU_DMAC_CH4_SEL_MASK = (int)0x7f,
    SYSC_CPU_DMAC_CH4_SEL_POS = 0,
    SYSC_CPU_DMAC_CH5_SEL_MASK = (int)0x7f00,
    SYSC_CPU_DMAC_CH5_SEL_POS = 8,
    SYSC_CPU_DMAC_CH6_SEL_MASK = (int)0x7f0000,
    SYSC_CPU_DMAC_CH6_SEL_POS = 16,
    SYSC_CPU_DMAC_CH7_SEL_MASK = (int)0x7f000000,
    SYSC_CPU_DMAC_CH7_SEL_POS = 24,
};

#endif

