import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    '../../../module/micro-ecc/uECC.c'
]
inc = [
    '.',
    '../../../module/micro-ecc/'
]
env.app_build('ble_uart_server',src,inc)
