import os
env = Environment(ENV = os.environ)
env['IC'] = 'leo'
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c'
]
inc = [
    '.'
]
env.app_build('adc_pingpong_dma',src,inc,ble = False)
