import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env['IC'] = 'leo'
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
]
inc = [
    '.'
]
env.app_build('lvd33',src,inc, ble = False)
