import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c',
    'user_info_config.c'
]
inc = [
    '.'
]

env['LINKSCRIPT'] = File(env.subst('compiler/$COMPILER/${IC}_mcu_link.txt'))
env.app_build('iap_application',src,inc,ble = False)
