import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../$SDK_ROOT/module/adpcm/adpcm.c',
    '../../Source/main.c',
]
inc = [
    '../../Include/.',
    '../../$SDK_ROOT/module/adpcm',
    '../../.',
]
env.app_build('adc_amic_sampling',src,inc,ble = False)
