import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'main.c'
]
inc = [
    '.'
]
env.app_build('ble_pairing_slave_role',src,inc)
