import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    'core_list_join.c',
    'core_main.c',
    'core_matrix.c',
    'core_portme.c',
    'core_state.c',
    'core_util.c',
]
inc = [
    '.'
]
#env['LINKSCRIPT'] = File(env.subst('$IC/ram_link.txt'))
#env.image_build('coremark',src,inc)
env.app_build('coremark',src,inc,ble = False)