import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [  
    'main.c',  
    '../bsp.c',
    'keyscan/keyscan.c',
    'usb_descriptors.c',
]
inc = [
    '.',
    'keyscan/'
]
env.app_build('usbd_hid_keyboard',src,inc, ble = False,usb = True)


