/*
 * Copyright (c) 2025 Linkedsemi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef LS_SOC_RESET_H_
#define LS_SOC_RESET_H_

#include <stdint.h>
#include "reg_base_addr.h"

#define LS_FUNC_RST_REG_POS  0
#define LS_FUNC_RST_SET_POS  22
#define LS_FUNC_RST_CLR_POS  27

#define GEN_RESET(FUNC)  FUNC##_RST_BASE, FUNC##_RST_REG, FUNC##_RST_SET_POS, FUNC##_RST_CLR_POS

#define BSTIM1_RESET     GEN_RESET(BSTIM1)
#define BSTIM2_RESET     GEN_RESET(BSTIM2)
#define GPTIMA1_RESET    GEN_RESET(GPTIMA1)
#define GPTIMA2_RESET    GEN_RESET(GPTIMA2)
#define GPTIMB1_RESET    GEN_RESET(GPTIMB1)
#define GPTIMC1_RESET    GEN_RESET(GPTIMC1)
#define ADTIM1_RESET     GEN_RESET(ADTIM1)
#define ADTIM2_RESET     GEN_RESET(ADTIM2)
#define PWM_RESET        GEN_RESET(PWM)
#define CAP_RESET        GEN_RESET(CAP)
#define I2C2_RESET       GEN_RESET(I2C2)
#define I2C3_RESET       GEN_RESET(I2C3)
#define I2C4_RESET       GEN_RESET(I2C4)
#define I2C5_RESET       GEN_RESET(I2C5)
#define I2C6_RESET       GEN_RESET(I2C6)
#define I2C7_RESET       GEN_RESET(I2C7)
#define I2C8_RESET       GEN_RESET(I2C8)
#define I2C9_RESET       GEN_RESET(I2C9)
#define I2C10_RESET      GEN_RESET(I2C10)
#define I2C11_RESET      GEN_RESET(I2C11)
#define I2C12_RESET      GEN_RESET(I2C12)
#define I2C13_RESET      GEN_RESET(I2C13)
#define I2C14_RESET      GEN_RESET(I2C14)
#define I2C15_RESET      GEN_RESET(I2C15)
#define I2C16_RESET      GEN_RESET(I2C16)
#define UART2_RESET      GEN_RESET(UART2)
#define UART3_RESET      GEN_RESET(UART3)
#define UART4_RESET      GEN_RESET(UART4)
#define UART5_RESET      GEN_RESET(UART5)
#define UART6_RESET      GEN_RESET(UART6)
#define UART7_RESET      GEN_RESET(UART7)
#define UART8_RESET      GEN_RESET(UART8)
#define UART9_RESET      GEN_RESET(UART9)
#define UART10_RESET     GEN_RESET(UART10)
#define UART11_RESET     GEN_RESET(UART11)
#define UART12_RESET     GEN_RESET(UART12)
#define SPI1_RESET       GEN_RESET(SPI1)
#define SPI2_RESET       GEN_RESET(SPI2)
#define ADC1_RESET       GEN_RESET(ADC1)
#define ADC2_RESET       GEN_RESET(ADC2)
#define EXTI1_RESET      GEN_RESET(EXTI1)
#define EXTI2_RESET      GEN_RESET(EXTI2)
#define EXTI3_RESET      GEN_RESET(EXTI3)
#define EXTI4_RESET      GEN_RESET(EXTI4)
#define MJTAG1_RESET     GEN_RESET(MJTAG1)
#define MJTAG2_RESET     GEN_RESET(MJTAG2)
#define MJTAG3_RESET     GEN_RESET(MJTAG3)
#define IWDT2_RESET      GEN_RESET(IWDT2)
#define I3C2_RESET       GEN_RESET(I3C2)
#define I3C3_RESET       GEN_RESET(I3C3)
#define I3C4_RESET       GEN_RESET(I3C4)
#define I3C5_RESET       GEN_RESET(I3C5)
#define I3C6_RESET       GEN_RESET(I3C6)
#define I3C7_RESET       GEN_RESET(I3C7)
#define I3C8_RESET       GEN_RESET(I3C8)
#define I3C9_RESET       GEN_RESET(I3C9)
#define I3C10_RESET      GEN_RESET(I3C10)
#define I3C11_RESET      GEN_RESET(I3C11)
#define I3C12_RESET      GEN_RESET(I3C12)
#define I3C13_RESET      GEN_RESET(I3C13)
#define I3C14_RESET      GEN_RESET(I3C14)
#define PECI1_RESET      GEN_RESET(PECI1)
#define PECI2_RESET      GEN_RESET(PECI2)
#define WWDT2_RESET      GEN_RESET(WWDT2)
#define KSCAN_RESET      GEN_RESET(KSCAN)
#define PS2IF1_RESET     GEN_RESET(PS2IF1)
#define PS2IF2_RESET     GEN_RESET(PS2IF2)
#define OWM_RESET        GEN_RESET(OWM)
#define CEC_RESET        GEN_RESET(CEC)
#define PIS_RESET        GEN_RESET(PIS)
#define FILTER_RESET     GEN_RESET(FILTER)
#define PDM_RESET        GEN_RESET(PDM)
#define PARAL_RESET      GEN_RESET(PARAL)
#define SGPIO1_MST_RESET GEN_RESET(SGPIO1_MST)
#define SGPIO2_MST_RESET GEN_RESET(SGPIO2_MST)
#define SGPIO1_MON_RESET GEN_RESET(SGPIO1_MON)
#define SGPIO2_MON_RESET GEN_RESET(SGPIO2_MON)
#define SMB_FLT1_RESET   GEN_RESET(SMB_FLT1)
#define SMB_FLT2_RESET   GEN_RESET(SMB_FLT2)
#define SMB_FLT3_RESET   GEN_RESET(SMB_FLT3)
#define SMB_FLT4_RESET   GEN_RESET(SMB_FLT4)
#define RST_SET_RESET    GEN_RESET(RST_SET)
#define CACHE1_RESET     GEN_RESET(CACHE1)
#define IOPMP_RESET      GEN_RESET(IOPMP)
#define QSPI1_RESET      GEN_RESET(QSPI1)
#define SHA512_RESET     GEN_RESET(SHA512)
#define OTFAD_AES_RESET  GEN_RESET(OTFAD_AES)
#define CALC_CRC_RESET   GEN_RESET(CALC_CRC)
#define CALC_RESET       GEN_RESET(CALC)
#define CRYPT_RESET      GEN_RESET(CRYPT)
#define OTP_CTRL_RESET   GEN_RESET(OTP_CTRL)
#define CALC_SHA_RESET   GEN_RESET(CALC_SHA)
#define CALC_SM4_RESET   GEN_RESET(CALC_SM4)
#define OTBN_RESET       GEN_RESET(OTBN)
#define NIST_TRNG_RESET  GEN_RESET(NIST_TRNG)
#define CACHE2_RESET     GEN_RESET(CACHE2)
#define QSPI2_RESET      GEN_RESET(QSPI2)
#define USB1_RESET       GEN_RESET(USB1)
#define USB2_RESET       GEN_RESET(USB2)
#define DMAC1_RESET      GEN_RESET(DMAC1)
#define DMAC2_RESET      GEN_RESET(DMAC2)
#define ESPI1_RESET      GEN_RESET(ESPI1)
#define ESPI2_RESET      GEN_RESET(ESPI2)
#define LPC1_RESET       GEN_RESET(LPC1)
#define LPC2_RESET       GEN_RESET(LPC2)
#define FDCAN_RESET      GEN_RESET(FDCAN)
#define PSRAM_RESET      GEN_RESET(PSRAM)
#define SPI3_RESET       GEN_RESET(SPI3)
#define SPI4_RESET       GEN_RESET(SPI4)
#define SPIS1_RESET      GEN_RESET(SPIS1)
#define SPIS2_RESET      GEN_RESET(SPIS2)
#define SPI1_FLT_RESET   GEN_RESET(SPI1_FLT)
#define SPI2_FLT_RESET   GEN_RESET(SPI2_FLT)
#define SPI3_FLT_RESET   GEN_RESET(SPI3_FLT)
#define SPI4_FLT_RESET   GEN_RESET(SPI4_FLT)
#define ETH1_RESET       GEN_RESET(ETH1)
#define ETH2_RESET       GEN_RESET(ETH2)
#define EMMC1_RESET      GEN_RESET(EMMC1)
#define EMMC2_RESET      GEN_RESET(EMMC2)
#define LTPI_SCM_RESET   GEN_RESET(LTPI_SCM)
#define LTPI_HPM_RESET   GEN_RESET(LTPI_HPM)
#define LTPI_PHY_RESET   GEN_RESET(LTPI_PHY)
#define I2C1_RESET       GEN_RESET(I2C1)
#define I3C1_RESET       GEN_RESET(I3C1)
#define UART1_RESET      GEN_RESET(UART1)
#define IWDT1_RESET      GEN_RESET(IWDT1)
#define WWDT1_RESET      GEN_RESET(WWDT1)
#define TRNG_RESET       GEN_RESET(TRNG)
#define TPM_SPIS1_RESET  GEN_RESET(TPM_SPIS1)
#define TPM_SPIS2_RESET  GEN_RESET(TPM_SPIS2)

#define PD_CPU_SRST0_RSTREG  0x18
#define PD_CPU_SRST1_RSTREG  0x1c
#define PD_PER_SRST0_RSTREG  0x10
#define PD_PER_SRST1_RSTREG  0x14
#define PD_PER_SRST2_RSTREG  0x18
#define PD_PER_SRST3_RSTREG  0x1c
#define PD_PER_SRST4_RSTREG  0x28
#define PD_PER_SRST5_RSTREG  0x2c

#define sysc_app_cpu APP_SYSC_CPU_APP_ADDR
#define sysc_app_per APP_SYSC_APP_PER_ADDR
#define sysc_sec_cpu SEC_SYSC_CPU_SEC_ADDR
#define sysc_sec_per SEC_SYSC_SEC_PER_ADDR

#define BSTIM1_RST_BASE     sysc_app_per
#define BSTIM2_RST_BASE     sysc_app_per
#define GPTIMA1_RST_BASE    sysc_app_per
#define GPTIMA2_RST_BASE    sysc_app_per
#define GPTIMB1_RST_BASE    sysc_app_per
#define GPTIMC1_RST_BASE    sysc_app_per
#define ADTIM1_RST_BASE     sysc_app_per
#define ADTIM2_RST_BASE     sysc_app_per
#define PWM_RST_BASE        sysc_app_per
#define CAP_RST_BASE        sysc_app_per
#define I2C2_RST_BASE       sysc_app_per
#define I2C3_RST_BASE       sysc_app_per
#define I2C4_RST_BASE       sysc_app_per
#define I2C5_RST_BASE       sysc_app_per
#define I2C6_RST_BASE       sysc_app_per
#define I2C7_RST_BASE       sysc_app_per
#define I2C8_RST_BASE       sysc_app_per
#define I2C9_RST_BASE       sysc_app_per
#define I2C10_RST_BASE      sysc_app_per
#define I2C11_RST_BASE      sysc_app_per
#define I2C12_RST_BASE      sysc_app_per
#define I2C13_RST_BASE      sysc_app_per
#define I2C14_RST_BASE      sysc_app_per
#define I2C15_RST_BASE      sysc_app_per
#define I2C16_RST_BASE      sysc_app_per
#define UART2_RST_BASE      sysc_app_per
#define UART3_RST_BASE      sysc_app_per
#define UART4_RST_BASE      sysc_app_per
#define UART5_RST_BASE      sysc_app_per
#define UART6_RST_BASE      sysc_app_per
#define UART7_RST_BASE      sysc_app_per
#define UART8_RST_BASE      sysc_app_per
#define UART9_RST_BASE      sysc_app_per
#define UART10_RST_BASE     sysc_app_per
#define UART11_RST_BASE     sysc_app_per
#define UART12_RST_BASE     sysc_app_per
#define SPI1_RST_BASE       sysc_app_per
#define SPI2_RST_BASE       sysc_app_per
#define ADC1_RST_BASE       sysc_app_per
#define ADC2_RST_BASE       sysc_app_per
#define EXTI1_RST_BASE      sysc_app_per
#define EXTI2_RST_BASE      sysc_app_per
#define EXTI3_RST_BASE      sysc_app_per
#define EXTI4_RST_BASE      sysc_app_per
#define MJTAG1_RST_BASE     sysc_app_per
#define MJTAG2_RST_BASE     sysc_app_per
#define MJTAG3_RST_BASE     sysc_app_per
#define IWDT2_RST_BASE      sysc_app_per
#define I3C2_RST_BASE       sysc_app_per
#define I3C3_RST_BASE       sysc_app_per
#define I3C4_RST_BASE       sysc_app_per
#define I3C5_RST_BASE       sysc_app_per
#define I3C6_RST_BASE       sysc_app_per
#define I3C7_RST_BASE       sysc_app_per
#define I3C8_RST_BASE       sysc_app_per
#define I3C9_RST_BASE       sysc_app_per
#define I3C10_RST_BASE      sysc_app_per
#define I3C11_RST_BASE      sysc_app_per
#define I3C12_RST_BASE      sysc_app_per
#define I3C13_RST_BASE      sysc_app_per
#define I3C14_RST_BASE      sysc_app_per
#define PECI1_RST_BASE      sysc_app_per
#define PECI2_RST_BASE      sysc_app_per
#define WWDT2_RST_BASE      sysc_app_per
#define KSCAN_RST_BASE      sysc_app_per
#define PS2IF1_RST_BASE     sysc_app_per
#define PS2IF2_RST_BASE     sysc_app_per
#define OWM_RST_BASE        sysc_app_per
#define CEC_RST_BASE        sysc_app_per
#define PIS_RST_BASE        sysc_app_per
#define FILTER_RST_BASE     sysc_app_per
#define PDM_RST_BASE        sysc_app_per
#define PARAL_RST_BASE      sysc_app_per
#define SGPIO1_MST_RST_BASE sysc_app_per
#define SGPIO2_MST_RST_BASE sysc_app_per
#define SGPIO1_MON_RST_BASE sysc_app_per
#define SGPIO2_MON_RST_BASE sysc_app_per
#define SMB_FLT1_RST_BASE   sysc_app_per
#define SMB_FLT2_RST_BASE   sysc_app_per
#define SMB_FLT3_RST_BASE   sysc_app_per
#define SMB_FLT4_RST_BASE   sysc_app_per
#define RST_SET_RST_BASE    sysc_sec_cpu
#define CACHE1_RST_BASE     sysc_sec_cpu
#define IOPMP_RST_BASE      sysc_sec_cpu
#define QSPI1_RST_BASE      sysc_sec_cpu
#define SHA512_RST_BASE     sysc_sec_cpu
#define OTFAD_AES_RST_BASE  sysc_sec_cpu
#define CALC_CRC_RST_BASE   sysc_sec_cpu
#define CALC_RST_BASE       sysc_sec_cpu
#define CRYPT_RST_BASE      sysc_sec_cpu
#define OTP_CTRL_RST_BASE   sysc_sec_cpu
#define CALC_SHA_RST_BASE   sysc_sec_cpu
#define CALC_SM4_RST_BASE   sysc_sec_cpu
#define OTBN_RST_BASE       sysc_sec_cpu
#define TPM_SPIS1_RST_BASE  sysc_sec_cpu
#define TPM_SPIS2_RST_BASE  sysc_sec_cpu
#define NIST_TRNG_RST_BASE  sysc_sec_cpu
#define CACHE2_RST_BASE     sysc_app_cpu
#define QSPI2_RST_BASE      sysc_app_cpu
#define USB1_RST_BASE       sysc_app_cpu
#define USB2_RST_BASE       sysc_app_cpu
#define DMAC1_RST_BASE      sysc_app_cpu
#define DMAC2_RST_BASE      sysc_app_cpu
#define ESPI1_RST_BASE      sysc_app_cpu
#define ESPI2_RST_BASE      sysc_app_cpu
#define LPC1_RST_BASE       sysc_app_cpu
#define LPC2_RST_BASE       sysc_app_cpu
#define FDCAN_RST_BASE      sysc_app_cpu
#define PSRAM_RST_BASE      sysc_app_cpu
#define SPI3_RST_BASE       sysc_app_cpu
#define SPI4_RST_BASE       sysc_app_cpu
#define SPIS1_RST_BASE      sysc_app_cpu
#define SPIS2_RST_BASE      sysc_app_cpu
#define SPI1_FLT_RST_BASE   sysc_app_cpu
#define SPI2_FLT_RST_BASE   sysc_app_cpu
#define SPI3_FLT_RST_BASE   sysc_app_cpu
#define SPI4_FLT_RST_BASE   sysc_app_cpu
#define ETH1_RST_BASE       sysc_app_cpu
#define ETH2_RST_BASE       sysc_app_cpu
#define EMMC1_RST_BASE      sysc_app_cpu
#define EMMC2_RST_BASE      sysc_app_cpu
#define LTPI_SCM_RST_BASE   sysc_app_cpu
#define LTPI_HPM_RST_BASE   sysc_app_cpu
#define LTPI_PHY_RST_BASE   sysc_app_cpu
#define I2C1_RST_BASE       sysc_sec_per
#define I3C1_RST_BASE       sysc_sec_per
#define UART1_RST_BASE      sysc_sec_per
#define IWDT1_RST_BASE      sysc_sec_per
#define WWDT1_RST_BASE      sysc_sec_per
#define TRNG_RST_BASE       sysc_sec_per

#define I2C1_RST_REG  PD_PER_SRST0_RSTREG
#define I3C1_RST_REG  PD_PER_SRST0_RSTREG
#define UART1_RST_REG PD_PER_SRST0_RSTREG
#define IWDT1_RST_REG PD_PER_SRST0_RSTREG
#define WWDT1_RST_REG PD_PER_SRST0_RSTREG
#define TRNG_RST_REG  PD_PER_SRST0_RSTREG

#define BSTIM1_RST_REG  PD_PER_SRST0_RSTREG
#define BSTIM2_RST_REG  PD_PER_SRST0_RSTREG
#define GPTIMA1_RST_REG PD_PER_SRST0_RSTREG
#define GPTIMA2_RST_REG PD_PER_SRST0_RSTREG
#define GPTIMB1_RST_REG PD_PER_SRST0_RSTREG
#define GPTIMC1_RST_REG PD_PER_SRST0_RSTREG
#define ADTIM1_RST_REG  PD_PER_SRST0_RSTREG
#define ADTIM2_RST_REG  PD_PER_SRST0_RSTREG
#define PWM_RST_REG     PD_PER_SRST0_RSTREG
#define CAP_RST_REG     PD_PER_SRST0_RSTREG
#define I2C2_RST_REG    PD_PER_SRST0_RSTREG
#define I2C3_RST_REG    PD_PER_SRST0_RSTREG
#define I2C4_RST_REG    PD_PER_SRST0_RSTREG
#define I2C5_RST_REG    PD_PER_SRST0_RSTREG
#define I2C6_RST_REG    PD_PER_SRST0_RSTREG
#define I2C7_RST_REG    PD_PER_SRST0_RSTREG

#define I2C8_RST_REG  PD_PER_SRST1_RSTREG
#define I2C9_RST_REG  PD_PER_SRST1_RSTREG
#define I2C10_RST_REG PD_PER_SRST1_RSTREG
#define I2C11_RST_REG PD_PER_SRST1_RSTREG
#define I2C12_RST_REG PD_PER_SRST1_RSTREG
#define I2C13_RST_REG PD_PER_SRST1_RSTREG
#define I2C14_RST_REG PD_PER_SRST1_RSTREG
#define I2C15_RST_REG PD_PER_SRST1_RSTREG
#define I2C16_RST_REG PD_PER_SRST1_RSTREG
#define UART2_RST_REG PD_PER_SRST1_RSTREG
#define UART3_RST_REG PD_PER_SRST1_RSTREG
#define UART4_RST_REG PD_PER_SRST1_RSTREG
#define UART5_RST_REG PD_PER_SRST1_RSTREG
#define UART6_RST_REG PD_PER_SRST1_RSTREG
#define UART7_RST_REG PD_PER_SRST1_RSTREG
#define UART8_RST_REG PD_PER_SRST1_RSTREG

#define UART9_RST_REG  PD_PER_SRST2_RSTREG
#define UART10_RST_REG PD_PER_SRST2_RSTREG
#define UART11_RST_REG PD_PER_SRST2_RSTREG
#define UART12_RST_REG PD_PER_SRST2_RSTREG
#define SPI1_RST_REG   PD_PER_SRST2_RSTREG
#define SPI2_RST_REG   PD_PER_SRST2_RSTREG
#define ADC1_RST_REG   PD_PER_SRST2_RSTREG
#define ADC2_RST_REG   PD_PER_SRST2_RSTREG
#define EXTI1_RST_REG  PD_PER_SRST2_RSTREG
#define EXTI2_RST_REG  PD_PER_SRST2_RSTREG
#define EXTI3_RST_REG  PD_PER_SRST2_RSTREG
#define EXTI4_RST_REG  PD_PER_SRST2_RSTREG
#define MJTAG1_RST_REG PD_PER_SRST2_RSTREG
#define MJTAG2_RST_REG PD_PER_SRST2_RSTREG
#define MJTAG3_RST_REG PD_PER_SRST2_RSTREG
#define IWDT2_RST_REG  PD_PER_SRST2_RSTREG

#define I3C2_RST_REG  PD_PER_SRST3_RSTREG
#define I3C3_RST_REG  PD_PER_SRST3_RSTREG
#define I3C4_RST_REG  PD_PER_SRST3_RSTREG
#define I3C5_RST_REG  PD_PER_SRST3_RSTREG
#define I3C6_RST_REG  PD_PER_SRST3_RSTREG
#define I3C7_RST_REG  PD_PER_SRST3_RSTREG
#define I3C8_RST_REG  PD_PER_SRST3_RSTREG
#define I3C9_RST_REG  PD_PER_SRST3_RSTREG
#define I3C10_RST_REG PD_PER_SRST3_RSTREG
#define I3C11_RST_REG PD_PER_SRST3_RSTREG
#define I3C12_RST_REG PD_PER_SRST3_RSTREG
#define I3C13_RST_REG PD_PER_SRST3_RSTREG
#define I3C14_RST_REG PD_PER_SRST3_RSTREG
#define PECI1_RST_REG PD_PER_SRST3_RSTREG
#define PECI2_RST_REG PD_PER_SRST3_RSTREG
#define WWDT2_RST_REG PD_PER_SRST3_RSTREG

#define KSCAN_RST_REG      PD_PER_SRST4_RSTREG
#define PS2IF1_RST_REG     PD_PER_SRST4_RSTREG
#define PS2IF2_RST_REG     PD_PER_SRST4_RSTREG
#define OWM_RST_REG        PD_PER_SRST4_RSTREG
#define CEC_RST_REG        PD_PER_SRST4_RSTREG
#define PIS_RST_REG        PD_PER_SRST4_RSTREG
#define FILTER_RST_REG     PD_PER_SRST4_RSTREG
#define PDM_RST_REG        PD_PER_SRST4_RSTREG
#define PARAL_RST_REG      PD_PER_SRST4_RSTREG
#define SGPIO1_MST_RST_REG PD_PER_SRST4_RSTREG
#define SGPIO2_MST_RST_REG PD_PER_SRST4_RSTREG
#define SGPIO1_MON_RST_REG PD_PER_SRST4_RSTREG
#define SGPIO2_MON_RST_REG PD_PER_SRST4_RSTREG

#define SMB_FLT1_RST_REG PD_PER_SRST5_RSTREG
#define SMB_FLT2_RST_REG PD_PER_SRST5_RSTREG
#define SMB_FLT3_RST_REG PD_PER_SRST5_RSTREG
#define SMB_FLT4_RST_REG PD_PER_SRST5_RSTREG

#define CACHE1_RST_REG    PD_CPU_SRST0_RSTREG
#define IOPMP_RST_REG     PD_CPU_SRST0_RSTREG
#define QSPI1_RST_REG     PD_CPU_SRST0_RSTREG
#define SHA512_RST_REG    PD_CPU_SRST0_RSTREG
#define OTFAD_AES_RST_REG PD_CPU_SRST0_RSTREG

#define CALC_CRC_RST_REG  PD_CPU_SRST1_RSTREG
#define CALC_RST_REG      PD_CPU_SRST1_RSTREG
#define CRYPT_RST_REG     PD_CPU_SRST1_RSTREG
#define OTP_CTRL_RST_REG  PD_CPU_SRST1_RSTREG
#define CALC_SHA_RST_REG  PD_CPU_SRST1_RSTREG
#define CALC_SM4_RST_REG  PD_CPU_SRST1_RSTREG
#define OTBN_RST_REG      PD_CPU_SRST1_RSTREG
#define TPM_SPIS1_RST_REG PD_CPU_SRST1_RSTREG
#define TPM_SPIS2_RST_REG PD_CPU_SRST1_RSTREG
#define NIST_TRNG_RST_REG PD_CPU_SRST1_RSTREG

#define CACHE2_RST_REG PD_CPU_SRST0_RSTREG
#define QSPI2_RST_REG  PD_CPU_SRST0_RSTREG
#define USB1_RST_REG   PD_CPU_SRST0_RSTREG
#define USB2_RST_REG   PD_CPU_SRST0_RSTREG
#define DMAC1_RST_REG  PD_CPU_SRST0_RSTREG
#define DMAC2_RST_REG  PD_CPU_SRST0_RSTREG
#define ESPI1_RST_REG  PD_CPU_SRST0_RSTREG
#define ESPI2_RST_REG  PD_CPU_SRST0_RSTREG
#define LPC1_RST_REG   PD_CPU_SRST0_RSTREG
#define LPC2_RST_REG   PD_CPU_SRST0_RSTREG
#define FDCAN_RST_REG  PD_CPU_SRST0_RSTREG
#define PSRAM_RST_REG  PD_CPU_SRST0_RSTREG

#define SPI3_RST_REG     PD_CPU_SRST1_RSTREG
#define SPI4_RST_REG     PD_CPU_SRST1_RSTREG
#define SPIS1_RST_REG    PD_CPU_SRST1_RSTREG
#define SPIS2_RST_REG    PD_CPU_SRST1_RSTREG
#define SPI1_FLT_RST_REG PD_CPU_SRST1_RSTREG
#define SPI2_FLT_RST_REG PD_CPU_SRST1_RSTREG
#define SPI3_FLT_RST_REG PD_CPU_SRST1_RSTREG
#define SPI4_FLT_RST_REG PD_CPU_SRST1_RSTREG
#define ETH1_RST_REG     PD_CPU_SRST1_RSTREG
#define ETH2_RST_REG     PD_CPU_SRST1_RSTREG
#define EMMC1_RST_REG    PD_CPU_SRST1_RSTREG
#define EMMC2_RST_REG    PD_CPU_SRST1_RSTREG
#define LTPI_SCM_RST_REG PD_CPU_SRST1_RSTREG
#define LTPI_HPM_RST_REG PD_CPU_SRST1_RSTREG
#define LTPI_PHY_RST_REG PD_CPU_SRST1_RSTREG

#define I2C1_RST_SET_MASK       0x1
#define I2C1_RST_SET_POS        0
#define I2C1_RST_CLR_MASK       0x2
#define I2C1_RST_CLR_POS        1
#define I3C1_RST_SET_MASK       0x10
#define I3C1_RST_SET_POS        4
#define I3C1_RST_CLR_MASK       0x20
#define I3C1_RST_CLR_POS        5
#define UART1_RST_SET_MASK      0x100
#define UART1_RST_SET_POS       8
#define UART1_RST_CLR_MASK      0x200
#define UART1_RST_CLR_POS       9
#define IWDT1_RST_SET_MASK      0x1000
#define IWDT1_RST_SET_POS       12
#define IWDT1_RST_CLR_MASK      0x2000
#define IWDT1_RST_CLR_POS       13
#define WWDT1_RST_SET_MASK      0x4000
#define WWDT1_RST_SET_POS       14
#define WWDT1_RST_CLR_MASK      0x8000
#define WWDT1_RST_CLR_POS       15
#define TRNG_RST_SET_MASK       0x10000
#define TRNG_RST_SET_POS        16
#define TRNG_RST_CLR_MASK       0x20000
#define TRNG_RST_CLR_POS        17
#define BSTIM1_RST_SET_MASK     0x1
#define BSTIM1_RST_SET_POS      0
#define BSTIM1_RST_CLR_MASK     0x2
#define BSTIM1_RST_CLR_POS      1
#define BSTIM2_RST_SET_MASK     0x4
#define BSTIM2_RST_SET_POS      2
#define BSTIM2_RST_CLR_MASK     0x8
#define BSTIM2_RST_CLR_POS      3
#define GPTIMA1_RST_SET_MASK    0x10
#define GPTIMA1_RST_SET_POS     4
#define GPTIMA1_RST_CLR_MASK    0x20
#define GPTIMA1_RST_CLR_POS     5
#define GPTIMA2_RST_SET_MASK    0x40
#define GPTIMA2_RST_SET_POS     6
#define GPTIMA2_RST_CLR_MASK    0x80
#define GPTIMA2_RST_CLR_POS     7
#define GPTIMB1_RST_SET_MASK    0x100
#define GPTIMB1_RST_SET_POS     8
#define GPTIMB1_RST_CLR_MASK    0x200
#define GPTIMB1_RST_CLR_POS     9
#define GPTIMC1_RST_SET_MASK    0x400
#define GPTIMC1_RST_SET_POS     10
#define GPTIMC1_RST_CLR_MASK    0x800
#define GPTIMC1_RST_CLR_POS     11
#define ADTIM1_RST_SET_MASK     0x1000
#define ADTIM1_RST_SET_POS      12
#define ADTIM1_RST_CLR_MASK     0x2000
#define ADTIM1_RST_CLR_POS      13
#define ADTIM2_RST_SET_MASK     0x4000
#define ADTIM2_RST_SET_POS      14
#define ADTIM2_RST_CLR_MASK     0x8000
#define ADTIM2_RST_CLR_POS      15
#define PWM_RST_SET_MASK        0x10000
#define PWM_RST_SET_POS         16
#define PWM_RST_CLR_MASK        0x20000
#define PWM_RST_CLR_POS         17
#define CAP_RST_SET_MASK        0x40000
#define CAP_RST_SET_POS         18
#define CAP_RST_CLR_MASK        0x80000
#define CAP_RST_CLR_POS         19
#define I2C2_RST_SET_MASK       0x100000
#define I2C2_RST_SET_POS        20
#define I2C2_RST_CLR_MASK       0x200000
#define I2C2_RST_CLR_POS        21
#define I2C3_RST_SET_MASK       0x400000
#define I2C3_RST_SET_POS        22
#define I2C3_RST_CLR_MASK       0x800000
#define I2C3_RST_CLR_POS        23
#define I2C4_RST_SET_MASK       0x1000000
#define I2C4_RST_SET_POS        24
#define I2C4_RST_CLR_MASK       0x2000000
#define I2C4_RST_CLR_POS        25
#define I2C5_RST_SET_MASK       0x4000000
#define I2C5_RST_SET_POS        26
#define I2C5_RST_CLR_MASK       0x8000000
#define I2C5_RST_CLR_POS        27
#define I2C6_RST_SET_MASK       0x10000000
#define I2C6_RST_SET_POS        28
#define I2C6_RST_CLR_MASK       0x20000000
#define I2C6_RST_CLR_POS        29
#define I2C7_RST_SET_MASK       0x40000000
#define I2C7_RST_SET_POS        30
#define I2C7_RST_CLR_MASK       0x80000000
#define I2C7_RST_CLR_POS        31
#define I2C8_RST_SET_MASK       0x1
#define I2C8_RST_SET_POS        0
#define I2C8_RST_CLR_MASK       0x2
#define I2C8_RST_CLR_POS        1
#define I2C9_RST_SET_MASK       0x4
#define I2C9_RST_SET_POS        2
#define I2C9_RST_CLR_MASK       0x8
#define I2C9_RST_CLR_POS        3
#define I2C10_RST_SET_MASK      0x10
#define I2C10_RST_SET_POS       4
#define I2C10_RST_CLR_MASK      0x20
#define I2C10_RST_CLR_POS       5
#define I2C11_RST_SET_MASK      0x40
#define I2C11_RST_SET_POS       6
#define I2C11_RST_CLR_MASK      0x80
#define I2C11_RST_CLR_POS       7
#define I2C12_RST_SET_MASK      0x100
#define I2C12_RST_SET_POS       8
#define I2C12_RST_CLR_MASK      0x200
#define I2C12_RST_CLR_POS       9
#define I2C13_RST_SET_MASK      0x400
#define I2C13_RST_SET_POS       10
#define I2C13_RST_CLR_MASK      0x800
#define I2C13_RST_CLR_POS       11
#define I2C14_RST_SET_MASK      0x1000
#define I2C14_RST_SET_POS       12
#define I2C14_RST_CLR_MASK      0x2000
#define I2C14_RST_CLR_POS       13
#define I2C15_RST_SET_MASK      0x4000
#define I2C15_RST_SET_POS       14
#define I2C15_RST_CLR_MASK      0x8000
#define I2C15_RST_CLR_POS       15
#define I2C16_RST_SET_MASK      0x10000
#define I2C16_RST_SET_POS       16
#define I2C16_RST_CLR_MASK      0x20000
#define I2C16_RST_CLR_POS       17
#define UART2_RST_SET_MASK      0x40000
#define UART2_RST_SET_POS       18
#define UART2_RST_CLR_MASK      0x80000
#define UART2_RST_CLR_POS       19
#define UART3_RST_SET_MASK      0x100000
#define UART3_RST_SET_POS       20
#define UART3_RST_CLR_MASK      0x200000
#define UART3_RST_CLR_POS       21
#define UART4_RST_SET_MASK      0x400000
#define UART4_RST_SET_POS       22
#define UART4_RST_CLR_MASK      0x800000
#define UART4_RST_CLR_POS       23
#define UART5_RST_SET_MASK      0x1000000
#define UART5_RST_SET_POS       24
#define UART5_RST_CLR_MASK      0x2000000
#define UART5_RST_CLR_POS       25
#define UART6_RST_SET_MASK      0x4000000
#define UART6_RST_SET_POS       26
#define UART6_RST_CLR_MASK      0x8000000
#define UART6_RST_CLR_POS       27
#define UART7_RST_SET_MASK      0x10000000
#define UART7_RST_SET_POS       28
#define UART7_RST_CLR_MASK      0x20000000
#define UART7_RST_CLR_POS       29
#define UART8_RST_SET_MASK      0x40000000
#define UART8_RST_SET_POS       30
#define UART8_RST_CLR_MASK      0x80000000
#define UART8_RST_CLR_POS       31
#define UART9_RST_SET_MASK      0x1
#define UART9_RST_SET_POS       0
#define UART9_RST_CLR_MASK      0x2
#define UART9_RST_CLR_POS       1
#define UART10_RST_SET_MASK     0x4
#define UART10_RST_SET_POS      2
#define UART10_RST_CLR_MASK     0x8
#define UART10_RST_CLR_POS      3
#define UART11_RST_SET_MASK     0x10
#define UART11_RST_SET_POS      4
#define UART11_RST_CLR_MASK     0x20
#define UART11_RST_CLR_POS      5
#define UART12_RST_SET_MASK     0x40
#define UART12_RST_SET_POS      6
#define UART12_RST_CLR_MASK     0x80
#define UART12_RST_CLR_POS      7
#define SPI1_RST_SET_MASK       0x100
#define SPI1_RST_SET_POS        8
#define SPI1_RST_CLR_MASK       0x200
#define SPI1_RST_CLR_POS        9
#define SPI2_RST_SET_MASK       0x400
#define SPI2_RST_SET_POS        10
#define SPI2_RST_CLR_MASK       0x800
#define SPI2_RST_CLR_POS        11
#define ADC1_RST_SET_MASK       0x1000
#define ADC1_RST_SET_POS        12
#define ADC1_RST_CLR_MASK       0x2000
#define ADC1_RST_CLR_POS        13
#define ADC2_RST_SET_MASK       0x4000
#define ADC2_RST_SET_POS        14
#define ADC2_RST_CLR_MASK       0x8000
#define ADC2_RST_CLR_POS        15
#define EXTI1_RST_SET_MASK      0x10000
#define EXTI1_RST_SET_POS       16
#define EXTI1_RST_CLR_MASK      0x20000
#define EXTI1_RST_CLR_POS       17
#define EXTI2_RST_SET_MASK      0x40000
#define EXTI2_RST_SET_POS       18
#define EXTI2_RST_CLR_MASK      0x80000
#define EXTI2_RST_CLR_POS       19
#define EXTI3_RST_SET_MASK      0x100000
#define EXTI3_RST_SET_POS       20
#define EXTI3_RST_CLR_MASK      0x200000
#define EXTI3_RST_CLR_POS       21
#define EXTI4_RST_SET_MASK      0x400000
#define EXTI4_RST_SET_POS       22
#define EXTI4_RST_CLR_MASK      0x800000
#define EXTI4_RST_CLR_POS       23
#define MJTAG1_RST_SET_MASK     0x1000000
#define MJTAG1_RST_SET_POS      24
#define MJTAG1_RST_CLR_MASK     0x2000000
#define MJTAG1_RST_CLR_POS      25
#define MJTAG2_RST_SET_MASK     0x4000000
#define MJTAG2_RST_SET_POS      26
#define MJTAG2_RST_CLR_MASK     0x8000000
#define MJTAG2_RST_CLR_POS      27
#define MJTAG3_RST_SET_MASK     0x10000000
#define MJTAG3_RST_SET_POS      28
#define MJTAG3_RST_CLR_MASK     0x20000000
#define MJTAG3_RST_CLR_POS      29
#define IWDT2_RST_SET_MASK      0x40000000
#define IWDT2_RST_SET_POS       30
#define IWDT2_RST_CLR_MASK      0x80000000
#define IWDT2_RST_CLR_POS       31
#define I3C2_RST_SET_MASK       0x1
#define I3C2_RST_SET_POS        0
#define I3C2_RST_CLR_MASK       0x2
#define I3C2_RST_CLR_POS        1
#define I3C3_RST_SET_MASK       0x4
#define I3C3_RST_SET_POS        2
#define I3C3_RST_CLR_MASK       0x8
#define I3C3_RST_CLR_POS        3
#define I3C4_RST_SET_MASK       0x10
#define I3C4_RST_SET_POS        4
#define I3C4_RST_CLR_MASK       0x20
#define I3C4_RST_CLR_POS        5
#define I3C5_RST_SET_MASK       0x40
#define I3C5_RST_SET_POS        6
#define I3C5_RST_CLR_MASK       0x80
#define I3C5_RST_CLR_POS        7
#define I3C6_RST_SET_MASK       0x100
#define I3C6_RST_SET_POS        8
#define I3C6_RST_CLR_MASK       0x200
#define I3C6_RST_CLR_POS        9
#define I3C7_RST_SET_MASK       0x400
#define I3C7_RST_SET_POS        10
#define I3C7_RST_CLR_MASK       0x800
#define I3C7_RST_CLR_POS        11
#define I3C8_RST_SET_MASK       0x1000
#define I3C8_RST_SET_POS        12
#define I3C8_RST_CLR_MASK       0x2000
#define I3C8_RST_CLR_POS        13
#define I3C9_RST_SET_MASK       0x4000
#define I3C9_RST_SET_POS        14
#define I3C9_RST_CLR_MASK       0x8000
#define I3C9_RST_CLR_POS        15
#define I3C10_RST_SET_MASK      0x10000
#define I3C10_RST_SET_POS       16
#define I3C10_RST_CLR_MASK      0x20000
#define I3C10_RST_CLR_POS       17
#define I3C11_RST_SET_MASK      0x40000
#define I3C11_RST_SET_POS       18
#define I3C11_RST_CLR_MASK      0x80000
#define I3C11_RST_CLR_POS       19
#define I3C12_RST_SET_MASK      0x100000
#define I3C12_RST_SET_POS       20
#define I3C12_RST_CLR_MASK      0x200000
#define I3C12_RST_CLR_POS       21
#define I3C13_RST_SET_MASK      0x400000
#define I3C13_RST_SET_POS       22
#define I3C13_RST_CLR_MASK      0x800000
#define I3C13_RST_CLR_POS       23
#define I3C14_RST_SET_MASK      0x1000000
#define I3C14_RST_SET_POS       24
#define I3C14_RST_CLR_MASK      0x2000000
#define I3C14_RST_CLR_POS       25
#define PECI1_RST_SET_MASK      0x4000000
#define PECI1_RST_SET_POS       26
#define PECI1_RST_CLR_MASK      0x8000000
#define PECI1_RST_CLR_POS       27
#define PECI2_RST_SET_MASK      0x10000000
#define PECI2_RST_SET_POS       28
#define PECI2_RST_CLR_MASK      0x20000000
#define PECI2_RST_CLR_POS       29
#define WWDT2_RST_SET_MASK      0x40000000
#define WWDT2_RST_SET_POS       30
#define WWDT2_RST_CLR_MASK      0x80000000
#define WWDT2_RST_CLR_POS       31
#define KSCAN_RST_SET_MASK      0x1
#define KSCAN_RST_SET_POS       0
#define KSCAN_RST_CLR_MASK      0x2
#define KSCAN_RST_CLR_POS       1
#define PS2IF1_RST_SET_MASK     0x4
#define PS2IF1_RST_SET_POS      2
#define PS2IF1_RST_CLR_MASK     0x8
#define PS2IF1_RST_CLR_POS      3
#define PS2IF2_RST_SET_MASK     0x10
#define PS2IF2_RST_SET_POS      4
#define PS2IF2_RST_CLR_MASK     0x20
#define PS2IF2_RST_CLR_POS      5
#define OWM_RST_SET_MASK        0x40
#define OWM_RST_SET_POS         6
#define OWM_RST_CLR_MASK        0x80
#define OWM_RST_CLR_POS         7
#define CEC_RST_SET_MASK        0x100
#define CEC_RST_SET_POS         8
#define CEC_RST_CLR_MASK        0x200
#define CEC_RST_CLR_POS         9
#define PIS_RST_SET_MASK        0x400
#define PIS_RST_SET_POS         10
#define PIS_RST_CLR_MASK        0x800
#define PIS_RST_CLR_POS         11
#define FILTER_RST_SET_MASK     0x1000
#define FILTER_RST_SET_POS      12
#define FILTER_RST_CLR_MASK     0x2000
#define FILTER_RST_CLR_POS      13
#define PDM_RST_SET_MASK        0x4000
#define PDM_RST_SET_POS         14
#define PDM_RST_CLR_MASK        0x8000
#define PDM_RST_CLR_POS         15
#define PARAL_RST_SET_MASK      0x10000
#define PARAL_RST_SET_POS       16
#define PARAL_RST_CLR_MASK      0x20000
#define PARAL_RST_CLR_POS       17
#define SGPIO1_MST_RST_SET_MASK 0x40000
#define SGPIO1_MST_RST_SET_POS  18
#define SGPIO1_MST_RST_CLR_MASK 0x80000
#define SGPIO1_MST_RST_CLR_POS  19
#define SGPIO2_MST_RST_SET_MASK 0x100000
#define SGPIO2_MST_RST_SET_POS  20
#define SGPIO2_MST_RST_CLR_MASK 0x200000
#define SGPIO2_MST_RST_CLR_POS  21
#define SGPIO1_MON_RST_SET_MASK 0x400000
#define SGPIO1_MON_RST_SET_POS  22
#define SGPIO1_MON_RST_CLR_MASK 0x800000
#define SGPIO1_MON_RST_CLR_POS  23
#define SGPIO2_MON_RST_SET_MASK 0x1000000
#define SGPIO2_MON_RST_SET_POS  24
#define SGPIO2_MON_RST_CLR_MASK 0x2000000
#define SGPIO2_MON_RST_CLR_POS  25
#define SMB_FLT1_RST_SET_MASK   0x1
#define SMB_FLT1_RST_SET_POS    0
#define SMB_FLT1_RST_CLR_MASK   0x2
#define SMB_FLT1_RST_CLR_POS    1
#define SMB_FLT2_RST_SET_MASK   0x4
#define SMB_FLT2_RST_SET_POS    2
#define SMB_FLT2_RST_CLR_MASK   0x8
#define SMB_FLT2_RST_CLR_POS    3
#define SMB_FLT3_RST_SET_MASK   0x10
#define SMB_FLT3_RST_SET_POS    4
#define SMB_FLT3_RST_CLR_MASK   0x20
#define SMB_FLT3_RST_CLR_POS    5
#define SMB_FLT4_RST_SET_MASK   0x40
#define SMB_FLT4_RST_SET_POS    6
#define SMB_FLT4_RST_CLR_MASK   0x80
#define SMB_FLT4_RST_CLR_POS    7
#define CACHE1_RST_SET_MASK     0x4
#define CACHE1_RST_SET_POS      2
#define CACHE1_RST_CLR_MASK     0x8
#define CACHE1_RST_CLR_POS      3
#define IOPMP_RST_SET_MASK      0x10
#define IOPMP_RST_SET_POS       4
#define IOPMP_RST_CLR_MASK      0x20
#define IOPMP_RST_CLR_POS       5
#define QSPI1_RST_SET_MASK      0x40
#define QSPI1_RST_SET_POS       6
#define QSPI1_RST_CLR_MASK      0x80
#define QSPI1_RST_CLR_POS       7
#define SHA512_RST_SET_MASK     0x100
#define SHA512_RST_SET_POS      8
#define SHA512_RST_CLR_MASK     0x200
#define SHA512_RST_CLR_POS      9
#define OTFAD_AES_RST_SET_MASK  0x400
#define OTFAD_AES_RST_SET_POS   10
#define OTFAD_AES_RST_CLR_MASK  0x800
#define OTFAD_AES_RST_CLR_POS   11
#define CALC_CRC_RST_SET_MASK   0x1
#define CALC_CRC_RST_SET_POS    0
#define CALC_CRC_RST_CLR_MASK   0x2
#define CALC_CRC_RST_CLR_POS    1
#define CALC_RST_SET_MASK       0x4
#define CALC_RST_SET_POS        2
#define CALC_RST_CLR_MASK       0x8
#define CALC_RST_CLR_POS        3
#define CRYPT_RST_SET_MASK      0x10
#define CRYPT_RST_SET_POS       4
#define CRYPT_RST_CLR_MASK      0x20
#define CRYPT_RST_CLR_POS       5
#define OTP_CTRL_RST_SET_MASK   0x40
#define OTP_CTRL_RST_SET_POS    6
#define OTP_CTRL_RST_CLR_MASK   0x80
#define OTP_CTRL_RST_CLR_POS    7
#define CALC_SHA_RST_SET_MASK   0x100
#define CALC_SHA_RST_SET_POS    8
#define CALC_SHA_RST_CLR_MASK   0x200
#define CALC_SHA_RST_CLR_POS    9
#define CALC_SM4_RST_SET_MASK   0x400
#define CALC_SM4_RST_SET_POS    10
#define CALC_SM4_RST_CLR_MASK   0x800
#define CALC_SM4_RST_CLR_POS    11
#define OTBN_RST_SET_MASK       0x1000
#define OTBN_RST_SET_POS        12
#define OTBN_RST_CLR_MASK       0x2000
#define OTBN_RST_CLR_POS        13
#define TPM_SPIS1_RST_SET_MASK  0x4000
#define TPM_SPIS1_RST_SET_POS   14
#define TPM_SPIS1_RST_CLR_MASK  0x8000
#define TPM_SPIS1_RST_CLR_POS   15
#define TPM_SPIS2_RST_SET_MASK  0x10000
#define TPM_SPIS2_RST_SET_POS   16
#define TPM_SPIS2_RST_CLR_MASK  0x20000
#define TPM_SPIS2_RST_CLR_POS   17
#define NIST_TRNG_RST_SET_MASK  0x40000000
#define NIST_TRNG_RST_SET_POS   30
#define NIST_TRNG_RST_CLR_MASK  0x80000000
#define NIST_TRNG_RST_CLR_POS   31
#define CACHE2_RST_SET_MASK     0x10
#define CACHE2_RST_SET_POS      4
#define CACHE2_RST_CLR_MASK     0x20
#define CACHE2_RST_CLR_POS      5
#define QSPI2_RST_SET_MASK      0x100
#define QSPI2_RST_SET_POS       8
#define QSPI2_RST_CLR_MASK      0x200
#define QSPI2_RST_CLR_POS       9
#define USB1_RST_SET_MASK       0x400
#define USB1_RST_SET_POS        10
#define USB1_RST_CLR_MASK       0x800
#define USB1_RST_CLR_POS        11
#define USB2_RST_SET_MASK       0x1000
#define USB2_RST_SET_POS        12
#define USB2_RST_CLR_MASK       0x2000
#define USB2_RST_CLR_POS        13
#define DMAC1_RST_SET_MASK      0x4000
#define DMAC1_RST_SET_POS       14
#define DMAC1_RST_CLR_MASK      0x8000
#define DMAC1_RST_CLR_POS       15
#define DMAC2_RST_SET_MASK      0x10000
#define DMAC2_RST_SET_POS       16
#define DMAC2_RST_CLR_MASK      0x20000
#define DMAC2_RST_CLR_POS       17
#define ESPI1_RST_SET_MASK      0x40000
#define ESPI1_RST_SET_POS       18
#define ESPI1_RST_CLR_MASK      0x80000
#define ESPI1_RST_CLR_POS       19
#define ESPI2_RST_SET_MASK      0x100000
#define ESPI2_RST_SET_POS       20
#define ESPI2_RST_CLR_MASK      0x200000
#define ESPI2_RST_CLR_POS       21
#define LPC1_RST_SET_MASK       0x400000
#define LPC1_RST_SET_POS        22
#define LPC1_RST_CLR_MASK       0x800000
#define LPC1_RST_CLR_POS        23
#define LPC2_RST_SET_MASK       0x1000000
#define LPC2_RST_SET_POS        24
#define LPC2_RST_CLR_MASK       0x2000000
#define LPC2_RST_CLR_POS        25
#define FDCAN_RST_SET_MASK      0x4000000
#define FDCAN_RST_SET_POS       26
#define FDCAN_RST_CLR_MASK      0x8000000
#define FDCAN_RST_CLR_POS       27
#define PSRAM_RST_SET_MASK      0x10000000
#define PSRAM_RST_SET_POS       28
#define PSRAM_RST_CLR_MASK      0x20000000
#define PSRAM_RST_CLR_POS       29
#define SPI3_RST_SET_MASK       0x1
#define SPI3_RST_SET_POS        0
#define SPI3_RST_CLR_MASK       0x2
#define SPI3_RST_CLR_POS        1
#define SPI4_RST_SET_MASK       0x4
#define SPI4_RST_SET_POS        2
#define SPI4_RST_CLR_MASK       0x8
#define SPI4_RST_CLR_POS        3
#define SPIS1_RST_SET_MASK      0x10
#define SPIS1_RST_SET_POS       4
#define SPIS1_RST_CLR_MASK      0x20
#define SPIS1_RST_CLR_POS       5
#define SPIS2_RST_SET_MASK      0x40
#define SPIS2_RST_SET_POS       6
#define SPIS2_RST_CLR_MASK      0x80
#define SPIS2_RST_CLR_POS       7
#define SPI1_FLT_RST_SET_MASK   0x100
#define SPI1_FLT_RST_SET_POS    8
#define SPI1_FLT_RST_CLR_MASK   0x200
#define SPI1_FLT_RST_CLR_POS    9
#define SPI2_FLT_RST_SET_MASK   0x400
#define SPI2_FLT_RST_SET_POS    10
#define SPI2_FLT_RST_CLR_MASK   0x800
#define SPI2_FLT_RST_CLR_POS    11
#define SPI3_FLT_RST_SET_MASK   0x1000
#define SPI3_FLT_RST_SET_POS    12
#define SPI3_FLT_RST_CLR_MASK   0x2000
#define SPI3_FLT_RST_CLR_POS    13
#define SPI4_FLT_RST_SET_MASK   0x4000
#define SPI4_FLT_RST_SET_POS    14
#define SPI4_FLT_RST_CLR_MASK   0x8000
#define SPI4_FLT_RST_CLR_POS    15
#define ETH1_RST_SET_MASK       0x10000
#define ETH1_RST_SET_POS        16
#define ETH1_RST_CLR_MASK       0x20000
#define ETH1_RST_CLR_POS        17
#define ETH2_RST_SET_MASK       0x40000
#define ETH2_RST_SET_POS        18
#define ETH2_RST_CLR_MASK       0x80000
#define ETH2_RST_CLR_POS        19
#define EMMC1_RST_SET_MASK      0x100000
#define EMMC1_RST_SET_POS       20
#define EMMC1_RST_CLR_MASK      0x200000
#define EMMC1_RST_CLR_POS       21
#define EMMC2_RST_SET_MASK      0x400000
#define EMMC2_RST_SET_POS       22
#define EMMC2_RST_CLR_MASK      0x800000
#define EMMC2_RST_CLR_POS       23
#define LTPI_SCM_RST_SET_MASK   0x1000000
#define LTPI_SCM_RST_SET_POS    24
#define LTPI_SCM_RST_CLR_MASK   0x2000000
#define LTPI_SCM_RST_CLR_POS    25
#define LTPI_HPM_RST_SET_MASK   0x4000000
#define LTPI_HPM_RST_SET_POS    26
#define LTPI_HPM_RST_CLR_MASK   0x8000000
#define LTPI_HPM_RST_CLR_POS    27
#define LTPI_PHY_RST_SET_MASK   0x10000000
#define LTPI_PHY_RST_SET_POS    28
#define LTPI_PHY_RST_CLR_MASK   0x20000000
#define LTPI_PHY_RST_CLR_POS    29

#endif
