/*
 * Copyright (c) 2025 Linkedsemi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef LS_SOC_CLOCK_H_
#define LS_SOC_CLOCK_H_

#include <stdint.h>
#include "reg_base_addr.h"

#define GEN_CLOCK(FUNC)  FUNC##_CLK_BASE, FUNC##_CLK_REG, FUNC##_CLK_SET_POS, FUNC##_CLK_CLR_POS

#define TIM_CLOCK        GEN_CLOCK(TIM)
#define RTC_CLOCK        GEN_CLOCK(RTC)
#define WDT_CLOCK        GEN_CLOCK(WDT)
#define CACHE2_CLOCK     GEN_CLOCK(CACHE2)
#define QSPI2_CLOCK      GEN_CLOCK(QSPI2)
#define USB1_CLOCK       GEN_CLOCK(USB1)
#define USB2_CLOCK       GEN_CLOCK(USB2)
#define DMAC1_CLOCK      GEN_CLOCK(DMAC1)
#define DMAC2_CLOCK      GEN_CLOCK(DMAC2)
#define ESPI1_CLOCK      GEN_CLOCK(ESPI1)
#define ESPI2_CLOCK      GEN_CLOCK(ESPI2)
#define LPC1_CLOCK       GEN_CLOCK(LPC1)
#define LPC2_CLOCK       GEN_CLOCK(LPC2)
#define FDCAN_CLOCK      GEN_CLOCK(FDCAN)
#define PSRAM_CLOCK      GEN_CLOCK(PSRAM)
#define USB2_CTL_CLOCK   GEN_CLOCK(USB2_CTL)
#define SPI3_CLOCK       GEN_CLOCK(SPI3)
#define SPI4_CLOCK       GEN_CLOCK(SPI4)
#define SPIS1_CLOCK      GEN_CLOCK(SPIS1)
#define SPIS2_CLOCK      GEN_CLOCK(SPIS2)
#define SPI1_FLT_CLOCK   GEN_CLOCK(SPI1_FLT)
#define SPI2_FLT_CLOCK   GEN_CLOCK(SPI2_FLT)
#define SPI3_FLT_CLOCK   GEN_CLOCK(SPI3_FLT)
#define SPI4_FLT_CLOCK   GEN_CLOCK(SPI4_FLT)
#define ETH1_CLOCK       GEN_CLOCK(ETH1)
#define ETH2_CLOCK       GEN_CLOCK(ETH2)
#define EMMC1_CLOCK      GEN_CLOCK(EMMC1)
#define EMMC2_CLOCK      GEN_CLOCK(EMMC2)
#define LTPI_SCM_CLOCK   GEN_CLOCK(LTPI_SCM)
#define LTPI_HPM_CLOCK   GEN_CLOCK(LTPI_HPM)
#define LTPI_PHY_CLOCK   GEN_CLOCK(LTPI_PHY)
#define BSTIM1_CLOCK     GEN_CLOCK(BSTIM1)
#define BSTIM2_CLOCK     GEN_CLOCK(BSTIM2)
#define GPTIMA1_CLOCK    GEN_CLOCK(GPTIMA1)
#define GPTIMA2_CLOCK    GEN_CLOCK(GPTIMA2)
#define GPTIMB1_CLOCK    GEN_CLOCK(GPTIMB1)
#define GPTIMC1_CLOCK    GEN_CLOCK(GPTIMC1)
#define ADTIM1_CLOCK     GEN_CLOCK(ADTIM1)
#define ADTIM2_CLOCK     GEN_CLOCK(ADTIM2)
#define PWM_CLOCK        GEN_CLOCK(PWM)
#define CAP_CLOCK        GEN_CLOCK(CAP)
#define I2C2_CLOCK       GEN_CLOCK(I2C2)
#define I2C3_CLOCK       GEN_CLOCK(I2C3)
#define I2C4_CLOCK       GEN_CLOCK(I2C4)
#define I2C5_CLOCK       GEN_CLOCK(I2C5)
#define I2C6_CLOCK       GEN_CLOCK(I2C6)
#define I2C7_CLOCK       GEN_CLOCK(I2C7)
#define I2C8_CLOCK       GEN_CLOCK(I2C8)
#define I2C9_CLOCK       GEN_CLOCK(I2C9)
#define I2C10_CLOCK      GEN_CLOCK(I2C10)
#define I2C11_CLOCK      GEN_CLOCK(I2C11)
#define I2C12_CLOCK      GEN_CLOCK(I2C12)
#define I2C13_CLOCK      GEN_CLOCK(I2C13)
#define I2C14_CLOCK      GEN_CLOCK(I2C14)
#define I2C15_CLOCK      GEN_CLOCK(I2C15)
#define I2C16_CLOCK      GEN_CLOCK(I2C16)
#define UART2_CLOCK      GEN_CLOCK(UART2)
#define UART3_CLOCK      GEN_CLOCK(UART3)
#define UART4_CLOCK      GEN_CLOCK(UART4)
#define UART5_CLOCK      GEN_CLOCK(UART5)
#define UART6_CLOCK      GEN_CLOCK(UART6)
#define UART7_CLOCK      GEN_CLOCK(UART7)
#define UART8_CLOCK      GEN_CLOCK(UART8)
#define UART9_CLOCK      GEN_CLOCK(UART9)
#define UART10_CLOCK     GEN_CLOCK(UART10)
#define UART11_CLOCK     GEN_CLOCK(UART11)
#define UART12_CLOCK     GEN_CLOCK(UART12)
#define SPI1_CLOCK       GEN_CLOCK(SPI1)
#define SPI2_CLOCK       GEN_CLOCK(SPI2)
#define ADC1_CLOCK       GEN_CLOCK(ADC1)
#define ADC2_CLOCK       GEN_CLOCK(ADC2)
#define EXTI1_CLOCK      GEN_CLOCK(EXTI1)
#define EXTI2_CLOCK      GEN_CLOCK(EXTI2)
#define EXTI3_CLOCK      GEN_CLOCK(EXTI3)
#define EXTI4_CLOCK      GEN_CLOCK(EXTI4)
#define MJTAG1_CLOCK     GEN_CLOCK(MJTAG1)
#define MJTAG2_CLOCK     GEN_CLOCK(MJTAG2)
#define MJTAG3_CLOCK     GEN_CLOCK(MJTAG3)
#define IWDT2_CLOCK      GEN_CLOCK(IWDT2)
#define I3C2_CLOCK       GEN_CLOCK(I3C2)
#define I3C3_CLOCK       GEN_CLOCK(I3C3)
#define I3C4_CLOCK       GEN_CLOCK(I3C4)
#define I3C5_CLOCK       GEN_CLOCK(I3C5)
#define I3C6_CLOCK       GEN_CLOCK(I3C6)
#define I3C7_CLOCK       GEN_CLOCK(I3C7)
#define I3C8_CLOCK       GEN_CLOCK(I3C8)
#define I3C9_CLOCK       GEN_CLOCK(I3C9)
#define I3C10_CLOCK      GEN_CLOCK(I3C10)
#define I3C11_CLOCK      GEN_CLOCK(I3C11)
#define I3C12_CLOCK      GEN_CLOCK(I3C12)
#define I3C13_CLOCK      GEN_CLOCK(I3C13)
#define I3C14_CLOCK      GEN_CLOCK(I3C14)
#define PECI1_CLOCK      GEN_CLOCK(PECI1)
#define PECI2_CLOCK      GEN_CLOCK(PECI2)
#define WWDT2_CLOCK      GEN_CLOCK(WWDT2)
#define CPU_DBG_CLOCK    GEN_CLOCK(CPU_DBG)
#define CACHE1_CLOCK     GEN_CLOCK(CACHE1)
#define IOPMP_CLOCK      GEN_CLOCK(IOPMP)
#define QSPI1_CLOCK      GEN_CLOCK(QSPI1)
#define SHA512_CLOCK     GEN_CLOCK(SHA512)
#define CALC_CRC_CLOCK   GEN_CLOCK(CALC_CRC)
#define CALC_CLOCK       GEN_CLOCK(CALC)
#define CRYPT_CLOCK      GEN_CLOCK(CRYPT)
#define OTP_CTRL_CLOCK   GEN_CLOCK(OTP_CTRL)
#define CALC_SHA_CLOCK   GEN_CLOCK(CALC_SHA)
#define CALC_SM4_CLOCK   GEN_CLOCK(CALC_SM4)
#define OTBN_CLOCK       GEN_CLOCK(OTBN)
#define NIST_TRNG_CLOCK  GEN_CLOCK(NIST_TRNG)
#define I2C1_CLOCK       GEN_CLOCK(I2C1)
#define I3C1_CLOCK       GEN_CLOCK(I3C1)
#define UART1_CLOCK      GEN_CLOCK(UART1)
#define IWDT1_CLOCK      GEN_CLOCK(IWDT1)
#define WWDT1_CLOCK      GEN_CLOCK(WWDT1)
#define TRNG_CLOCK       GEN_CLOCK(TRNG)
#define TPM_SPIS1_CLOCK  GEN_CLOCK(TPM_SPIS1)
#define TPM_SPIS2_CLOCK  GEN_CLOCK(TPM_SPIS2)
#define KSCAN_CLOCK      GEN_CLOCK(KSCAN)
#define PS2IF1_CLOCK     GEN_CLOCK(PS2IF1)
#define PS2IF2_CLOCK     GEN_CLOCK(PS2IF2)
#define OWM_CLOCK        GEN_CLOCK(OWM)
#define CEC_CLOCK        GEN_CLOCK(CEC)
#define PIS_CLOCK        GEN_CLOCK(PIS)
#define FILTER_CLOCK     GEN_CLOCK(FILTER)
#define PDM_CLOCK        GEN_CLOCK(PDM)
#define PARAL_CLOCK      GEN_CLOCK(PARAL)
#define SGPIO1_MST_CLOCK GEN_CLOCK(SGPIO1_MST)
#define SGPIO2_MST_CLOCK GEN_CLOCK(SGPIO2_MST)
#define SGPIO1_MON_CLOCK GEN_CLOCK(SGPIO1_MON)
#define SGPIO2_MON_CLOCK GEN_CLOCK(SGPIO2_MON)
#define SMB_FLT1_CLOCK   GEN_CLOCK(SMB_FLT1)
#define SMB_FLT2_CLOCK   GEN_CLOCK(SMB_FLT2)
#define SMB_FLT3_CLOCK   GEN_CLOCK(SMB_FLT3)
#define SMB_FLT4_CLOCK   GEN_CLOCK(SMB_FLT4)

#define CLKG_SRST_CLK_REG    0x2c
#define PD_CPU_CLKG0_CLK_REG 0x10
#define PD_CPU_CLKG1_CLK_REG 0x14
#define PD_PER_CLKG0_CLK_REG 0x0
#define PD_PER_CLKG1_CLK_REG 0x4
#define PD_PER_CLKG2_CLK_REG 0x8
#define PD_PER_CLKG3_CLK_REG 0xc
#define PD_PER_CLKG4_CLK_REG 0x20
#define PD_PER_CLKG5_CLK_REG 0x24

#define sysc_app_cpu APP_SYSC_CPU_APP_ADDR
#define sysc_app_per APP_SYSC_APP_PER_ADDR
#define sysc_app_pmu APP_PMU_RG_APP_ADDR
#define sysc_sec_cpu SEC_SYSC_CPU_SEC_ADDR
#define sysc_sec_per SEC_SYSC_SEC_PER_ADDR
#define sysc_sec_pmu SEC_PMU_RG_SEC_ADDR

#define TIM_CLK_BASE        sysc_app_pmu
#define RTC_CLK_BASE        sysc_app_pmu
#define WDT_CLK_BASE        sysc_sec_pmu
#define CACHE2_CLK_BASE     sysc_app_cpu
#define QSPI2_CLK_BASE      sysc_app_cpu
#define USB1_CLK_BASE       sysc_app_cpu
#define USB2_CLK_BASE       sysc_app_cpu
#define DMAC1_CLK_BASE      sysc_app_cpu
#define DMAC2_CLK_BASE      sysc_app_cpu
#define ESPI1_CLK_BASE      sysc_app_cpu
#define ESPI2_CLK_BASE      sysc_app_cpu
#define LPC1_CLK_BASE       sysc_app_cpu
#define LPC2_CLK_BASE       sysc_app_cpu
#define FDCAN_CLK_BASE      sysc_app_cpu
#define PSRAM_CLK_BASE      sysc_app_cpu
#define USB2_CTL_CLK_BASE   sysc_app_cpu
#define SPI3_CLK_BASE       sysc_app_cpu
#define SPI4_CLK_BASE       sysc_app_cpu
#define SPIS1_CLK_BASE      sysc_app_cpu
#define SPIS2_CLK_BASE      sysc_app_cpu
#define SPI1_FLT_CLK_BASE   sysc_app_cpu
#define SPI2_FLT_CLK_BASE   sysc_app_cpu
#define SPI3_FLT_CLK_BASE   sysc_app_cpu
#define SPI4_FLT_CLK_BASE   sysc_app_cpu
#define ETH1_CLK_BASE       sysc_app_cpu
#define ETH2_CLK_BASE       sysc_app_cpu
#define EMMC1_CLK_BASE      sysc_app_cpu
#define EMMC2_CLK_BASE      sysc_app_cpu
#define LTPI_SCM_CLK_BASE   sysc_app_cpu
#define LTPI_HPM_CLK_BASE   sysc_app_cpu
#define LTPI_PHY_CLK_BASE   sysc_app_cpu
#define BSTIM1_CLK_BASE     sysc_app_per
#define BSTIM2_CLK_BASE     sysc_app_per
#define GPTIMA1_CLK_BASE    sysc_app_per
#define GPTIMA2_CLK_BASE    sysc_app_per
#define GPTIMB1_CLK_BASE    sysc_app_per
#define GPTIMC1_CLK_BASE    sysc_app_per
#define ADTIM1_CLK_BASE     sysc_app_per
#define ADTIM2_CLK_BASE     sysc_app_per
#define PWM_CLK_BASE        sysc_app_per
#define CAP_CLK_BASE        sysc_app_per
#define I2C2_CLK_BASE       sysc_app_per
#define I2C3_CLK_BASE       sysc_app_per
#define I2C4_CLK_BASE       sysc_app_per
#define I2C5_CLK_BASE       sysc_app_per
#define I2C6_CLK_BASE       sysc_app_per
#define I2C7_CLK_BASE       sysc_app_per
#define I2C8_CLK_BASE       sysc_app_per
#define I2C9_CLK_BASE       sysc_app_per
#define I2C10_CLK_BASE      sysc_app_per
#define I2C11_CLK_BASE      sysc_app_per
#define I2C12_CLK_BASE      sysc_app_per
#define I2C13_CLK_BASE      sysc_app_per
#define I2C14_CLK_BASE      sysc_app_per
#define I2C15_CLK_BASE      sysc_app_per
#define I2C16_CLK_BASE      sysc_app_per
#define UART2_CLK_BASE      sysc_app_per
#define UART3_CLK_BASE      sysc_app_per
#define UART4_CLK_BASE      sysc_app_per
#define UART5_CLK_BASE      sysc_app_per
#define UART6_CLK_BASE      sysc_app_per
#define UART7_CLK_BASE      sysc_app_per
#define UART8_CLK_BASE      sysc_app_per
#define UART9_CLK_BASE      sysc_app_per
#define UART10_CLK_BASE     sysc_app_per
#define UART11_CLK_BASE     sysc_app_per
#define UART12_CLK_BASE     sysc_app_per
#define SPI1_CLK_BASE       sysc_app_per
#define SPI2_CLK_BASE       sysc_app_per
#define ADC1_CLK_BASE       sysc_app_per
#define ADC2_CLK_BASE       sysc_app_per
#define EXTI1_CLK_BASE      sysc_app_per
#define EXTI2_CLK_BASE      sysc_app_per
#define EXTI3_CLK_BASE      sysc_app_per
#define EXTI4_CLK_BASE      sysc_app_per
#define MJTAG1_CLK_BASE     sysc_app_per
#define MJTAG2_CLK_BASE     sysc_app_per
#define MJTAG3_CLK_BASE     sysc_app_per
#define IWDT2_CLK_BASE      sysc_app_per
#define I3C2_CLK_BASE       sysc_app_per
#define I3C3_CLK_BASE       sysc_app_per
#define I3C4_CLK_BASE       sysc_app_per
#define I3C5_CLK_BASE       sysc_app_per
#define I3C6_CLK_BASE       sysc_app_per
#define I3C7_CLK_BASE       sysc_app_per
#define I3C8_CLK_BASE       sysc_app_per
#define I3C9_CLK_BASE       sysc_app_per
#define I3C10_CLK_BASE      sysc_app_per
#define I3C11_CLK_BASE      sysc_app_per
#define I3C12_CLK_BASE      sysc_app_per
#define I3C13_CLK_BASE      sysc_app_per
#define I3C14_CLK_BASE      sysc_app_per
#define PECI1_CLK_BASE      sysc_app_per
#define PECI2_CLK_BASE      sysc_app_per
#define WWDT2_CLK_BASE      sysc_app_per
#define CPU_DBG_CLK_BASE    sysc_sec_cpu
#define CACHE1_CLK_BASE     sysc_sec_cpu
#define IOPMP_CLK_BASE      sysc_sec_cpu
#define QSPI1_CLK_BASE      sysc_sec_cpu
#define SHA512_CLK_BASE     sysc_sec_cpu
#define CALC_CRC_CLK_BASE   sysc_sec_cpu
#define CALC_CLK_BASE       sysc_sec_cpu
#define CRYPT_CLK_BASE      sysc_sec_cpu
#define OTP_CTRL_CLK_BASE   sysc_sec_cpu
#define CALC_SHA_CLK_BASE   sysc_sec_cpu
#define CALC_SM4_CLK_BASE   sysc_sec_cpu
#define OTBN_CLK_BASE       sysc_sec_cpu
#define TPM_SPIS1_CLK_BASE  sysc_sec_cpu
#define TPM_SPIS2_CLK_BASE  sysc_sec_cpu
#define NIST_TRNG_CLK_BASE  sysc_sec_cpu
#define I2C1_CLK_BASE       sysc_sec_per
#define I3C1_CLK_BASE       sysc_sec_per
#define UART1_CLK_BASE      sysc_sec_per
#define IWDT1_CLK_BASE      sysc_sec_per
#define WWDT1_CLK_BASE      sysc_sec_per
#define TRNG_CLK_BASE       sysc_sec_per
#define KSCAN_CLK_BASE      sysc_app_per
#define PS2IF1_CLK_BASE     sysc_app_per
#define PS2IF2_CLK_BASE     sysc_app_per
#define OWM_CLK_BASE        sysc_app_per
#define CEC_CLK_BASE        sysc_app_per
#define PIS_CLK_BASE        sysc_app_per
#define FILTER_CLK_BASE     sysc_app_per
#define PDM_CLK_BASE        sysc_app_per
#define PARAL_CLK_BASE      sysc_app_per
#define SGPIO1_MST_CLK_BASE sysc_app_per
#define SGPIO2_MST_CLK_BASE sysc_app_per
#define SGPIO1_MON_CLK_BASE sysc_app_per
#define SGPIO2_MON_CLK_BASE sysc_app_per
#define SMB_FLT1_CLK_BASE   sysc_app_per
#define SMB_FLT2_CLK_BASE   sysc_app_per
#define SMB_FLT3_CLK_BASE   sysc_app_per
#define SMB_FLT4_CLK_BASE   sysc_app_per

#define TIM_CLK_REG        CLKG_SRST_CLK_REG
#define RTC_CLK_REG        CLKG_SRST_CLK_REG
#define WDT_CLK_REG        CLKG_SRST_CLK_REG
#define CACHE2_CLK_REG     PD_CPU_CLKG0_CLK_REG
#define QSPI2_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define USB1_CLK_REG       PD_CPU_CLKG0_CLK_REG
#define USB2_CLK_REG       PD_CPU_CLKG0_CLK_REG
#define DMAC1_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define DMAC2_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define ESPI1_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define ESPI2_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define LPC1_CLK_REG       PD_CPU_CLKG0_CLK_REG
#define LPC2_CLK_REG       PD_CPU_CLKG0_CLK_REG
#define FDCAN_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define PSRAM_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define USB2_CTL_CLK_REG   PD_CPU_CLKG0_CLK_REG
#define SPI3_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define SPI4_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define SPIS1_CLK_REG      PD_CPU_CLKG1_CLK_REG
#define SPIS2_CLK_REG      PD_CPU_CLKG1_CLK_REG
#define SPI1_FLT_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define SPI2_FLT_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define SPI3_FLT_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define SPI4_FLT_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define ETH1_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define ETH2_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define EMMC1_CLK_REG      PD_CPU_CLKG1_CLK_REG
#define EMMC2_CLK_REG      PD_CPU_CLKG1_CLK_REG
#define LTPI_SCM_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define LTPI_HPM_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define LTPI_PHY_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define BSTIM1_CLK_REG     PD_PER_CLKG0_CLK_REG
#define BSTIM2_CLK_REG     PD_PER_CLKG0_CLK_REG
#define GPTIMA1_CLK_REG    PD_PER_CLKG0_CLK_REG
#define GPTIMA2_CLK_REG    PD_PER_CLKG0_CLK_REG
#define GPTIMB1_CLK_REG    PD_PER_CLKG0_CLK_REG
#define GPTIMC1_CLK_REG    PD_PER_CLKG0_CLK_REG
#define ADTIM1_CLK_REG     PD_PER_CLKG0_CLK_REG
#define ADTIM2_CLK_REG     PD_PER_CLKG0_CLK_REG
#define PWM_CLK_REG        PD_PER_CLKG0_CLK_REG
#define CAP_CLK_REG        PD_PER_CLKG0_CLK_REG
#define I2C2_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C3_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C4_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C5_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C6_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C7_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I2C8_CLK_REG       PD_PER_CLKG1_CLK_REG
#define I2C9_CLK_REG       PD_PER_CLKG1_CLK_REG
#define I2C10_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C11_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C12_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C13_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C14_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C15_CLK_REG      PD_PER_CLKG1_CLK_REG
#define I2C16_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART2_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART3_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART4_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART5_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART6_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART7_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART8_CLK_REG      PD_PER_CLKG1_CLK_REG
#define UART9_CLK_REG      PD_PER_CLKG2_CLK_REG
#define UART10_CLK_REG     PD_PER_CLKG2_CLK_REG
#define UART11_CLK_REG     PD_PER_CLKG2_CLK_REG
#define UART12_CLK_REG     PD_PER_CLKG2_CLK_REG
#define SPI1_CLK_REG       PD_PER_CLKG2_CLK_REG
#define SPI2_CLK_REG       PD_PER_CLKG2_CLK_REG
#define ADC1_CLK_REG       PD_PER_CLKG2_CLK_REG
#define ADC2_CLK_REG       PD_PER_CLKG2_CLK_REG
#define EXTI1_CLK_REG      PD_PER_CLKG2_CLK_REG
#define EXTI2_CLK_REG      PD_PER_CLKG2_CLK_REG
#define EXTI3_CLK_REG      PD_PER_CLKG2_CLK_REG
#define EXTI4_CLK_REG      PD_PER_CLKG2_CLK_REG
#define MJTAG1_CLK_REG     PD_PER_CLKG2_CLK_REG
#define MJTAG2_CLK_REG     PD_PER_CLKG2_CLK_REG
#define MJTAG3_CLK_REG     PD_PER_CLKG2_CLK_REG
#define IWDT2_CLK_REG      PD_PER_CLKG2_CLK_REG
#define I3C2_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C3_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C4_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C5_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C6_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C7_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C8_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C9_CLK_REG       PD_PER_CLKG3_CLK_REG
#define I3C10_CLK_REG      PD_PER_CLKG3_CLK_REG
#define I3C11_CLK_REG      PD_PER_CLKG3_CLK_REG
#define I3C12_CLK_REG      PD_PER_CLKG3_CLK_REG
#define I3C13_CLK_REG      PD_PER_CLKG3_CLK_REG
#define I3C14_CLK_REG      PD_PER_CLKG3_CLK_REG
#define PECI1_CLK_REG      PD_PER_CLKG3_CLK_REG
#define PECI2_CLK_REG      PD_PER_CLKG3_CLK_REG
#define WWDT2_CLK_REG      PD_PER_CLKG3_CLK_REG
#define CPU_DBG_CLK_REG    PD_CPU_CLKG0_CLK_REG
#define CACHE1_CLK_REG     PD_CPU_CLKG0_CLK_REG
#define IOPMP_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define QSPI1_CLK_REG      PD_CPU_CLKG0_CLK_REG
#define SHA512_CLK_REG     PD_CPU_CLKG0_CLK_REG
#define CALC_CRC_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define CALC_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define CRYPT_CLK_REG      PD_CPU_CLKG1_CLK_REG
#define OTP_CTRL_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define CALC_SHA_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define CALC_SM4_CLK_REG   PD_CPU_CLKG1_CLK_REG
#define OTBN_CLK_REG       PD_CPU_CLKG1_CLK_REG
#define TPM_SPIS1_CLK_REG  PD_CPU_CLKG1_CLK_REG
#define TPM_SPIS2_CLK_REG  PD_CPU_CLKG1_CLK_REG
#define NIST_TRNG_CLK_REG  PD_CPU_CLKG1_CLK_REG
#define I2C1_CLK_REG       PD_PER_CLKG0_CLK_REG
#define I3C1_CLK_REG       PD_PER_CLKG0_CLK_REG
#define UART1_CLK_REG      PD_PER_CLKG0_CLK_REG
#define IWDT1_CLK_REG      PD_PER_CLKG0_CLK_REG
#define WWDT1_CLK_REG      PD_PER_CLKG0_CLK_REG
#define TRNG_CLK_REG       PD_PER_CLKG0_CLK_REG
#define KSCAN_CLK_REG      PD_PER_CLKG4_CLK_REG
#define PS2IF1_CLK_REG     PD_PER_CLKG4_CLK_REG
#define PS2IF2_CLK_REG     PD_PER_CLKG4_CLK_REG
#define OWM_CLK_REG        PD_PER_CLKG4_CLK_REG
#define CEC_CLK_REG        PD_PER_CLKG4_CLK_REG
#define PIS_CLK_REG        PD_PER_CLKG4_CLK_REG
#define FILTER_CLK_REG     PD_PER_CLKG4_CLK_REG
#define PDM_CLK_REG        PD_PER_CLKG4_CLK_REG
#define PARAL_CLK_REG      PD_PER_CLKG4_CLK_REG
#define SGPIO1_MST_CLK_REG PD_PER_CLKG4_CLK_REG
#define SGPIO2_MST_CLK_REG PD_PER_CLKG4_CLK_REG
#define SGPIO1_MON_CLK_REG PD_PER_CLKG4_CLK_REG
#define SGPIO2_MON_CLK_REG PD_PER_CLKG4_CLK_REG
#define SMB_FLT1_CLK_REG   PD_PER_CLKG5_CLK_REG
#define SMB_FLT2_CLK_REG   PD_PER_CLKG5_CLK_REG
#define SMB_FLT3_CLK_REG   PD_PER_CLKG5_CLK_REG
#define SMB_FLT4_CLK_REG   PD_PER_CLKG5_CLK_REG

#define TIM_CLK_SET_MASK       0x1
#define TIM_CLK_SET_POS        0
#define TIM_CLK_CLR_MASK       0x2
#define TIM_CLK_CLR_POS        1
#define RTC_CLK_SET_MASK       0x10
#define RTC_CLK_SET_POS        4
#define RTC_CLK_CLR_MASK       0x20
#define RTC_CLK_CLR_POS        5
#define WDT_CLK_SET_MASK       0x4
#define WDT_CLK_SET_POS        2
#define WDT_CLK_CLR_MASK       0x8
#define WDT_CLK_CLR_POS        3
#define CACHE2_CLK_SET_MASK    0x10
#define CACHE2_CLK_SET_POS     4
#define CACHE2_CLK_CLR_MASK    0x20
#define CACHE2_CLK_CLR_POS     5
#define QSPI2_CLK_SET_MASK     0x100
#define QSPI2_CLK_SET_POS      8
#define QSPI2_CLK_CLR_MASK     0x200
#define QSPI2_CLK_CLR_POS      9
#define USB1_CLK_SET_MASK      0x400
#define USB1_CLK_SET_POS       10
#define USB1_CLK_CLR_MASK      0x800
#define USB1_CLK_CLR_POS       11
#define USB2_CLK_SET_MASK      0x1000
#define USB2_CLK_SET_POS       12
#define USB2_CLK_CLR_MASK      0x2000
#define USB2_CLK_CLR_POS       13
#define DMAC1_CLK_SET_MASK     0x4000
#define DMAC1_CLK_SET_POS      14
#define DMAC1_CLK_CLR_MASK     0x8000
#define DMAC1_CLK_CLR_POS      15
#define DMAC2_CLK_SET_MASK     0x10000
#define DMAC2_CLK_SET_POS      16
#define DMAC2_CLK_CLR_MASK     0x20000
#define DMAC2_CLK_CLR_POS      17
#define ESPI1_CLK_SET_MASK     0x40000
#define ESPI1_CLK_SET_POS      18
#define ESPI1_CLK_CLR_MASK     0x80000
#define ESPI1_CLK_CLR_POS      19
#define ESPI2_CLK_SET_MASK     0x100000
#define ESPI2_CLK_SET_POS      20
#define ESPI2_CLK_CLR_MASK     0x200000
#define ESPI2_CLK_CLR_POS      21
#define LPC1_CLK_SET_MASK      0x400000
#define LPC1_CLK_SET_POS       22
#define LPC1_CLK_CLR_MASK      0x800000
#define LPC1_CLK_CLR_POS       23
#define LPC2_CLK_SET_MASK      0x1000000
#define LPC2_CLK_SET_POS       24
#define LPC2_CLK_CLR_MASK      0x2000000
#define LPC2_CLK_CLR_POS       25
#define FDCAN_CLK_SET_MASK     0x4000000
#define FDCAN_CLK_SET_POS      26
#define FDCAN_CLK_CLR_MASK     0x8000000
#define FDCAN_CLK_CLR_POS      27
#define PSRAM_CLK_SET_MASK     0x10000000
#define PSRAM_CLK_SET_POS      28
#define PSRAM_CLK_CLR_MASK     0x20000000
#define PSRAM_CLK_CLR_POS      29
#define USB2_CTL_CLK_SET_MASK  0x40000000
#define USB2_CTL_CLK_SET_POS   30
#define USB2_CTL_CLK_CLR_MASK  0x80000000
#define USB2_CTL_CLK_CLR_POS   31
#define SPI3_CLK_SET_MASK      0x1
#define SPI3_CLK_SET_POS       0
#define SPI3_CLK_CLR_MASK      0x2
#define SPI3_CLK_CLR_POS       1
#define SPI4_CLK_SET_MASK      0x4
#define SPI4_CLK_SET_POS       2
#define SPI4_CLK_CLR_MASK      0x8
#define SPI4_CLK_CLR_POS       3
#define SPIS1_CLK_SET_MASK     0x10
#define SPIS1_CLK_SET_POS      4
#define SPIS1_CLK_CLR_MASK     0x20
#define SPIS1_CLK_CLR_POS      5
#define SPIS2_CLK_SET_MASK     0x40
#define SPIS2_CLK_SET_POS      6
#define SPIS2_CLK_CLR_MASK     0x80
#define SPIS2_CLK_CLR_POS      7
#define SPI1_FLT_CLK_SET_MASK  0x100
#define SPI1_FLT_CLK_SET_POS   8
#define SPI1_FLT_CLK_CLR_MASK  0x200
#define SPI1_FLT_CLK_CLR_POS   9
#define SPI2_FLT_CLK_SET_MASK  0x400
#define SPI2_FLT_CLK_SET_POS   10
#define SPI2_FLT_CLK_CLR_MASK  0x800
#define SPI2_FLT_CLK_CLR_POS   11
#define SPI3_FLT_CLK_SET_MASK  0x1000
#define SPI3_FLT_CLK_SET_POS   12
#define SPI3_FLT_CLK_CLR_MASK  0x2000
#define SPI3_FLT_CLK_CLR_POS   13
#define SPI4_FLT_CLK_SET_MASK  0x4000
#define SPI4_FLT_CLK_SET_POS   14
#define SPI4_FLT_CLK_CLR_MASK  0x8000
#define SPI4_FLT_CLK_CLR_POS   15
#define ETH1_CLK_SET_MASK      0x10000
#define ETH1_CLK_SET_POS       16
#define ETH1_CLK_CLR_MASK      0x20000
#define ETH1_CLK_CLR_POS       17
#define ETH2_CLK_SET_MASK      0x40000
#define ETH2_CLK_SET_POS       18
#define ETH2_CLK_CLR_MASK      0x80000
#define ETH2_CLK_CLR_POS       19
#define EMMC1_CLK_SET_MASK     0x100000
#define EMMC1_CLK_SET_POS      20
#define EMMC1_CLK_CLR_MASK     0x200000
#define EMMC1_CLK_CLR_POS      21
#define EMMC2_CLK_SET_MASK     0x400000
#define EMMC2_CLK_SET_POS      22
#define EMMC2_CLK_CLR_MASK     0x800000
#define EMMC2_CLK_CLR_POS      23
#define LTPI_SCM_CLK_SET_MASK  0x1000000
#define LTPI_SCM_CLK_SET_POS   24
#define LTPI_SCM_CLK_CLR_MASK  0x2000000
#define LTPI_SCM_CLK_CLR_POS   25
#define LTPI_HPM_CLK_SET_MASK  0x4000000
#define LTPI_HPM_CLK_SET_POS   26
#define LTPI_HPM_CLK_CLR_MASK  0x8000000
#define LTPI_HPM_CLK_CLR_POS   27
#define LTPI_PHY_CLK_SET_MASK  0x10000000
#define LTPI_PHY_CLK_SET_POS   28
#define LTPI_PHY_CLK_CLR_MASK  0x20000000
#define LTPI_PHY_CLK_CLR_POS   29
#define BSTIM1_CLK_SET_MASK    0x1
#define BSTIM1_CLK_SET_POS     0
#define BSTIM1_CLK_CLR_MASK    0x2
#define BSTIM1_CLK_CLR_POS     1
#define BSTIM2_CLK_SET_MASK    0x4
#define BSTIM2_CLK_SET_POS     2
#define BSTIM2_CLK_CLR_MASK    0x8
#define BSTIM2_CLK_CLR_POS     3
#define GPTIMA1_CLK_SET_MASK   0x10
#define GPTIMA1_CLK_SET_POS    4
#define GPTIMA1_CLK_CLR_MASK   0x20
#define GPTIMA1_CLK_CLR_POS    5
#define GPTIMA2_CLK_SET_MASK   0x40
#define GPTIMA2_CLK_SET_POS    6
#define GPTIMA2_CLK_CLR_MASK   0x80
#define GPTIMA2_CLK_CLR_POS    7
#define GPTIMB1_CLK_SET_MASK   0x100
#define GPTIMB1_CLK_SET_POS    8
#define GPTIMB1_CLK_CLR_MASK   0x200
#define GPTIMB1_CLK_CLR_POS    9
#define GPTIMC1_CLK_SET_MASK   0x400
#define GPTIMC1_CLK_SET_POS    10
#define GPTIMC1_CLK_CLR_MASK   0x800
#define GPTIMC1_CLK_CLR_POS    11
#define ADTIM1_CLK_SET_MASK    0x1000
#define ADTIM1_CLK_SET_POS     12
#define ADTIM1_CLK_CLR_MASK    0x2000
#define ADTIM1_CLK_CLR_POS     13
#define ADTIM2_CLK_SET_MASK    0x4000
#define ADTIM2_CLK_SET_POS     14
#define ADTIM2_CLK_CLR_MASK    0x8000
#define ADTIM2_CLK_CLR_POS     15
#define PWM_CLK_SET_MASK       0x10000
#define PWM_CLK_SET_POS        16
#define PWM_CLK_CLR_MASK       0x20000
#define PWM_CLK_CLR_POS        17
#define CAP_CLK_SET_MASK       0x40000
#define CAP_CLK_SET_POS        18
#define CAP_CLK_CLR_MASK       0x80000
#define CAP_CLK_CLR_POS        19
#define I2C2_CLK_SET_MASK      0x100000
#define I2C2_CLK_SET_POS       20
#define I2C2_CLK_CLR_MASK      0x200000
#define I2C2_CLK_CLR_POS       21
#define I2C3_CLK_SET_MASK      0x400000
#define I2C3_CLK_SET_POS       22
#define I2C3_CLK_CLR_MASK      0x800000
#define I2C3_CLK_CLR_POS       23
#define I2C4_CLK_SET_MASK      0x1000000
#define I2C4_CLK_SET_POS       24
#define I2C4_CLK_CLR_MASK      0x2000000
#define I2C4_CLK_CLR_POS       25
#define I2C5_CLK_SET_MASK      0x4000000
#define I2C5_CLK_SET_POS       26
#define I2C5_CLK_CLR_MASK      0x8000000
#define I2C5_CLK_CLR_POS       27
#define I2C6_CLK_SET_MASK      0x10000000
#define I2C6_CLK_SET_POS       28
#define I2C6_CLK_CLR_MASK      0x20000000
#define I2C6_CLK_CLR_POS       29
#define I2C7_CLK_SET_MASK      0x40000000
#define I2C7_CLK_SET_POS       30
#define I2C7_CLK_CLR_MASK      0x80000000
#define I2C7_CLK_CLR_POS       31
#define I2C8_CLK_SET_MASK      0x1
#define I2C8_CLK_SET_POS       0
#define I2C8_CLK_CLR_MASK      0x2
#define I2C8_CLK_CLR_POS       1
#define I2C9_CLK_SET_MASK      0x4
#define I2C9_CLK_SET_POS       2
#define I2C9_CLK_CLR_MASK      0x8
#define I2C9_CLK_CLR_POS       3
#define I2C10_CLK_SET_MASK     0x10
#define I2C10_CLK_SET_POS      4
#define I2C10_CLK_CLR_MASK     0x20
#define I2C10_CLK_CLR_POS      5
#define I2C11_CLK_SET_MASK     0x40
#define I2C11_CLK_SET_POS      6
#define I2C11_CLK_CLR_MASK     0x80
#define I2C11_CLK_CLR_POS      7
#define I2C12_CLK_SET_MASK     0x100
#define I2C12_CLK_SET_POS      8
#define I2C12_CLK_CLR_MASK     0x200
#define I2C12_CLK_CLR_POS      9
#define I2C13_CLK_SET_MASK     0x400
#define I2C13_CLK_SET_POS      10
#define I2C13_CLK_CLR_MASK     0x800
#define I2C13_CLK_CLR_POS      11
#define I2C14_CLK_SET_MASK     0x1000
#define I2C14_CLK_SET_POS      12
#define I2C14_CLK_CLR_MASK     0x2000
#define I2C14_CLK_CLR_POS      13
#define I2C15_CLK_SET_MASK     0x4000
#define I2C15_CLK_SET_POS      14
#define I2C15_CLK_CLR_MASK     0x8000
#define I2C15_CLK_CLR_POS      15
#define I2C16_CLK_SET_MASK     0x10000
#define I2C16_CLK_SET_POS      16
#define I2C16_CLK_CLR_MASK     0x20000
#define I2C16_CLK_CLR_POS      17
#define UART2_CLK_SET_MASK     0x40000
#define UART2_CLK_SET_POS      18
#define UART2_CLK_CLR_MASK     0x80000
#define UART2_CLK_CLR_POS      19
#define UART3_CLK_SET_MASK     0x100000
#define UART3_CLK_SET_POS      20
#define UART3_CLK_CLR_MASK     0x200000
#define UART3_CLK_CLR_POS      21
#define UART4_CLK_SET_MASK     0x400000
#define UART4_CLK_SET_POS      22
#define UART4_CLK_CLR_MASK     0x800000
#define UART4_CLK_CLR_POS      23
#define UART5_CLK_SET_MASK     0x1000000
#define UART5_CLK_SET_POS      24
#define UART5_CLK_CLR_MASK     0x2000000
#define UART5_CLK_CLR_POS      25
#define UART6_CLK_SET_MASK     0x4000000
#define UART6_CLK_SET_POS      26
#define UART6_CLK_CLR_MASK     0x8000000
#define UART6_CLK_CLR_POS      27
#define UART7_CLK_SET_MASK     0x10000000
#define UART7_CLK_SET_POS      28
#define UART7_CLK_CLR_MASK     0x20000000
#define UART7_CLK_CLR_POS      29
#define UART8_CLK_SET_MASK     0x40000000
#define UART8_CLK_SET_POS      30
#define UART8_CLK_CLR_MASK     0x80000000
#define UART8_CLK_CLR_POS      31
#define UART9_CLK_SET_MASK     0x1
#define UART9_CLK_SET_POS      0
#define UART9_CLK_CLR_MASK     0x2
#define UART9_CLK_CLR_POS      1
#define UART10_CLK_SET_MASK    0x4
#define UART10_CLK_SET_POS     2
#define UART10_CLK_CLR_MASK    0x8
#define UART10_CLK_CLR_POS     3
#define UART11_CLK_SET_MASK    0x10
#define UART11_CLK_SET_POS     4
#define UART11_CLK_CLR_MASK    0x20
#define UART11_CLK_CLR_POS     5
#define UART12_CLK_SET_MASK    0x40
#define UART12_CLK_SET_POS     6
#define UART12_CLK_CLR_MASK    0x80
#define UART12_CLK_CLR_POS     7
#define SPI1_CLK_SET_MASK      0x100
#define SPI1_CLK_SET_POS       8
#define SPI1_CLK_CLR_MASK      0x200
#define SPI1_CLK_CLR_POS       9
#define SPI2_CLK_SET_MASK      0x400
#define SPI2_CLK_SET_POS       10
#define SPI2_CLK_CLR_MASK      0x800
#define SPI2_CLK_CLR_POS       11
#define ADC1_CLK_SET_MASK      0x1000
#define ADC1_CLK_SET_POS       12
#define ADC1_CLK_CLR_MASK      0x2000
#define ADC1_CLK_CLR_POS       13
#define ADC2_CLK_SET_MASK      0x4000
#define ADC2_CLK_SET_POS       14
#define ADC2_CLK_CLR_MASK      0x8000
#define ADC2_CLK_CLR_POS       15
#define EXTI1_CLK_SET_MASK     0x10000
#define EXTI1_CLK_SET_POS      16
#define EXTI1_CLK_CLR_MASK     0x20000
#define EXTI1_CLK_CLR_POS      17
#define EXTI2_CLK_SET_MASK     0x40000
#define EXTI2_CLK_SET_POS      18
#define EXTI2_CLK_CLR_MASK     0x80000
#define EXTI2_CLK_CLR_POS      19
#define EXTI3_CLK_SET_MASK     0x100000
#define EXTI3_CLK_SET_POS      20
#define EXTI3_CLK_CLR_MASK     0x200000
#define EXTI3_CLK_CLR_POS      21
#define EXTI4_CLK_SET_MASK     0x400000
#define EXTI4_CLK_SET_POS      22
#define EXTI4_CLK_CLR_MASK     0x800000
#define EXTI4_CLK_CLR_POS      23
#define MJTAG1_CLK_SET_MASK    0x1000000
#define MJTAG1_CLK_SET_POS     24
#define MJTAG1_CLK_CLR_MASK    0x2000000
#define MJTAG1_CLK_CLR_POS     25
#define MJTAG2_CLK_SET_MASK    0x4000000
#define MJTAG2_CLK_SET_POS     26
#define MJTAG2_CLK_CLR_MASK    0x8000000
#define MJTAG2_CLK_CLR_POS     27
#define MJTAG3_CLK_SET_MASK    0x10000000
#define MJTAG3_CLK_SET_POS     28
#define MJTAG3_CLK_CLR_MASK    0x20000000
#define MJTAG3_CLK_CLR_POS     29
#define IWDT2_CLK_SET_MASK     0x40000000
#define IWDT2_CLK_SET_POS      30
#define IWDT2_CLK_CLR_MASK     0x80000000
#define IWDT2_CLK_CLR_POS      31
#define I3C2_CLK_SET_MASK      0x1
#define I3C2_CLK_SET_POS       0
#define I3C2_CLK_CLR_MASK      0x2
#define I3C2_CLK_CLR_POS       1
#define I3C3_CLK_SET_MASK      0x4
#define I3C3_CLK_SET_POS       2
#define I3C3_CLK_CLR_MASK      0x8
#define I3C3_CLK_CLR_POS       3
#define I3C4_CLK_SET_MASK      0x10
#define I3C4_CLK_SET_POS       4
#define I3C4_CLK_CLR_MASK      0x20
#define I3C4_CLK_CLR_POS       5
#define I3C5_CLK_SET_MASK      0x40
#define I3C5_CLK_SET_POS       6
#define I3C5_CLK_CLR_MASK      0x80
#define I3C5_CLK_CLR_POS       7
#define I3C6_CLK_SET_MASK      0x100
#define I3C6_CLK_SET_POS       8
#define I3C6_CLK_CLR_MASK      0x200
#define I3C6_CLK_CLR_POS       9
#define I3C7_CLK_SET_MASK      0x400
#define I3C7_CLK_SET_POS       10
#define I3C7_CLK_CLR_MASK      0x800
#define I3C7_CLK_CLR_POS       11
#define I3C8_CLK_SET_MASK      0x1000
#define I3C8_CLK_SET_POS       12
#define I3C8_CLK_CLR_MASK      0x2000
#define I3C8_CLK_CLR_POS       13
#define I3C9_CLK_SET_MASK      0x4000
#define I3C9_CLK_SET_POS       14
#define I3C9_CLK_CLR_MASK      0x8000
#define I3C9_CLK_CLR_POS       15
#define I3C10_CLK_SET_MASK     0x10000
#define I3C10_CLK_SET_POS      16
#define I3C10_CLK_CLR_MASK     0x20000
#define I3C10_CLK_CLR_POS      17
#define I3C11_CLK_SET_MASK     0x40000
#define I3C11_CLK_SET_POS      18
#define I3C11_CLK_CLR_MASK     0x80000
#define I3C11_CLK_CLR_POS      19
#define I3C12_CLK_SET_MASK     0x100000
#define I3C12_CLK_SET_POS      20
#define I3C12_CLK_CLR_MASK     0x200000
#define I3C12_CLK_CLR_POS      21
#define I3C13_CLK_SET_MASK     0x400000
#define I3C13_CLK_SET_POS      22
#define I3C13_CLK_CLR_MASK     0x800000
#define I3C13_CLK_CLR_POS      23
#define I3C14_CLK_SET_MASK     0x1000000
#define I3C14_CLK_SET_POS      24
#define I3C14_CLK_CLR_MASK     0x2000000
#define I3C14_CLK_CLR_POS      25
#define PECI1_CLK_SET_MASK     0x4000000
#define PECI1_CLK_SET_POS      26
#define PECI1_CLK_CLR_MASK     0x8000000
#define PECI1_CLK_CLR_POS      27
#define PECI2_CLK_SET_MASK     0x10000000
#define PECI2_CLK_SET_POS      28
#define PECI2_CLK_CLR_MASK     0x20000000
#define PECI2_CLK_CLR_POS      29
#define WWDT2_CLK_SET_MASK     0x40000000
#define WWDT2_CLK_SET_POS      30
#define WWDT2_CLK_CLR_MASK     0x80000000
#define WWDT2_CLK_CLR_POS      31
#define CPU_DBG_CLK_SET_MASK   0x1
#define CPU_DBG_CLK_SET_POS    0
#define CPU_DBG_CLK_CLR_MASK   0x2
#define CPU_DBG_CLK_CLR_POS    1
#define CACHE1_CLK_SET_MASK    0x4
#define CACHE1_CLK_SET_POS     2
#define CACHE1_CLK_CLR_MASK    0x8
#define CACHE1_CLK_CLR_POS     3
#define IOPMP_CLK_SET_MASK     0x10
#define IOPMP_CLK_SET_POS      4
#define IOPMP_CLK_CLR_MASK     0x20
#define IOPMP_CLK_CLR_POS      5
#define QSPI1_CLK_SET_MASK     0x40
#define QSPI1_CLK_SET_POS      6
#define QSPI1_CLK_CLR_MASK     0x80
#define QSPI1_CLK_CLR_POS      7
#define SHA512_CLK_SET_MASK    0x100
#define SHA512_CLK_SET_POS     8
#define SHA512_CLK_CLR_MASK    0x200
#define SHA512_CLK_CLR_POS     9
#define CALC_CRC_CLK_SET_MASK  0x1
#define CALC_CRC_CLK_SET_POS   0
#define CALC_CRC_CLK_CLR_MASK  0x2
#define CALC_CRC_CLK_CLR_POS   1
#define CALC_CLK_SET_MASK      0x4
#define CALC_CLK_SET_POS       2
#define CALC_CLK_CLR_MASK      0x8
#define CALC_CLK_CLR_POS       3
#define CRYPT_CLK_SET_MASK     0x10
#define CRYPT_CLK_SET_POS      4
#define CRYPT_CLK_CLR_MASK     0x20
#define CRYPT_CLK_CLR_POS      5
#define OTP_CTRL_CLK_SET_MASK  0x40
#define OTP_CTRL_CLK_SET_POS   6
#define OTP_CTRL_CLK_CLR_MASK  0x80
#define OTP_CTRL_CLK_CLR_POS   7
#define CALC_SHA_CLK_SET_MASK  0x100
#define CALC_SHA_CLK_SET_POS   8
#define CALC_SHA_CLK_CLR_MASK  0x200
#define CALC_SHA_CLK_CLR_POS   9
#define CALC_SM4_CLK_SET_MASK  0x400
#define CALC_SM4_CLK_SET_POS   10
#define CALC_SM4_CLK_CLR_MASK  0x800
#define CALC_SM4_CLK_CLR_POS   11
#define OTBN_CLK_SET_MASK      0x1000
#define OTBN_CLK_SET_POS       12
#define OTBN_CLK_CLR_MASK      0x2000
#define OTBN_CLK_CLR_POS       13
#define TPM_SPIS1_CLK_SET_MASK  0x4000
#define TPM_SPIS1_CLK_SET_POS  14
#define TPM_SPIS1_CLK_CLR_MASK  0x8000
#define TPM_SPIS1_CLK_CLR_POS  15
#define TPM_SPIS2_CLK_SET_MASK  0x10000
#define TPM_SPIS2_CLK_SET_POS  16
#define TPM_SPIS2_CLK_CLR_MASK  0x20000
#define TPM_SPIS2_CLK_CLR_POS  17
#define NIST_TRNG_CLK_SET_MASK 0x40000000
#define NIST_TRNG_CLK_SET_POS  30
#define NIST_TRNG_CLK_CLR_MASK 0x80000000
#define NIST_TRNG_CLK_CLR_POS  31
#define I2C1_CLK_SET_MASK      0x1
#define I2C1_CLK_SET_POS       0
#define I2C1_CLK_CLR_MASK      0x2
#define I2C1_CLK_CLR_POS       1
#define I3C1_CLK_SET_MASK      0x10
#define I3C1_CLK_SET_POS       4
#define I3C1_CLK_CLR_MASK      0x20
#define I3C1_CLK_CLR_POS       5
#define UART1_CLK_SET_MASK     0x100
#define UART1_CLK_SET_POS      8
#define UART1_CLK_CLR_MASK     0x200
#define UART1_CLK_CLR_POS      9
#define IWDT1_CLK_SET_MASK     0x1000
#define IWDT1_CLK_SET_POS      12
#define IWDT1_CLK_CLR_MASK     0x2000
#define IWDT1_CLK_CLR_POS      13
#define WWDT1_CLK_SET_MASK     0x4000
#define WWDT1_CLK_SET_POS      14
#define WWDT1_CLK_CLR_MASK     0x8000
#define WWDT1_CLK_CLR_POS      15
#define TRNG_CLK_SET_MASK      0x10000
#define TRNG_CLK_SET_POS       16
#define TRNG_CLK_CLR_MASK      0x20000
#define TRNG_CLK_CLR_POS       17
#define KSCAN_CLK_SET_MASK      0x1
#define KSCAN_CLK_SET_POS       0
#define KSCAN_CLK_CLR_MASK      0x2
#define KSCAN_CLK_CLR_POS       1
#define PS2IF1_CLK_SET_MASK     0x4
#define PS2IF1_CLK_SET_POS      2
#define PS2IF1_CLK_CLR_MASK     0x8
#define PS2IF1_CLK_CLR_POS      3
#define PS2IF2_CLK_SET_MASK     0x10
#define PS2IF2_CLK_SET_POS      4
#define PS2IF2_CLK_CLR_MASK     0x20
#define PS2IF2_CLK_CLR_POS      5
#define OWM_CLK_SET_MASK        0x40
#define OWM_CLK_SET_POS         6
#define OWM_CLK_CLR_MASK        0x80
#define OWM_CLK_CLR_POS         7
#define CEC_CLK_SET_MASK        0x100
#define CEC_CLK_SET_POS         8
#define CEC_CLK_CLR_MASK        0x200
#define CEC_CLK_CLR_POS         9
#define PIS_CLK_SET_MASK        0x400
#define PIS_CLK_SET_POS         10
#define PIS_CLK_CLR_MASK        0x800
#define PIS_CLK_CLR_POS         11
#define FILTER_CLK_SET_MASK     0x1000
#define FILTER_CLK_SET_POS      12
#define FILTER_CLK_CLR_MASK     0x2000
#define FILTER_CLK_CLR_POS      13
#define PDM_CLK_SET_MASK        0x4000
#define PDM_CLK_SET_POS         14
#define PDM_CLK_CLR_MASK        0x8000
#define PDM_CLK_CLR_POS         15
#define PARAL_CLK_SET_MASK      0x10000
#define PARAL_CLK_SET_POS       16
#define PARAL_CLK_CLR_MASK      0x20000
#define PARAL_CLK_CLR_POS       17
#define SGPIO1_MST_CLK_SET_MASK 0x40000
#define SGPIO1_MST_CLK_SET_POS  18
#define SGPIO1_MST_CLK_CLR_MASK 0x80000
#define SGPIO1_MST_CLK_CLR_POS  19
#define SGPIO2_MST_CLK_SET_MASK 0x100000
#define SGPIO2_MST_CLK_SET_POS  20
#define SGPIO2_MST_CLK_CLR_MASK 0x200000
#define SGPIO2_MST_CLK_CLR_POS  21
#define SGPIO1_MON_CLK_SET_MASK 0x400000
#define SGPIO1_MON_CLK_SET_POS  22
#define SGPIO1_MON_CLK_CLR_MASK 0x800000
#define SGPIO1_MON_CLK_CLR_POS  23
#define SGPIO2_MON_CLK_SET_MASK 0x1000000
#define SGPIO2_MON_CLK_SET_POS  24
#define SGPIO2_MON_CLK_CLR_MASK 0x2000000
#define SGPIO2_MON_CLK_CLR_POS  25
#define SMB_FLT1_CLK_SET_MASK   0x1
#define SMB_FLT1_CLK_SET_POS    0
#define SMB_FLT1_CLK_CLR_MASK   0x2
#define SMB_FLT1_CLK_CLR_POS    1
#define SMB_FLT2_CLK_SET_MASK   0x4
#define SMB_FLT2_CLK_SET_POS    2
#define SMB_FLT2_CLK_CLR_MASK   0x8
#define SMB_FLT2_CLK_CLR_POS    3
#define SMB_FLT3_CLK_SET_MASK   0x10
#define SMB_FLT3_CLK_SET_POS    4
#define SMB_FLT3_CLK_CLR_MASK   0x20
#define SMB_FLT3_CLK_CLR_POS    5
#define SMB_FLT4_CLK_SET_MASK   0x40
#define SMB_FLT4_CLK_SET_POS    6
#define SMB_FLT4_CLK_CLR_MASK   0x80
#define SMB_FLT4_CLK_CLR_POS    7

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_LSQSH_CLOCK_H_ */
