#ifndef REG_SYSC_APP_AWO_TYPE_H_
#define REG_SYSC_APP_AWO_TYPE_H_
#include <stdint.h>
#include "reg_base_addr.h"

#define SYSC_APP_AWO ((reg_sysc_app_awo_t *)APP_SYSC_AWO_APP_ADDR)

typedef struct
{
    volatile uint32_t RESERVED0[12];
    volatile uint32_t PD_AWO_CLK_CTRL1; //0x30
    volatile uint32_t RESERVED1[6];
    volatile uint32_t ETH_EMMC_RST; //0x4c
    volatile uint32_t ETH1_CLK_CFG; //0x50
    volatile uint32_t ETH1_RMII_CFG; //0x54
    volatile uint32_t ETH2_CLK_CFG; //0x58
    volatile uint32_t ETH2_RMII_CFG; //0x5c
    volatile uint32_t EMMC1_TX_RX_CLK; //0x60
    volatile uint32_t EMMC1_CORE_TIM_CLK; //0x64
    volatile uint32_t EMMC2_TX_RX_CLK; //0x68
    volatile uint32_t EMMC2_CORE_TIM_CLK; //0x6c
    volatile uint32_t LPC_CLK; //0x70
    volatile uint32_t RESERVED2[3];
#if 1
    volatile uint32_t IO_FUNC[4][8];
#else
    volatile uint32_t IOA_IOB_FUNC1_EN; //0x80
    volatile uint32_t IOC_IOD_FUNC1_EN; //0x84
    volatile uint32_t IOE_IOF_FUNC1_EN; //0x88
    volatile uint32_t IOG_IOH_FUNC1_EN; //0x8c
    volatile uint32_t IOI_IOJ_FUNC1_EN; //0x90
    volatile uint32_t IOK_IOM_FUNC1_EN; //0x94
    volatile uint32_t ION_IOQ_FUNC1_EN; //0x98
    volatile uint32_t IOT_FUNC1_EN; //0x9c
    volatile uint32_t IOA_IOB_FUNC2_EN; //0xa0
    volatile uint32_t IOC_IOD_FUNC2_EN; //0xa4
    volatile uint32_t IOE_IOF_FUNC2_EN; //0xa8
    volatile uint32_t IOG_IOH_FUNC2_EN; //0xac
    volatile uint32_t IOI_IOJ_FUNC2_EN; //0xb0
    volatile uint32_t IOK_IOM_FUNC2_EN; //0xb4
    volatile uint32_t ION_IOQ_FUNC2_EN; //0xb8
    volatile uint32_t IOT_FUNC2_EN; //0xbc
    volatile uint32_t IOA_IOB_FUNC3_EN; //0xc0
    volatile uint32_t IOC_IOD_FUNC3_EN; //0xc4
    volatile uint32_t IOE_IOF_FUNC3_EN; //0xc8
    volatile uint32_t IOG_IOH_FUNC3_EN; //0xcc
    volatile uint32_t IOI_IOJ_FUNC3_EN; //0xd0
    volatile uint32_t IOK_IOM_FUNC3_EN; //0xd4
    volatile uint32_t ION_IOQ_FUNC3_EN; //0xd8
    volatile uint32_t IOT_FUNC3_EN; //0xdc
    volatile uint32_t IOA_IOB_FUNC4_EN; //0xe0
    volatile uint32_t IOC_IOD_FUNC4_EN; //0xe4
    volatile uint32_t IOE_IOF_FUNC4_EN; //0xe8
    volatile uint32_t IOG_IOH_FUNC4_EN; //0xec
    volatile uint32_t IOI_IOJ_FUNC4_EN; //0xf0
    volatile uint32_t IOK_IOM_FUNC4_EN; //0xf4
    volatile uint32_t ION_IOQ_FUNC4_EN; //0xf8
    volatile uint32_t IOT_FUNC4_EN; //0xfc
#endif
} reg_sysc_app_awo_t;

enum SYSC_APP_AWO_REG_PD_AWO_CLK_CTRL1_FIELD {
    SYSC_APP_AWO_PSRAM_FLT_CTRL_MASK = (int)0xf000,
    SYSC_APP_AWO_PSRAM_FLT_CTRL_POS = 12,
    SYSC_APP_AWO_CLK_SEL_PSRAM_MASK = (int)0x1f0000,
    SYSC_APP_AWO_CLK_SEL_PSRAM_POS = 16,
    SYSC_APP_AWO_CLK_SEL_PSRAM_FLT_MASK = (int)0x600000,
    SYSC_APP_AWO_CLK_SEL_PSRAM_FLT_POS = 21,
    SYSC_APP_AWO_CLK_SEL_USB2_MASK = (int)0x7000000,
    SYSC_APP_AWO_CLK_SEL_USB2_POS = 24,
};

enum SYSC_APP_AWO_REG_ETH_EMMC_RST_FIELD {
    SYSC_APP_AWO_ETH1_CLK_TX_RST_N_MASK = (int)0x1,
    SYSC_APP_AWO_ETH1_CLK_TX_RST_N_POS = 0,
    SYSC_APP_AWO_ETH1_CLK_RX_RST_N_MASK = (int)0x2,
    SYSC_APP_AWO_ETH1_CLK_RX_RST_N_POS = 1,
    SYSC_APP_AWO_ETH1_CLK_RMII_RST_N_MASK = (int)0x4,
    SYSC_APP_AWO_ETH1_CLK_RMII_RST_N_POS = 2,
    SYSC_APP_AWO_ETH2_CLK_TX_RST_N_MASK = (int)0x10,
    SYSC_APP_AWO_ETH2_CLK_TX_RST_N_POS = 4,
    SYSC_APP_AWO_ETH2_CLK_RX_RST_N_MASK = (int)0x20,
    SYSC_APP_AWO_ETH2_CLK_RX_RST_N_POS = 5,
    SYSC_APP_AWO_ETH2_CLK_RMII_RST_N_MASK = (int)0x40,
    SYSC_APP_AWO_ETH2_CLK_RMII_RST_N_POS = 6,
    SYSC_APP_AWO_EMMC1_CLK_TX_RST_N_MASK = (int)0x100,
    SYSC_APP_AWO_EMMC1_CLK_TX_RST_N_POS = 8,
    SYSC_APP_AWO_EMMC1_CLK_RX_RST_N_MASK = (int)0x200,
    SYSC_APP_AWO_EMMC1_CLK_RX_RST_N_POS = 9,
    SYSC_APP_AWO_EMMC1_CLK_CORE_RST_N_MASK = (int)0x400,
    SYSC_APP_AWO_EMMC1_CLK_CORE_RST_N_POS = 10,
    SYSC_APP_AWO_EMMC1_CLK_TIM_RST_N_MASK = (int)0x800,
    SYSC_APP_AWO_EMMC1_CLK_TIM_RST_N_POS = 11,
    SYSC_APP_AWO_EMMC2_CLK_TX_RST_N_MASK = (int)0x1000,
    SYSC_APP_AWO_EMMC2_CLK_TX_RST_N_POS = 12,
    SYSC_APP_AWO_EMMC2_CLK_RX_RST_N_MASK = (int)0x2000,
    SYSC_APP_AWO_EMMC2_CLK_RX_RST_N_POS = 13,
    SYSC_APP_AWO_EMMC2_CLK_CORE_RST_N_MASK = (int)0x4000,
    SYSC_APP_AWO_EMMC2_CLK_CORE_RST_N_POS = 14,
    SYSC_APP_AWO_EMMC2_CLK_TIM_RST_N_MASK = (int)0x8000,
    SYSC_APP_AWO_EMMC2_CLK_TIM_RST_N_POS = 15,
    SYSC_APP_AWO_LPC1_CLK_RST_N_MASK = (int)0x10000,
    SYSC_APP_AWO_LPC1_CLK_RST_N_POS = 16,
    SYSC_APP_AWO_LPC2_CLK_RST_N_MASK = (int)0x20000,
    SYSC_APP_AWO_LPC2_CLK_RST_N_POS = 17,
};

enum SYSC_APP_AWO_REG_ETH1_CLK_CFG_FIELD {
    SYSC_APP_AWO_ETH1_CLK_TX_DIV_MASK = (int)0x3f,
    SYSC_APP_AWO_ETH1_CLK_TX_DIV_POS = 0,
    SYSC_APP_AWO_ETH1_CLK_TX_SEL_MASK = (int)0x3c0,
    SYSC_APP_AWO_ETH1_CLK_TX_SEL_POS = 6,
    SYSC_APP_AWO_ETH1_CLK_TX_CG_MASK = (int)0x400,
    SYSC_APP_AWO_ETH1_CLK_TX_CG_POS = 10,
    SYSC_APP_AWO_ETH1_CLK_RX_DIV_MASK = (int)0x3f0000,
    SYSC_APP_AWO_ETH1_CLK_RX_DIV_POS = 16,
    SYSC_APP_AWO_ETH1_CLK_RX_SEL_MASK = (int)0x7c00000,
    SYSC_APP_AWO_ETH1_CLK_RX_SEL_POS = 22,
    SYSC_APP_AWO_ETH1_CLK_RX_CG_MASK = (int)0x8000000,
    SYSC_APP_AWO_ETH1_CLK_RX_CG_POS = 27,
};

enum SYSC_APP_AWO_REG_ETH1_RMII_CFG_FIELD {
    SYSC_APP_AWO_ETH1_CLK_RMII_DIV_MASK = (int)0xf,
    SYSC_APP_AWO_ETH1_CLK_RMII_DIV_POS = 0,
    SYSC_APP_AWO_ETH1_CLK_RMII_SEL_MASK = (int)0x70,
    SYSC_APP_AWO_ETH1_CLK_RMII_SEL_POS = 4,
    SYSC_APP_AWO_ETH1_CLK_RMII_CG_MASK = (int)0x80,
    SYSC_APP_AWO_ETH1_CLK_RMII_CG_POS = 7,
};

enum SYSC_APP_AWO_REG_ETH2_CLK_CFG_FIELD {
    SYSC_APP_AWO_ETH2_CLK_TX_DIV_MASK = (int)0x3f,
    SYSC_APP_AWO_ETH2_CLK_TX_DIV_POS = 0,
    SYSC_APP_AWO_ETH2_CLK_TX_SEL_MASK = (int)0x3c0,
    SYSC_APP_AWO_ETH2_CLK_TX_SEL_POS = 6,
    SYSC_APP_AWO_ETH2_CLK_TX_CG_MASK = (int)0x400,
    SYSC_APP_AWO_ETH2_CLK_TX_CG_POS = 10,
    SYSC_APP_AWO_ETH2_CLK_RX_DIV_MASK = (int)0x3f0000,
    SYSC_APP_AWO_ETH2_CLK_RX_DIV_POS = 16,
    SYSC_APP_AWO_ETH2_CLK_RX_SEL_MASK = (int)0x7c00000,
    SYSC_APP_AWO_ETH2_CLK_RX_SEL_POS = 22,
    SYSC_APP_AWO_ETH2_CLK_RX_CG_MASK = (int)0x8000000,
    SYSC_APP_AWO_ETH2_CLK_RX_CG_POS = 27,
};

enum SYSC_APP_AWO_REG_ETH2_RMII_CFG_FIELD {
    SYSC_APP_AWO_ETH2_CLK_RMII_DIV_MASK = (int)0xf,
    SYSC_APP_AWO_ETH2_CLK_RMII_DIV_POS = 0,
    SYSC_APP_AWO_ETH2_CLK_RMII_SEL_MASK = (int)0x70,
    SYSC_APP_AWO_ETH2_CLK_RMII_SEL_POS = 4,
    SYSC_APP_AWO_ETH2_CLK_RMII_CG_MASK = (int)0x80,
    SYSC_APP_AWO_ETH2_CLK_RMII_CG_POS = 7,
};

enum SYSC_APP_AWO_REG_EMMC1_TX_RX_CLK_FIELD {
    SYSC_APP_AWO_EMMC1_CLK_TX_DIV_MASK = (int)0x3ff,
    SYSC_APP_AWO_EMMC1_CLK_TX_DIV_POS = 0,
    SYSC_APP_AWO_EMMC1_CLK_TX_SEL_MASK = (int)0x3c00,
    SYSC_APP_AWO_EMMC1_CLK_TX_SEL_POS = 10,
    SYSC_APP_AWO_EMMC1_CLK_TX_CG_MASK = (int)0x4000,
    SYSC_APP_AWO_EMMC1_CLK_TX_CG_POS = 14,
    SYSC_APP_AWO_EMMC1_CLK_RX_DIV_MASK = (int)0x3f0000,
    SYSC_APP_AWO_EMMC1_CLK_RX_DIV_POS = 16,
    SYSC_APP_AWO_EMMC1_CLK_RX_SEL_MASK = (int)0x3c00000,
    SYSC_APP_AWO_EMMC1_CLK_RX_SEL_POS = 22,
    SYSC_APP_AWO_EMMC1_CLK_RX_CG_MASK = (int)0x4000000,
    SYSC_APP_AWO_EMMC1_CLK_RX_CG_POS = 26,
};

enum SYSC_APP_AWO_REG_EMMC1_CORE_TIM_CLK_FIELD {
    SYSC_APP_AWO_EMMC1_CLK_CORE_DIV_MASK = (int)0xf,
    SYSC_APP_AWO_EMMC1_CLK_CORE_DIV_POS = 0,
    SYSC_APP_AWO_EMMC1_CLK_CORE_SEL_MASK = (int)0x70,
    SYSC_APP_AWO_EMMC1_CLK_CORE_SEL_POS = 4,
    SYSC_APP_AWO_EMMC1_CLK_CORE_CG_MASK = (int)0x80,
    SYSC_APP_AWO_EMMC1_CLK_CORE_CG_POS = 7,
    SYSC_APP_AWO_EMMC1_CLK_TIM_DIV_MASK = (int)0xf00,
    SYSC_APP_AWO_EMMC1_CLK_TIM_DIV_POS = 8,
    SYSC_APP_AWO_EMMC1_CLK_TIM_SEL_MASK = (int)0x7000,
    SYSC_APP_AWO_EMMC1_CLK_TIM_SEL_POS = 12,
    SYSC_APP_AWO_EMMC1_CLK_TIM_CG_MASK = (int)0x8000,
    SYSC_APP_AWO_EMMC1_CLK_TIM_CG_POS = 15,
};

enum SYSC_APP_AWO_REG_EMMC2_TX_RX_CLK_FIELD {
    SYSC_APP_AWO_EMMC2_CLK_TX_DIV_MASK = (int)0x3ff,
    SYSC_APP_AWO_EMMC2_CLK_TX_DIV_POS = 0,
    SYSC_APP_AWO_EMMC2_CLK_TX_SEL_MASK = (int)0x3c00,
    SYSC_APP_AWO_EMMC2_CLK_TX_SEL_POS = 10,
    SYSC_APP_AWO_EMMC2_CLK_TX_CG_MASK = (int)0x4000,
    SYSC_APP_AWO_EMMC2_CLK_TX_CG_POS = 14,
    SYSC_APP_AWO_EMMC2_CLK_RX_DIV_MASK = (int)0x3f0000,
    SYSC_APP_AWO_EMMC2_CLK_RX_DIV_POS = 16,
    SYSC_APP_AWO_EMMC2_CLK_RX_SEL_MASK = (int)0x3c00000,
    SYSC_APP_AWO_EMMC2_CLK_RX_SEL_POS = 22,
    SYSC_APP_AWO_EMMC2_CLK_RX_CG_MASK = (int)0x4000000,
    SYSC_APP_AWO_EMMC2_CLK_RX_CG_POS = 26,
};

enum SYSC_APP_AWO_REG_EMMC2_CORE_TIM_CLK_FIELD {
    SYSC_APP_AWO_EMMC2_CLK_CORE_DIV_MASK = (int)0xf,
    SYSC_APP_AWO_EMMC2_CLK_CORE_DIV_POS = 0,
    SYSC_APP_AWO_EMMC2_CLK_CORE_SEL_MASK = (int)0x70,
    SYSC_APP_AWO_EMMC2_CLK_CORE_SEL_POS = 4,
    SYSC_APP_AWO_EMMC2_CLK_CORE_CG_MASK = (int)0x80,
    SYSC_APP_AWO_EMMC2_CLK_CORE_CG_POS = 7,
    SYSC_APP_AWO_EMMC2_CLK_TIM_DIV_MASK = (int)0xf00,
    SYSC_APP_AWO_EMMC2_CLK_TIM_DIV_POS = 8,
    SYSC_APP_AWO_EMMC2_CLK_TIM_SEL_MASK = (int)0x7000,
    SYSC_APP_AWO_EMMC2_CLK_TIM_SEL_POS = 12,
    SYSC_APP_AWO_EMMC2_CLK_TIM_CG_MASK = (int)0x8000,
    SYSC_APP_AWO_EMMC2_CLK_TIM_CG_POS = 15,
};

enum SYSC_APP_AWO_REG_LPC_CLK_FIELD {
    SYSC_APP_AWO_LPC1_CLK_DIV_MASK = (int)0xf,
    SYSC_APP_AWO_LPC1_CLK_DIV_POS = 0,
    SYSC_APP_AWO_LPC1_CLK_SEL_MASK = (int)0x1f0,
    SYSC_APP_AWO_LPC1_CLK_SEL_POS = 4,
    SYSC_APP_AWO_LPC1_CLK_CG_MASK = (int)0x200,
    SYSC_APP_AWO_LPC1_CLK_CG_POS = 9,
    SYSC_APP_AWO_LPC2_CLK_DIV_MASK = (int)0xf0000,
    SYSC_APP_AWO_LPC2_CLK_DIV_POS = 16,
    SYSC_APP_AWO_LPC2_CLK_SEL_MASK = (int)0x1f00000,
    SYSC_APP_AWO_LPC2_CLK_SEL_POS = 20,
    SYSC_APP_AWO_LPC2_CLK_CG_MASK = (int)0x2000000,
    SYSC_APP_AWO_LPC2_CLK_CG_POS = 25,
};

enum SYSC_APP_AWO_REG_IOA_IOB_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOA_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOA_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOB_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOB_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOC_IOD_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOC_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOC_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOD_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOD_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOE_IOF_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOE_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOE_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOF_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOF_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOG_IOH_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOG_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOG_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOH_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOH_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOI_IOJ_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOI_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOI_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOJ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOK_IOM_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOK_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOK_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOM_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOM_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_ION_IOQ_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_ION_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_ION_EN_POS = 0,
    SYSC_APP_AWO_FUNC1_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC1_IOQ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOT_FUNC1_EN_FIELD {
    SYSC_APP_AWO_FUNC1_IOT_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC1_IOT_EN_POS = 0,
};

enum SYSC_APP_AWO_REG_IOA_IOB_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOA_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOA_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOB_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOB_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOC_IOD_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOC_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOC_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOD_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOD_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOE_IOF_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOE_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOE_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOF_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOF_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOG_IOH_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOG_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOG_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOH_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOH_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOI_IOJ_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOI_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOI_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOJ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOK_IOM_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOK_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOK_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOM_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOM_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_ION_IOQ_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_ION_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_ION_EN_POS = 0,
    SYSC_APP_AWO_FUNC2_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC2_IOQ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOT_FUNC2_EN_FIELD {
    SYSC_APP_AWO_FUNC2_IOT_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC2_IOT_EN_POS = 0,
};

enum SYSC_APP_AWO_REG_IOA_IOB_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOA_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOA_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOB_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOB_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOC_IOD_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOC_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOC_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOD_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOD_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOE_IOF_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOE_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOE_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOF_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOF_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOG_IOH_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOG_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOG_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOH_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOH_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOI_IOJ_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOI_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOI_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOJ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOK_IOM_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOK_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOK_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOM_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOM_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_ION_IOQ_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_ION_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_ION_EN_POS = 0,
    SYSC_APP_AWO_FUNC3_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC3_IOQ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOT_FUNC3_EN_FIELD {
    SYSC_APP_AWO_FUNC3_IOT_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC3_IOT_EN_POS = 0,
};

enum SYSC_APP_AWO_REG_IOA_IOB_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOA_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOA_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOB_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOB_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOC_IOD_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOC_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOC_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOD_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOD_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOE_IOF_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOE_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOE_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOF_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOF_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOG_IOH_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOG_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOG_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOH_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOH_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOI_IOJ_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOI_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOI_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOJ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOJ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOK_IOM_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOK_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOK_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOM_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOM_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_ION_IOQ_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_ION_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_ION_EN_POS = 0,
    SYSC_APP_AWO_FUNC4_IOQ_EN_MASK = (int)0xffff0000,
    SYSC_APP_AWO_FUNC4_IOQ_EN_POS = 16,
};

enum SYSC_APP_AWO_REG_IOT_FUNC4_EN_FIELD {
    SYSC_APP_AWO_FUNC4_IOT_EN_MASK = (int)0xffff,
    SYSC_APP_AWO_FUNC4_IOT_EN_POS = 0,
};

#endif
