import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [
    '../../Source/main.c',
    '../../Source/at_sig_mesh_prover_recv_cmd.c',
    '../../Source/at_sig_mesh_prover_cmd_parse.c',
    '../../Source/at_sig_mesh_prover_cmd_ind.c',
]
inc = [
    '../../Include/.',
    '../../.',
]
env.app_build('sig_mesh_provisioner',src,inc,mesh = True)