import os
env = Environment(ENV = os.environ)
env['SDK_ROOT'] = Dir('../../../')
env.SConscript(env['SDK_ROOT'].File('soc/SConscript'),exports=['env'])
src = [    
    '$BASE_ARCH/FlashDev.c',
    '$BASE_ARCH/FlashPrg.c',
]
inc = [
    '.'
]
env['LINKSCRIPT'] = File(env.subst('$BASE_ARCH/flash_prog_link.txt'))
env.image_build('flash_prog',src,inc)
